### ISSUE TITLE
libhogweed.so.6 failed to reference __gmpn_cnd_swap  

### ISSUE THREAD

**Issue by Hoek67** [openscad/openscad#4903] opened 2023-12-23 13:30 UTC
Trying to compile OpenSCAD on Ubuntu (latest).

Get near the last step.

following instructions on https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Building_on_Linux/UNIX

This step has an error.
![image](https://github.com/openscad/openscad/assets/18671600/3f8cbe8e-0b4d-4cb9-885a-ae8cd109382b)

gets error...

![image](https://github.com/openscad/openscad/assets/18671600/86ce4764-c199-41a6-9ce2-8ecad6db47cc)

![image](https://github.com/openscad/openscad/assets/18671600/cdc0516a-dab1-4aee-86fa-42ba479de2e8)

I'd like to have a look at the export code and hopefully add a zip option with .obj and .mat in it.

I'm not a Linux person so tried a few things and it didn't fix it. (ie. install nettle)

Any help appreciated.

Seems GMP got broken somewhere.

**Comment by kintel** [comment] 2023-12-23 13:40
If you're not trying to do something very specific, the install guide recommends `./scripts/uni-get-dependencies.sh`, not `./scripts/uni-build-dependencies.sh`.

**Comment by t-paul** [comment] 2023-12-23 14:00
Also duplicate of #4741.

**Closed by t-paul** 2023-12-23 14:00 UTC
Labels: Type: Discussion
