### ISSUE TITLE
Dark Mode not working on Windows 11

### ISSUE THREAD

**Issue by Zoestra** [openscad/openscad#4731] opened 2023-08-30 18:31 UTC
**Describe the bug**

openscad window uses light mode despite system theme being set to dark mode

**Screenshots**
![image](https://github.com/openscad/openscad/assets/79121105/2291496e-dd6e-4bf8-9efb-5e90249fbd08)

**Environment and Version info (please complete the following information):**
Windows 11 Pro 22H2 - 22321.2215
AMD Ryzen 9 3900x
OpenSCAD version 2021.01 

**Additional context**
at first i wasnt sure if i was missing an option somewhere or not, and theres scant information about how to activate dark mode on any forums that i could find. i was able to change the color schemes of the render window and the edit window, but have so far not been able to find anywhere to change the window color.

**Comment by t-paul** [comment] 2023-08-30 18:35
Duplicate of #4693.

Could you try with the dev snapshot version, if that has the same problem?

**Closed by t-paul** 2023-08-30 18:35 UTC
Labels: Type: Bug
