### ISSUE TITLE
Allow dynamically generated options in Customizer drop downs

### ISSUE THREAD

**Issue by davejlong** [openscad/openscad#4352] opened 2022-09-12 15:34 UTC
When building out customizer dropdown menus, I've often found it would be helpful if I could use some SCAD code to generate the options for those drop downs. For example, [this pull request](https://github.com/hominoids/SBC_Case_Builder/pull/10/files) on SBC_Case_Builder creates a one line script that is used to get a list of SBC boards to put into the drop down options for the Customizer. It would be helpful if comment for the drop down actually just runs the script to get the list instead.

**Comment by jordanbrown0** [comment] 2024-03-25 23:26
Duplicate of #4427.

**Closed by jordanbrown0** 2024-03-25 23:26 UTC
