### ISSUE TITLE
Missing support for points, lines

### ISSUE THREAD

**Issue by mrvn** [openscad/openscad#1659] opened 2016-06-04 07:02 UTC
I'm using openscad to generate dxf files for a laser cutter with great success. But not everything is possible. Specifically one can not draw points and lines in openscad.

Points: I wanted to cut out a lamp shade showing the night sky with holes for the stars but drawing them as tiny circles has two problems: 1) A line segment puts too much power on a small area making a large and ugly hole. 2) offset() will shrink the hole into nothingness and remove it.

Lines: I've seen designs for laser cutting that uses lines to allow the part to be easily bend without falling apart or breaking. Using thin squares has the same 2 problems as circles for points.

**Comment by t-paul** [comment] 2016-06-04 11:15
Closing as duplicate of #508.

**Closed by t-paul** 2016-06-04 11:15 UTC
