### ISSUE TITLE
Feature: Method to convert imported dxf to point vector for point vector based modules and functions

### ISSUE THREAD

**Issue by Jerimon1998** [openscad/openscad#1976] opened 2017-03-28 01:02 UTC
In my efforts to create a hyperbolic worm gear in OpenSCAD, I found that the "cleanest" way for me to create the desired shape was to use the sweep() module, as it is found in list-comprehension-demos.
The problem is that I need to use an involute gear as the base shape, and the involute_gears file in the MCAD library will only produce either a 2D shape or a 3D extrusion.
I have found my own workaround of generating a .dxf file of an involute profile, then converting it to a 2D .xyz file in a separate program. Finally I edit the .xyz file with Notepad++, replacing carriage return and end-of-line characters with the brackets and commas needed to paste it directly into the .scad file.
This produces a point array that I can use in sweep().
My intent of using OpenSCAD, however, was to make a fully parametric version that could be used in the Thingiverse Customizer. I can scale the built-in gear profile, and Customizer does allow users to upload their own .dxf file for the .scad file to use, but there is nothing else I can make of it, short of putting the algorithm to calculate the points of an involute gear directly into the .scad file (too tedious for the coder, the Customizer server(s), and the user).
.dxf files are constituted by vertexes, among other things, so it should(?) be easy to convert it to points instead of a 2D shape.

**Comment by t-paul** [comment] 2017-03-28 07:05
Closing as duplicate of #1324.

I'm not sure that would help with the Thingiverse Customizer though, the [documentation](http://customizer.makerbot.com/docs) still says in section Limitations: "Cannot import external files (like .stl or .dxf files)". Or did that change lately?

**Closed by t-paul** 2017-03-28 07:05 UTC
