### ISSUE TITLE
Editor - Line Wrap Preference - Indent?

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2670] opened 2019-01-01 20:26 UTC
The pref;
View/Preferences/Editor/Line-Wrap/Line-wrap-indentation/Style:Indented is either wrong or non-intuitive.
It uses the Indentation-width from the Indentation box above, not the Indent value to the right, ie;
![linewrap indent](https://user-images.githubusercontent.com/1972961/50576028-64f47300-0e5d-11e9-8241-85a19683d039.JPG)

This may be intentional, forcing the same indent, and thus the adjacent Indent value is only meaningful for Fixed indent, if so the adjacent field should be greyed or blanked for other than Fixed. 
However, I suspect it should use the adjacent Indent value.

**Comment by Sharma-Hrishabh** [comment] 2020-02-07 15:42
Hey, this issue looks interesting to me, and I would get an overview of the GUI portion code of openscad. Should I go ahead? 
It would be great if I can get some hints.

**Comment by t-paul** [comment] 2020-02-07 20:06
Sure, that would be great. I guess the first step would be to find out what's going on by checking the current GUI against the features documented for [QScintilla](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciScintilla.html). There's a huge amount of settings so it could be a simple bug in the code (referencing the wrong input box to read from), a misunderstanding of the features provided (maybe there's not even a separate setting), or something else completely.

**Comment by Sharma-Hrishabh** [comment] 2020-02-08 07:04
Hey @t-paul , what I observed after exploring the editor and preferences file is that all things are correct there. I read the documentation and observed 'WrapIndentMode' enum, which is being used in our editor to control that LineWrap Indent functionality.
It is written that-
-'Same' will not take any value from Indent spin box in LineWrapIndent, and will indent as per the first sub-line.
-'Fixed' takes value from Indent spin box in LineWrapIndent and put indentation accordingly.
-'Indent' mode is something different, it indents as per first sub-line plus an extra indentation.

![enter image description here](https://lh3.googleusercontent.com/oexajJS5MUg2WtIvHLrKF-sybSeD9BQmlVPAZNA1_JUocQWK3pZpcILgU7T0mM6z3rxBVuTqOqj5a_qREPcAQLxsA4XQCZi5wc430eMWFCtI06jnDDgHgODTc2VamDD0YKirkp1KAbTpj2BL5bKAq0KfwgUnL9uT3Vk4O7mLbwNWULEDGCe-DGCbh_baU8NkVbOZ6BC5vr_uqtGdCknCItU3vNAKAmtkhj6xOljruvZQiS3wbFxtN3tPYwSk_po3RNZOKVCCYtOoQkQvVmeaqnWrRRDvjqGvEPDg2xXES7FitITBP3hKn84yzPgZnl1x905rMyRYWMo8JE40o8AiHmBI8WkfnC8VSmVLT3tAIK6v8Jnp-ApGYQtU33uwemGEaCbXr642CKv_MUbHim47G1IDleQOVtqctiFACY4hm_qyfQarcS42aq4mjo9j5n9SvVNEjGRuNtodbWweUR3b0zx_XkKXERC-3FoggfQ0BrAsZ7LBoLZ5RtUH_zUK84hRn9yC-MAZJnFZK9_b_YHZqxEDl_fwfeQrpRKEoBvC5seMmB_iPzNi34Y-t4OxkMWSozPQpTwUgYCtRvurWYUXYwSJQ21vcXMkShPfCzQwalgJplfEynQSxcXFr9l35oWVDbIsqDCl7jUW29S3jXr2gbn_bBQSvfQHPC_LVFFeTeHERxJypAJ9wQ=w895-h312-no)

Now, what is happening while using Indented Style, in LineWrap is that, it is actually not taking any value from the spinbox, which is already an expected behaviour, and when we are varying the Indent Width from Indentation settings, it is actually changing the indentation value as new indentation value is the sum of indentation of first sub-line and indentation width, and we are varying the indentation width.
So, it's not a bug. What we can do, at user-end, to make things simpler is that, we can disable the 'indent' spin box in LineWrap during 'Indented' LineWrapStyle, to avoid any confusion.
So, what's your view on this?

**Comment by t-paul** [comment] 2020-02-09 18:12
Nice summary, thanks. Yes, it seems disabling the input field for 'Indent' should make it clear enough the value is not used for this mode. So basically only 'Fixed' will have the spinbox enabled.

Looks like we can't yet add the new 'DeepIndent' option as that's introduced later than the v2.9 version we have as minimum (unless there's a simple and not too ugly way to detect that).

**Comment by Sharma-Hrishabh** [comment] 2020-02-09 18:17
So, should I go for disabling it ?

**Comment by t-paul** [comment] 2020-02-09 18:18
That would be great, yes.

**Comment by t-paul** [comment] 2020-02-16 15:53
Fixed via #3212.

**Closed by t-paul** 2020-02-16 15:53 UTC
Labels: Comp: GUI, Comp: Preferences, Type: Bug
