### ISSUE TITLE
SubArray Management in Customiser.

### ISSUE THREAD

**Issue by MrBenGriffin** [openscad/openscad#4708] opened 2023-07-27 11:39 UTC
**Is your feature request related to a problem? **
When using the customizer, it would be really nice to be able to manage dynamic arrays of sub-arrays.  Currently I have to name each subarray, provide a checkbox for whether or not to include it, and likewise name each subarray with a set of different variables.

*If this is already supported, then the documentation needs to be updated.*

**Describe the solution you'd like**
Being able to add / remove a new subarray to an array would allow for far more control over customising models which are array-like.

**Describe alternatives you've considered**
See above for the current approach I am taking.

**Additional context**

![image](https://github.com/openscad/openscad/assets/1785064/1b52cb80-a869-4b95-a2c8-1c541fa4495f)

![image](https://github.com/openscad/openscad/assets/1785064/e0e97f26-9fda-41a1-a1db-77097cf7bf35)

**Comment by jordanbrown0** [comment] 2024-03-25 23:33
Duplicate of #3817 .

**Closed by jordanbrown0** 2024-03-25 23:33 UTC
Labels: Type: Enhancement
