### ISSUE TITLE
CGAL assertion failure when differencing moderate complexity models

### ISSUE THREAD

**Issue by dmopalmer** [openscad/openscad#396] opened 2013-06-08 23:48 UTC
A difference of a 5k polygon model with itself (shifted) leads to an assertion error.  A simpler (1k polygons) model does not.  Larger models also cause the assertion.  

Tarball is at 
https://dl.dropboxusercontent.com/u/9855476/difference_test.tgz

CGAL error in CGAL_Nef_polyhedron's difference operator: CGAL ERROR: assertion violation!
Expr: itl != it->second.end()

(All models were generated (by quadratic edge decimation)  using meshlab from the Venus of Willendorf model at turbosquid.  This is a paleolithic sculpture of a nude woman, so NSFW if your work involves knapping flint spear points.)

---

``` openscad

module thing()
{   // 5k model causes assertion failure.    1K model no problem
     import("venus_5k.stl",convexity=10);
//  import("venus_1k.stl",convexity=10);
}

module diff()
{
    difference()
    {
        child(0);
        translate([1,0,0]) child(0);
    }
}

render() diff() thing();
```

Versions:
OpenScad 2013.05.25 binary distribution (also seen on 2013.1 installed using MacPorts) on Mac OSX 10.8.4.
##

**Comment by kintel** [comment] 2015-01-22 19:43
To clarify: It looks like subtracting two well-formed, valid and simple manifold objects in CGAL triggers the mentioned assertion. This sounds like a bug in CGAL.
```
CGAL error: assertion violation!
Expression : itl != it->second.end()
File       : /Users/kintel/code/OpenSCAD/openscad/../libraries/install/include/CGAL/Nef_3/SNC_external_structure.h
Line       : 1102
```

**Comment by thehans** [comment] 2021-06-10 18:58
Original links are broken, unable to reproduce.  Please re-open or create new issue if models which reproduce the issue can be provided.
Closing

**Closed by thehans** 2021-06-10 18:58 UTC
Labels: Dep: CGAL, Ext: CGAL Bug
