### ISSUE TITLE
OpenGL Validation Error during launch from terminal on OSX10.9

### ISSUE THREAD

**Issue by Kharms** [openscad/openscad#772] opened 2014-05-01 18:20 UTC
![screen shot 2014-05-01 at 2 19 45 pm](https://cloud.githubusercontent.com/assets/7454464/2855490/39fcb79e-d15d-11e3-8294-a423685bdfc2.png)

**Comment by kintel** [comment] 2015-01-22 20:52
Closing as duplicate of #205

**Closed by kintel** 2015-01-22 20:52 UTC
Labels: OS X
