### ISSUE TITLE
Critical error on including files to SCAD object file

### ISSUE THREAD

**Issue by ManfredEP** [openscad/openscad#1806] opened 2016-09-27 11:34 UTC
just a few minutes ago my OpenSCAD installation crashes with error message:
a critical error was caught. boost::filesystem::read_symlink
original in german the next:
request is not supported (or so)
and the path.
It comes up in use and include statements. Ther is no symlink in path but a NTFS mount point. 
These are screen shots:
![error_scad_1](https://cloud.githubusercontent.com/assets/22472254/18871646/a39f8d34-84b6-11e6-8962-033d7ce77de7.jpg)
![error_scad_2](https://cloud.githubusercontent.com/assets/22472254/18871651/a7c3303c-84b6-11e6-82a7-edfe29184147.jpg)
The module ModBoden uses some of the other modules so there are double-includes in it.

**Comment by kintel** [comment] 2016-09-27 11:52
This looks like a duplicate of #1309

**Comment by t-paul** [comment] 2016-09-27 15:04
Yeah, same error message, just in German. Unfortunately we can't easily solve that as the issue seems to be in boost itself (linked in #1309).

Closing as duplicate.

**Closed by t-paul** 2016-09-27 15:04 UTC
