### ISSUE TITLE
multiple warnings cause system (windows) to freeze

### ISSUE THREAD

**Issue by UBaer21** [openscad/openscad#5254] opened 2024-08-07 05:28 UTC
**Environment**
Windows10 64-bit
openSCAD 2024.07.27

**Issue**
If "stop at first warning" is disabled (or working with points) a loop with a e.g. typo will cause a freeze for minutes (depending the loop)
it seems every warning msg increase the time by 0.5 seconds (increasing) .
loop 50 = 3 sec
loop 100= 12sec
loop 150= 30sec
loop 200= 50 sec
loop 250= 75 sec
loop 300= 110 sec
loop 400= 180 sec (3 min )
double the loop (2×) size increases time nearly fourfold (4×) 
time ≅ 2^(loop/100) * 10
```
a=undef; // or typo
for (i=[0:200]) rotate(i*j+a) cube();
```

If this can't be fixed a option "stop after 20 warnings" would be very much appreciated.

**Comment by thehans** [comment] 2024-08-07 05:46
Closing as duplicate of #4459

**Closed by thehans** 2024-08-07 05:46 UTC
Labels: Type: Discussion
