### ISSUE TITLE
Text rendering error when maximising window on non primary screen

### ISSUE THREAD

**Issue by SuperRoach** [openscad/openscad#1863] opened 2016-11-13 00:40 UTC
![mumt4mm](https://cloud.githubusercontent.com/assets/63333/20242950/e6fffcfe-a995-11e6-9ced-4cbe4192c676.png)

(Note how the translate is overlapping its own ( ) parameters container)

When using Openscad, if you move it to a secondary screen, and maximise it, the font size goes larger. Then when you begin to type, the text is overlapping itself. 

The text warping will stay like this until you close the program.

When you type in it, the text becomes increasingly distorted and overlapping.
(latest dev snapshot), Windows 10

**Comment by kintel** [comment] 2016-11-13 00:42
Closing as duplicate of #1624

**Closed by kintel** 2016-11-13 00:42 UTC
