### ISSUE TITLE
OpenSCAD Stuck on Folder Permissions

### ISSUE THREAD

**Issue by vcao** [openscad/openscad#4845] opened 2023-11-21 20:14 UTC
**Describe the bug**
User is stuck in a permission loop upon opening OpenSCAD on MacOS Sonoma 14.1.1 even after full permissions are granted (Files and Folders as well as Full Disk Access). 

**To Reproduce**
1. Open OpenSCAD
2. Security prompt that the file was downloaded outside the App Store.
3. Navigate to security settings and override using 'Open Anyway'
4. Open OpenSCAD again and select file scad file in Downloads folder.
5. Prompted to "OpenSCAD.app" would like to access files in your Documents folder. Select OK.
6. Prompted to "OpenSCAD.app" would like to access files in your Downloads folder. Select OK.
7. Repeat Steps 5-6 continuously until OpenSCAD crashes.

**Expected behavior**
OpenSCAD launches.

**Screenshots**
<img width="260" alt="Screenshot 2023-11-21 at 12 05 41 PM" src="https://github.com/openscad/openscad/assets/692998/d5f60c44-8c94-4fd9-8c35-233d39167e41">
<img width="260" alt="Screenshot 2023-11-21 at 12 05 44 PM" src="https://github.com/openscad/openscad/assets/692998/85ea2372-c829-4faf-a79a-70807e06a41f">

**Environment and Version info (please complete the following information):**
 - OS: MacOS Sonoma 14.1.1
 - System: Macbook Pro 14 M1 Max, 64 GB RAM, 2 TB Storage
 - OpenSCAD Version version 2023.11.20 (git f602162d2) downloaded from openscad.org

**Comment by kintel** [comment] 2023-11-21 20:38
Duplicate of #4059

**Closed by kintel** 2023-11-21 20:38 UTC
Labels: Type: Bug
