### ISSUE TITLE
Wireframe view F11 needs two objects

### ISSUE THREAD

**Issue by UBaer21** [openscad/openscad#3984] opened 2021-11-21 22:15 UTC
New file 
cube()  render F11 ⇒ nothing
second cube render  ⇒ wireframe view
same with other objects even complex polyhedron you always need a second object to see the Wireframe.  Which might be a bit confusing. (also that it needs a render while other views don't )
(version 21.10.19  win64)
AND  F12 thrown together view doesn't work when "view edges" is on

**Comment by DavidCromp** [comment] 2022-01-15 20:11
Unfortunately this is a known issue, as currently wireframe only supports CGAL meshes as discussed in #2031.

**Comment by thehans** [comment] 2022-01-15 20:29
Closing as duplicate of #2031

**Closed by thehans** 2022-01-15 20:29 UTC
