### ISSUE TITLE
CGAL Assertion error

### ISSUE THREAD

**Issue by oysteinkrog** [openscad/openscad#1090] opened 2014-12-20 21:03 UTC
I have a closed-source design I am working on and I get assertion errors when rendering:
I will try to create a repro project, but for now:

Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
PolySet has nonplanar faces. Attempting alternate construction
PolySet has nonplanar faces. Attempting alternate construction
PolySet has nonplanar faces. Attempting alternate construction
PolySet has nonplanar faces. Attempting alternate construction
CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation!
Expr: pe_prev->is_border() || !internal::Plane_constructor<Plane>::get_plane(pe_prev->facet(),pe_prev->facet()->plane()).is_degenerate()
File: /data/OpenSCAD/libraries-mingw64-master/mxe-w64/usr/x86_64-w64-mingw32.static/include/CGAL/Nef_3/polyhedron_3_to_nef_3.h
Line: 251
PolySet has nonplanar faces. Attempting alternate construction
PolySet has nonplanar faces. Attempting alternate construction

OpenSCAD Version: 2014.12.20
System information: Windows 8 (v6.2) 4 CPUs 15.98 GB RAM
Compiler, build date: GCC "4.9.2" 64bit, Dec 20 2014
Boost version: 1_57
Eigen version: 3.2.2
CGAL version, kernels: 4.5, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.3.2
Qt version: 5.4.0
QScintilla version: 2.8.4
MingW build: MingW64
GLib version: 2.42.1
Application Path: C:/Program Files/OpenSCAD
Documents Path: C:\Users\Øystein\Documents
Resource Path: C:/Program Files/OpenSCAD
User Library Path: 
User Config Path: C:\Users\Øystein\AppData\Local/OpenSCAD
Backup Path: 
OPENSCADPATH: 
OpenSCAD library path:

C:/Program Files/OpenSCAD\libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 1.11.0
OpenGL Version: 4.4.0
GL Renderer: GeForce GTX 570/PCIe/SSE2
GL Vendor: NVIDIA Corporation
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Using QGLWidget

GL Extensions:
GL_AMD_multi_draw_indirect
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_compute_variable_group_size
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_imaging
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counters
GL_ARB_shader_bit_encoding
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_sparse_texture
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_draw_buffers
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_EXTX_framebuffer_mixed_formats
GL_EXT_Cg_shader
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_bindable_uniform
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_import_sync_object
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_shader_objects
GL_EXT_separate_specular_color
GL_EXT_shader_image_load_store
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_object
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback2
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_EXT_vertex_attrib_64bit
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_KHR_blend_equation_advanced
GL_KHR_debug
GL_KTX_buffer_region
GL_NVX_conditional_render
GL_NVX_gpu_memory_info
GL_NV_ES1_1_compatibility
GL_NV_ES3_1_compatibility
GL_NV_bindless_multi_draw_indirect
GL_NV_bindless_multi_draw_indirect_count
GL_NV_blend_equation_advanced
GL_NV_blend_square
GL_NV_compute_program5
GL_NV_conditional_render
GL_NV_copy_depth_to_color
GL_NV_copy_image
GL_NV_depth_buffer_float
GL_NV_depth_clamp
GL_NV_draw_texture
GL_NV_explicit_multisample
GL_NV_fence
GL_NV_float_buffer
GL_NV_fog_distance
GL_NV_fragment_program
GL_NV_fragment_program2
GL_NV_fragment_program_option
GL_NV_framebuffer_multisample_coverage
GL_NV_geometry_shader4
GL_NV_gpu_program4
GL_NV_gpu_program4_1
GL_NV_gpu_program5
GL_NV_gpu_program5_mem_extended
GL_NV_gpu_program_fp64
GL_NV_gpu_shader5
GL_NV_half_float
GL_NV_light_max_exponent
GL_NV_multisample_coverage
GL_NV_multisample_filter_hint
GL_NV_occlusion_query
GL_NV_packed_depth_stencil
GL_NV_parameter_buffer_object
GL_NV_parameter_buffer_object2
GL_NV_path_rendering
GL_NV_pixel_data_range
GL_NV_point_sprite
GL_NV_primitive_restart
GL_NV_register_combiners
GL_NV_register_combiners2
GL_NV_shader_atomic_counters
GL_NV_shader_atomic_float
GL_NV_shader_buffer_load
GL_NV_shader_storage_buffer_object
GL_NV_shader_thread_group
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_compression_vtc
GL_NV_texture_env_combine4
GL_NV_texture_expand_normal
GL_NV_texture_multisample
GL_NV_texture_rectangle
GL_NV_texture_shader
GL_NV_texture_shader2
GL_NV_texture_shader3
GL_NV_transform_feedback
GL_NV_transform_feedback2
GL_NV_vertex_array_range
GL_NV_vertex_array_range2
GL_NV_vertex_attrib_integer_64bit
GL_NV_vertex_buffer_unified_memory
GL_NV_vertex_program
GL_NV_vertex_program1_1
GL_NV_vertex_program2
GL_NV_vertex_program2_option
GL_NV_vertex_program3
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_lod
GL_SGIX_depth_texture
GL_SGIX_shadow
GL_SUN_slice_accum
GL_WIN_swap_hint
WGL_EXT_swap_control

**Comment by oysteinkrog** [comment] 2015-01-03 14:36
Here is repro, I'm sorry I could not simplify it more:

```
use <scad-utils/lists.scad>
use <scad-utils/trajectory.scad>
use <scad-utils/trajectory_path.scad>
use <scad-utils/transformations.scad>
use <scad-utils/shapes.scad>
use <scad-utils/linalg.scad>
use <scad-utils/se3.scad>
use <scad-utils/so3.scad>
use <scad-utils/hull.scad>
use <list-comprehension-demos/skin.scad>
use <list-comprehension-demos/sweep.scad>
use <list-comprehension-demos/draw-helpers.scad>

// small number
e=.02;

function transform_pre(vec_m, t) = [for(m=vec_m) t*m];
function transform_post(vec_m, t) = [for(m=vec_m) m*t];
function path_offset(path,offset=[0,0,0]) = transform_post(path, translation(offset));
function path_offset_z(path,offset=0) = path_offset(path,[0,0,offset]);

column_degrees=5*(19.1/((PI*65)/180));
path_lq = [[65, 0, 0], [64.9604, 0, -2.26847], [64.8417, 0, -4.53417], [64.6439, 0, -6.79435], [64.3674, 0, -9.04625], [64.0125, 0, -11.2871], [63.5796, 0, -13.5143], [63.0692, 0, -15.7249], [62.482, 0, -17.9164], [61.8187, 0, -20.0861], [61.08, 0, -22.2313], [60.267, 0, -24.3494], [59.3805, 0, -26.4379], [58.4216, 0, -28.4941], [57.3916, 0, -30.5157], [56.2917, 0, -32.5], [55.1231, 0, -34.4448], [53.8874, 0, -36.3475], [52.5861, 0, -38.206], [51.2207, 0, -40.018], [49.7929, 0, -41.7812], [48.3044, 0, -43.4935], [46.7571, 0, -45.1528], [45.1528, 0, -46.7571], [43.4935, 0, -48.3044], [41.7812, 0, -49.7929], [40.018, 0, -51.2207], [38.206, 0, -52.5861], [36.3475, 0, -53.8874], [34.4448, 0, -55.1231], [32.5, 0, -56.2917], [30.5157, 0, -57.3916], [28.4941, 0, -58.4216], [26.4379, 0, -59.3805], [24.3494, 0, -60.267], [22.2313, 0, -61.08], [20.0861, 0, -61.8187], [17.9164, 0, -62.482], [15.7249, 0, -63.0692], [13.5143, 0, -63.5796], [11.2871, 0, -64.0125], [9.04625, 0, -64.3674], [6.79435, 0, -64.6439]];

path_q_lq = construct_transform_path(path_lq,1,1);

// a transform that is applied to the function values before quantization
cols_t_pre=
translation([0,45.7,0])
* rotation([-15,0,0])
* translation([0,0,65])
* rotation([0,90-column_degrees/2,0])
* rotation([0,6,0]);

path_t = transform_pre(path_q_lq, cols_t_pre);

extrasize=[
    [5,10],
    [9.45,9.95]
];

path_t_start = path_t[0];
path_t_end = path_t[len(path_t)-1];

path_t_start_e_ = path_t_start * translation([0,0,-extrasize[0][0]]);
path_t_end_e_ = path_t_end * translation([0,0,extrasize[0][1]]);

s_t1 = translation_part(path_t_start);
s_t2 = translation_part(path_t_start_e_);
s_t3 = [s_t2[0],s_t2[1],s_t1[2]];

e_t1 = translation_part(path_t_end);
e_t2 = translation_part(path_t_end_e_);
e_t3 = [e_t2[0],e_t2[1],e_t1[2]];

path_t_start_e = construct_rt(rotation_part(path_t_start_e_), s_t3);
path_t_end_e = construct_rt(rotation_part(path_t_end_e_), e_t3);

// extended path
path_t_ext_solid_ = concat([path_t_start_e], path_t, [path_t_end_e]);

offset = extrasize[1][1] - ((extrasize[1][0]+extrasize[1][1])/2);
width = extrasize[1][0] + extrasize[1][1];

path_z=[for(t=path_t_ext_solid_) translation_part(t)[2]];
low_point = min(path_z);
top_point = max(path_z);
height = (top_point-low_point);

path_t_ext_top_ = path_offset(path_t_ext_solid_,[-height/2,offset+e,0]);
path_t_ext_top = transform_post(path_t_ext_top_, rotation([0,180,0]));
path_t_ext_middle_ = path_offset(path_t_ext_solid_,[-height,offset,0]);
path_t_ext_middle = transform_post(path_t_ext_middle_, rotation([0,180,0]));
path_t_ext_bottom_ = path_offset(path_t_ext_solid_,[-height,offset,0]);
path_t_ext_bottom = transform_post(path_t_ext_bottom_, rotation([0,180,0]));

shape_top = rectangle_profile([height, width+2*e]);
shape_bottom = rectangle_profile([0.1, width]);
shape_thin = rectangle_profile([0.1, width]);

sweep(shape_top,path_t_ext_top);
hull()
{
    sweep(shape_thin,path_t_ext_middle);
    linear_extrude(height=e)
    {
        projection([0,0,1])
        {
            sweep(shape_bottom,path_t_ext_bottom);
        }
    }
}
```

**Comment by oysteinkrog** [comment] 2015-01-03 14:39
The above code produces this error with the very latest git (09e7bfc96dce9173b531d31a51fe1e00196f19c9):
```
PolySet has nonplanar faces. Attempting alternate construction
ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: pe_prev->is_border() || !internal::Plane_constructor::get_plane(pe_prev->facet(),pe_prev->facet()->plane()).is_degenerate() File: C:/msys64/mingw64/include/CGAL/Nef_3/polyhedron_3_to_nef_3.h Line: 251
```

However by modifying the above snippet with:
```
height = (top_point-low_point)+1;
````
This error is produced:
```

PolySet has nonplanar faces. Attempting alternate construction
ERROR: CGAL error in CGALUtils::applyBinaryOperator UNKNOWN: CGAL ERROR: assertion violation! Expr: itl != it->second.end() File: C:/msys64/mingw64/include/CGAL/Nef_3/SNC_external_structure.h Line: 1102
```

**Comment by kintel** [comment] 2015-01-16 06:54
Fixed by #1156

**Closed by kintel** 2015-01-16 06:54 UTC

**Comment by oysteinkrog** [comment] 2015-01-29 20:38
Latest snapshot (2015.01.23 (git 5a0c4b0)) still has CGAL ERROR, but a different one:

```
PolySet has nonplanar faces. Attempting alternate construction
ERROR: Alternate construction failed. CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /data/OpenSCAD/libraries-mingw64-master/mxe-w64/usr/x86_64-w64-mingw32.static/include/CGAL/Nef_S2/SM_const_decorator.h Line: 326```

Part of the design does not render (previews fine).

**Comment by kintel** [comment] 2015-01-29 20:40
Thanks for continued testing. Do you have a way of isolating the part that doesn't render, to make it easier to reproduce and test?

**Comment by oysteinkrog** [comment] 2015-01-29 20:54
I managed to cut it down a bit more now:
```
use <scad-utils/transformations.scad>
use <scad-utils/shapes.scad>
use <list-comprehension-demos/sweep.scad>

function transform_pre(vec_m, t) = [for(m=vec_m) t*m];
function transform_post(vec_m, t) = [for(m=vec_m) m*t];

path_lq = [[65, 0, 0], [64.9604, 0, -2.26847], [64.8417, 0, -4.53417], [64.6439, 0, -6.79435], [64.3674, 0, -9.04625], [64.0125, 0, -11.2871], [63.5796, 0, -13.5143], [63.0692, 0, -15.7249], [62.482, 0, -17.9164], [61.8187, 0, -20.0861], [61.08, 0, -22.2313], [60.267, 0, -24.3494], [59.3805, 0, -26.4379], [58.4216, 0, -28.4941], [57.3916, 0, -30.5157], [56.2917, 0, -32.5], [55.1231, 0, -34.4448], [53.8874, 0, -36.3475], [52.5861, 0, -38.206], [51.2207, 0, -40.018], [49.7929, 0, -41.7812], [48.3044, 0, -43.4935], [46.7571, 0, -45.1528], [45.1528, 0, -46.7571], [43.4935, 0, -48.3044], [41.7812, 0, -49.7929], [40.018, 0, -51.2207], [38.206, 0, -52.5861], [36.3475, 0, -53.8874], [34.4448, 0, -55.1231], [32.5, 0, -56.2917], [30.5157, 0, -57.3916], [28.4941, 0, -58.4216], [26.4379, 0, -59.3805], [24.3494, 0, -60.267], [22.2313, 0, -61.08], [20.0861, 0, -61.8187], [17.9164, 0, -62.482], [15.7249, 0, -63.0692], [13.5143, 0, -63.5796], [11.2871, 0, -64.0125], [9.04625, 0, -64.3674], [6.79435, 0, -64.6439]];

path_q_lq = construct_transform_path(path_lq,1,1);

cols_t_pre=
translation([0,45.7,0])
* rotation([-15,0,0])
* translation([0,0,65])
* rotation([0,6,0]);

path_t = transform_pre(path_q_lq, cols_t_pre);
shape_top = rectangle_profile([1,1]);

sweep(shape_top,path_t);

sweep(shape_top,path_t);
```

The curious thing is that the error only appears if I run that sweep twice, doing it once does not produce an error.
In my real design I do not have two identical sweeps, so just removing one of them is unfortunately not a real solution:p

**Comment by oysteinkrog** [comment] 2015-01-29 20:57
A version that gives yet another error:
```
PolySet has nonplanar faces. Attempting alternate construction
ERROR: CGAL error in CGALUtils::applyBinaryOperator union: CGAL ERROR: precondition violation! Expr: ! _is_valid (_succ2_P) || comp_f (node1_P->object, _succ2_P->object) != LARGER File: /data/OpenSCAD/libraries-mingw64-master/mxe-w64/usr/x86_64-w64-mingw32.static/include/CGAL/Multiset.h Line: 2304
```

```
use <scad-utils/transformations.scad>
use <scad-utils/shapes.scad>
use <list-comprehension-demos/sweep.scad>

function transform_pre(vec_m, t) = [for(m=vec_m) t*m];
function transform_post(vec_m, t) = [for(m=vec_m) m*t];

path_lq = [[65, 0, 0], [64.9604, 0, -2.26847]];

path_q_lq = construct_transform_path(path_lq,1,1);

cols_t_pre=
translation([0,45.7,0])
* rotation([-15,0,0])
* rotation([0,6,0]);

path_t = transform_pre(path_q_lq, cols_t_pre);
shape_top = rectangle_profile([1,1]);

sweep(shape_top,path_t);

sweep(shape_top,path_t);
```

**Comment by kintel** [comment] 2015-01-29 21:37
First of all, the reason why it triggers on multiple objects is that having just one object won't result in a CGAL operation, as the object is already evaluated.
To trigger a CGAL operation, add _any_ object, e.g. just a cube().
Alternatively, on the cmd-line, you can use ```--render=cgal``` to force conversion to CGAL

**Comment by kintel** [comment] 2015-01-29 21:39
Btw., this is getting out of hand - let's start a new issue for each unique problem, to better track it, and get back to this issue for your original design.

**Comment by kintel** [comment] 2015-01-29 22:49
@oysteinkrog OK, try again now. Was a trivial bug to fix.

**Comment by oysteinkrog** [comment] 2015-01-29 23:25
Confirmed, latest git now works on both this repro and my full design.
Thanks:)

**Comment by kintel** [comment] 2015-01-30 00:04
Yay - thanks for hanging in there!
