### ISSUE TITLE
Setting $variable with -D on the command line gives them too much scope.

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#2200] opened 2017-11-20 00:07 UTC
Setting a $variable on the command line should just append that variable to the end of the main file. Indeed the code seems to do exactly that. However with recent versions they have a different effect. Instead of just setting the variable at file scope it seems to override any setting at module scope. Module scope should always trump file scope with dynamic scoping.

Here is an example that goes wrong:

use.scad:
------------
```
$bom = 0;

use <used.scad>

test();

let($bom = 0)
   test();
   
$bom = 1;
```
used.scad:
--------------
```
use <used2.scad>

module test() {
    echo("test:", $bom = $bom);
    test2();
}
```
used2.scad:
----------------
```
module test2() {
    echo("test2:", $bom=$bom);
}
```
In the GUI this gives:
```
ECHO: "test:", $bom = 1
ECHO: "test2:", $bom = 1
ECHO: "test:", $bom = 0
ECHO: "test2:", $bom = 0
```
From the command line with ```-D$bom=1``` it gives:
```
ECHO: "test:", $bom = 1
ECHO: "test2:", $bom = 1
ECHO: "test:", $bom = 1
ECHO: "test2:", $bom = 1
```

**Comment by kintel** [comment] 2017-11-20 00:45
This behavior changed in 2012, interestingly enough due to a bug report from you :)
See #211

**Comment by nophead** [comment] 2017-11-20 10:22
So it appends the -D options to all used files. But that only sets it at file scope everywhere. When you set the same variable in a module it overrides it. When it is a $variable it has dynamic scope visible in the children of that module and the modules it calls. Surely that should override file scope definition in used modules as well?

**Comment by MichaelAtOz** [comment] 2017-11-20 23:10
I put $bom=2 at end of used.scad & $bom=3 at end of used2.scad.
(also added msg= parameter & an assign() to test whether let() was a problem)
```
ECHO: "test:  msg=", "top", ", $bom='", 2
ECHO: "test2: msg=", "from test()", ", $bom='", 3
ECHO: "test:  msg=", "let", ", $bom='", 2
ECHO: "test2: msg=", "from test()", ", $bom='", 3
DEPRECATED: The assign() module will be removed in future releases. Use a regular assignment instead. 
ECHO: "test:  msg=", "asn", ", $bom='", 2
ECHO: "test2: msg=", "from test()", ", $bom='", 3
```
For test(), $bom=2 as the file scope wins becasue there is no $bom in the paramters of the test() call.
Ditto for test2.

i.e. let($bom=1) has less scope level to test() $bom file level.

I think that is as expected.
The issue is that #211 solution is not optimal...

**Comment by nophead** [comment] 2017-11-21 00:17
It shouldn't matter that $bom is not passed has a parameter. It has dynamic scope, so should trump file scope all the way up the call stack, not just up the call stack in the local file but not extend into the used one.

Yes #211 is not optimal and not actually needed. I found more recently that the file scope of the using module is passed to the used module but doesn't override a definition there. So I use this in my global include and actually test $_bom.
```
$_bom          = $bom             == undef ? 0      : $bom;  
```

This means a single definition in the main file works fine to affect all the others in the GUI and would on the command line if #211 was reverted.

**Comment by kintel** [comment] 2017-11-22 05:23
That's indeed a bit odd. I wonder if there is some lookup bug which prefers a file-scoped variable to a dynamically scoped one. Needs some careful investigation..

**Comment by nophead** [comment] 2017-11-22 12:14
They are looked up here:https://github.com/openscad/openscad/blob/0904a3b3a5b56b16bb423b177972468eeca775a9/src/context.cc#L132.

I think when a used module is instantiated its config variables are part of its context. It is higher on the stack so gets searched first when they are looked up.

There seems to be no segregation in the context between file scope config variables and module scope ones. I think there needs to be so module scope ones can be searched before file scope.

**Comment by kintel** [comment] 2023-11-27 00:52
#3761 cleans up special variable passing, and makes the behavior more well-defined. Closing this issue as obsolete. Please open a new issue if there is still unclear behavior present.

**Closed by kintel** 2023-11-27 00:52 UTC
Labels: Comp: Command Line

**Comment by jordanbrown0** [comment] 2026-04-30 08:06
The best mental model that I have for this behavior is that the top level of a `use<>` file is a shim between the caller and the callee, another layer in both the call stack and the lexical stack.  A more recent change (which I don't know the numbers for offhand, but I'm sure you all remember) still executes that way, but then ignores the `use<>` file's top level when searching for `$` variables.
