### ISSUE TITLE
Center option unnecessarily limiting

### ISSUE THREAD

**Issue by ScottNudds** [openscad/openscad#4284] opened 2022-06-20 01:44 UTC
When centering a rectangle there are no facilities for centering on specific axis.  This typically produces an option of not centering and doing it manually with a translate, or centering and then correcting the axis that you don't want centered with a translate.

Either way a translate is required which entirely negates the utility of having the center option.

The solution would be to optionally treat the center parameter as a scalar = center on all axis, or as a 2 or 3 vector, center along the specified axis.

**Comment by MichaelAtOz** [comment] 2022-06-20 02:57
Duplicate of #265

**Closed** 2022-06-20 02:57 UTC
