### ISSUE TITLE
POV-Ray export for polyhedron is missing faces

### ISSUE THREAD

**Issue by UBaer21** [openscad/openscad#5499] opened 2024-12-17 00:34 UTC
```
tips=7;
loop=tips*2-1; // the length or number points of a star3D

function star3D(r=[10,5],tips=4,z=0) = [
let(chg=360/(tips*2))
  for(i=[0:tips*2-1])
    concat([cos(i*chg),sin(i*chg)]* (i%2?r[0]:r[1]) , z )
];

points=[
each star3D(r= [10,5],z=0,tips=tips),// base
each star3D(r= [10,5],z=5,tips=tips), // 2nd level
each star3D(r= [1,3],z=2,tips=tips) // 3rd level
];

faces= [
[for(i=[0:loop])i ], // base face
[for(i=[loop:-1:0])i + tips*4 ], // 3rd level face in reverse order

for(i=[0:loop])[(i+1)%(tips*2),i,i+ tips*2 ,(i +1)%(tips*2) + tips*2],// 1st level sides creates a quad group for each side
for(i=[0:loop])[(i+1)%(tips*2),i,i+ tips*2 ,(i +1)%(tips*2) + tips*2] +[1,1,1,1]*tips*2// 2nd level sides just add the number of tips*2

];

polyhedron(points,faces=faces);
```
export is
![Untitled scad pov BYPurg](https://github.com/user-attachments/assets/80dedf17-4395-467c-be5f-17d0a0288045)

should be like
![image](https://github.com/user-attachments/assets/95190577-c4d5-439c-aa12-7207a947fd99)

**Comment by kintel** [comment] 2024-12-17 02:31
This looks like a duplicate of #5459

**Comment by UBaer21** [comment] 2024-12-17 08:46
Oh yes you are right, using a union and adding a cube() also solved that here.

**Closed** 2024-12-17 14:22 UTC
Labels: Type: Bug
