### ISSUE TITLE
Unable to close undocked windows in 2020.11.30.ci6340

### ISSUE THREAD

**Issue by nyponen** [openscad/openscad#3512] opened 2020-12-05 19:12 UTC
When windows are undocked, and you close the preview window, the other windows are not closed, and cannot be closed normally. This occurs in the development snapshot 2020.11.30.ci6340 (git 9a08c222f)

**Comment by MichaelAtOz** [comment] 2020-12-05 22:58
I cannot reproduce this.
With 2020.11.30.ci6340/64, I undocked Editor & Console, leaving Preview with nothing else (I don't normally use Customizer or error log).
Clicking the close button in the Preview Titlebar, closed all three. Ditto File/Quit.
Rerunning, all three come up undocked as before.

Both Window-7/64 & Debian.

> cannot be closed normally

The close `X` button does nothing?

**Comment by nyponen** [comment] 2020-12-06 15:45
> I cannot reproduce this.
> With 2020.11.30.ci6340/64, I undocked Editor & Console, leaving Preview with nothing else (I don't normally use Customizer or error log).
> Clicking the close button in the Preview Titlebar, closed all three. Ditto File/Quit.
> Rerunning, all three come up undocked as before.
> 
> Both Window-7/64 & Debian.
> 
> > cannot be closed normally
> 
> The close `X` button does nothing?

When I click the 'X' button, Windows issues a popup with the message "openscad.exe is not responding" and gives a choice to "Close the program" or "Wait for the program to respond". When I click "Close the window" Windows reports the problem to Microsoft. This is on Windows 10.

**Comment by MichaelAtOz** [comment] 2020-12-06 22:30
Hmmm...loopy.scad....
Are you trying to close it while it is in still previewing?

**Comment by thehans** [comment] 2020-12-07 11:54
Sounds like duplicate of #1195 if that's the issue.

**Comment by nyponen** [comment] 2021-02-08 16:21
> Are you trying to close it while it is in still previewing?

No.

**Comment by nyponen** [comment] 2021-02-08 17:42
This still occurs in 2021.01 when OpenSCAD windows are undocked on separate monitors.

**Comment by kintel** [comment] 2024-12-22 18:18
@nyponen Following up: Does this still fail on a recent development snapshot?

**Comment by nyponen** [comment] 2024-12-23 16:05
I just tried this on 2024.12.22 (git 401f06ed4) and it seems to work correctly.

**Closed** 2024-12-23 16:25 UTC
Labels: Waiting for feedback, OS: Windows, Comp: GUI, Type: Bug
