### ISSUE TITLE
parallelize rendering with CGAL

### ISSUE THREAD

**Issue by krichter722** [openscad/openscad#1944] opened 2017-02-14 02:24 UTC
It'd be nice if the rendering process with CGAL would use more than one CPU/thread. This has been discussed in [this forum thread](http://forum.openscad.org/multithreading-OpenSCAD-td3504.html) without result.

experienced with openscad-2015.03-1-882-ge990ac49e

**Comment by kintel** [comment] 2017-02-14 03:09
Closing as duplicate of #391

**Closed by kintel** 2017-02-14 03:09 UTC
