### ISSUE TITLE
OpenScad doesn't show cached errors

### ISSUE THREAD

**Issue by zapta** [openscad/openscad#1924] opened 2017-01-30 23:39 UTC
To reproduce

1. Create an .scad file with the single line content

import("nosuchfile.stl");

2. Click Preview.  An error message for non existing file will be printed in the console (good).

3. Click Preview again. The error message is not displayed despite the script having an error.

Not displaying errors the second time because of caching is counter intuitive IMO. If an error  exists in the script, it should always be redisplayed.

**Comment by kintel** [comment] 2017-01-30 23:53
Duplicate of #454

**Closed by kintel** 2017-01-30 23:53 UTC
