### ISSUE TITLE
Export to formats other than STL by pressing F7

### ISSUE THREAD

**Issue by wzhd** [openscad/openscad#3220] opened 2020-02-15 05:18 UTC
Currently, the shortcut is only for exporting to STL.
It would be nice if the default export format could be changed.
And the format can't be changed in the export dialog, either. Because only STL is listed.

This has become more relevant after discovering that some models can't be sliced correctly in the Prusa slicer when exported as STL, but works totally fine when exported to 3mf. So I'm using at least two mouse clicks instead of two key presses to perform each export.

**Comment by t-paul** [comment] 2020-02-15 16:08
Closing as duplicate of #2977.

**Closed by t-paul** 2020-02-15 16:08 UTC
