### ISSUE TITLE
polygon() discards points

### ISSUE THREAD

**Issue by engblom** [openscad/openscad#1582] opened 2016-02-15 10:04 UTC
Somewhere around 60-80 points, polygon() begin to discard points and the higher it goes, the less points will be drawn. For example 1000 points becomes just 8 points.

Here is a ready example with 1000 points that becomes just 8 points:

P=[[0, 0], [0.002002, 0.003003], [0.004004, 0.00600597], [0.00600601, 0.0090089], [0.00800801, 0.0120118], [0.01001, 0.0150145], [0.012012, 0.0180172], [0.014014, 0.0210196], [0.016016, 0.024022], [0.018018, 0.0270241], [0.02002, 0.030026], [0.022022, 0.0330277], [0.024024, 0.0360291], [0.026026, 0.0390302], [0.028028, 0.042031], [0.03003, 0.0450315], [0.032032, 0.0480316], [0.034034, 0.0510313], [0.036036, 0.0540307], [0.038038, 0.0570295], [0.04004, 0.060028], [0.042042, 0.0630259], [0.044044, 0.0660233], [0.046046, 0.0690203], [0.048048, 0.0720166], [0.0500501, 0.0750124], [0.0520521, 0.0780076], [0.0540541, 0.0810021], [0.0560561, 0.083996], [0.0580581, 0.0869892], [0.0600601, 0.0899818], [0.0620621, 0.0929736], [0.0640641, 0.0959646], [0.0660661, 0.0989549], [0.0680681, 0.101944], [0.0700701, 0.104933], [0.0720721, 0.107921], [0.0740741, 0.110908], [0.0760761, 0.113894], [0.0780781, 0.116879], [0.0800801, 0.119863], [0.0820821, 0.122847], [0.0840841, 0.125829], [0.0860861, 0.12881], [0.0880881, 0.13179], [0.0900901, 0.13477], [0.0920921, 0.137748], [0.0940941, 0.140725], [0.0960961, 0.1437], [0.0980981, 0.146675], [0.1001, 0.149649], [0.102102, 0.152621], [0.104104, 0.155592], [0.106106, 0.158562], [0.108108, 0.16153], [0.11011, 0.164498], [0.112112, 0.167464], [0.114114, 0.170428], [0.116116, 0.173391], [0.118118, 0.176353], [0.12012, 0.179314], [0.122122, 0.182273], [0.124124, 0.18523], [0.126126, 0.188186], [0.128128, 0.19114], [0.13013, 0.194093], [0.132132, 0.197045], [0.134134, 0.199995], [0.136136, 0.202943], [0.138138, 0.205889], [0.14014, 0.208834], [0.142142, 0.211777], [0.144144, 0.214719], [0.146146, 0.217658], [0.148148, 0.220596], [0.15015, 0.223533], [0.152152, 0.226467], [0.154154, 0.2294], [0.156156, 0.23233], [0.158158, 0.235259], [0.16016, 0.238186], [0.162162, 0.241111], [0.164164, 0.244034], [0.166166, 0.246955], [0.168168, 0.249874], [0.17017, 0.252791], [0.172172, 0.255706], [0.174174, 0.258619], [0.176176, 0.26153], [0.178178, 0.264439], [0.18018, 0.267346], [0.182182, 0.27025], [0.184184, 0.273152], [0.186186, 0.276052], [0.188188, 0.27895], [0.19019, 0.281845], [0.192192, 0.284739], [0.194194, 0.28763], [0.196196, 0.290518], [0.198198, 0.293404], [0.2002, 0.296288], [0.202202, 0.29917], [0.204204, 0.302049], [0.206206, 0.304925], [0.208208, 0.307799], [0.21021, 0.310671], [0.212212, 0.31354], [0.214214, 0.316406], [0.216216, 0.31927], [0.218218, 0.322132], [0.22022, 0.32499], [0.222222, 0.327846], [0.224224, 0.3307], [0.226226, 0.33355], [0.228228, 0.336398], [0.23023, 0.339244], [0.232232, 0.342086], [0.234234, 0.344926], [0.236236, 0.347762], [0.238238, 0.350596], [0.24024, 0.353428], [0.242242, 0.356256], [0.244244, 0.359081], [0.246246, 0.361904], [0.248248, 0.364723], [0.25025, 0.367539], [0.252252, 0.370353], [0.254254, 0.373163], [0.256256, 0.375971], [0.258258, 0.378775], [0.26026, 0.381576], [0.262262, 0.384374], [0.264264, 0.387169], [0.266266, 0.389961], [0.268268, 0.392749], [0.27027, 0.395534], [0.272272, 0.398316], [0.274274, 0.401095], [0.276276, 0.403871], [0.278278, 0.406643], [0.28028, 0.409411], [0.282282, 0.412177], [0.284284, 0.414939], [0.286286, 0.417697], [0.288288, 0.420453], [0.29029, 0.423204], [0.292292, 0.425952], [0.294294, 0.428697], [0.296296, 0.431438], [0.298298, 0.434176], [0.3003, 0.43691], [0.302302, 0.43964], [0.304304, 0.442367], [0.306306, 0.44509], [0.308308, 0.447809], [0.31031, 0.450525], [0.312312, 0.453237], [0.314314, 0.455945], [0.316316, 0.45865], [0.318318, 0.46135], [0.32032, 0.464047], [0.322322, 0.46674], [0.324324, 0.469429], [0.326326, 0.472114], [0.328328, 0.474796], [0.33033, 0.477473], [0.332332, 0.480146], [0.334334, 0.482816], [0.336336, 0.485481], [0.338338, 0.488142], [0.34034, 0.490799], [0.342342, 0.493453], [0.344344, 0.496102], [0.346346, 0.498746], [0.348348, 0.501387], [0.35035, 0.504024], [0.352352, 0.506656], [0.354354, 0.509284], [0.356356, 0.511908], [0.358358, 0.514527], [0.36036, 0.517142], [0.362362, 0.519753], [0.364364, 0.52236], [0.366366, 0.524962], [0.368368, 0.52756], [0.37037, 0.530153], [0.372372, 0.532742], [0.374374, 0.535326], [0.376376, 0.537906], [0.378378, 0.540481], [0.38038, 0.543052], [0.382382, 0.545618], [0.384384, 0.54818], [0.386386, 0.550737], [0.388388, 0.553289], [0.39039, 0.555837], [0.392392, 0.55838], [0.394394, 0.560918], [0.396396, 0.563452], [0.398398, 0.56598], [0.4004, 0.568504], [0.402402, 0.571024], [0.404404, 0.573538], [0.406406, 0.576047], [0.408408, 0.578552], [0.41041, 0.581052], [0.412412, 0.583546], [0.414414, 0.586036], [0.416416, 0.588521], [0.418418, 0.591001], [0.42042, 0.593475], [0.422422, 0.595945], [0.424424, 0.59841], [0.426426, 0.600869], [0.428428, 0.603323], [0.43043, 0.605773], [0.432432, 0.608217], [0.434434, 0.610656], [0.436436, 0.613089], [0.438438, 0.615518], [0.44044, 0.617941], [0.442442, 0.620358], [0.444444, 0.622771], [0.446446, 0.625178], [0.448448, 0.62758], [0.45045, 0.629976], [0.452452, 0.632367], [0.454454, 0.634753], [0.456456, 0.637133], [0.458458, 0.639507], [0.46046, 0.641876], [0.462462, 0.64424], [0.464464, 0.646598], [0.466466, 0.64895], [0.468468, 0.651297], [0.47047, 0.653638], [0.472472, 0.655974], [0.474474, 0.658303], [0.476476, 0.660628], [0.478478, 0.662946], [0.48048, 0.665259], [0.482482, 0.667565], [0.484484, 0.669866], [0.486486, 0.672162], [0.488488, 0.674451], [0.49049, 0.676734], [0.492492, 0.679012], [0.494494, 0.681284], [0.496496, 0.683549], [0.498498, 0.685809], [0.500501, 0.688063], [0.502503, 0.690311], [0.504505, 0.692552], [0.506507, 0.694788], [0.508509, 0.697017], [0.510511, 0.699241], [0.512513, 0.701458], [0.514515, 0.703669], [0.516517, 0.705874], [0.518519, 0.708073], [0.520521, 0.710265], [0.522523, 0.712452], [0.524525, 0.714632], [0.526527, 0.716805], [0.528529, 0.718973], [0.530531, 0.721134], [0.532533, 0.723288], [0.534535, 0.725436], [0.536537, 0.727578], [0.538539, 0.729713], [0.540541, 0.731842], [0.542543, 0.733964], [0.544545, 0.73608], [0.546547, 0.73819], [0.548549, 0.740292], [0.550551, 0.742388], [0.552553, 0.744478], [0.554555, 0.746561], [0.556557, 0.748637], [0.558559, 0.750706], [0.560561, 0.752769], [0.562563, 0.754825], [0.564565, 0.756874], [0.566567, 0.758917], [0.568569, 0.760952], [0.570571, 0.762981], [0.572573, 0.765003], [0.574575, 0.767018], [0.576577, 0.769026], [0.578579, 0.771027], [0.580581, 0.773022], [0.582583, 0.775009], [0.584585, 0.776989], [0.586587, 0.778962], [0.588589, 0.780929], [0.590591, 0.782888], [0.592593, 0.78484], [0.594595, 0.786785], [0.596597, 0.788722], [0.598599, 0.790653], [0.600601, 0.792576], [0.602603, 0.794492], [0.604605, 0.796401], [0.606607, 0.798303], [0.608609, 0.800197], [0.610611, 0.802084], [0.612613, 0.803964], [0.614615, 0.805836], [0.616617, 0.807701], [0.618619, 0.809559], [0.620621, 0.811409], [0.622623, 0.813251], [0.624625, 0.815086], [0.626627, 0.816914], [0.628629, 0.818734], [0.630631, 0.820547], [0.632633, 0.822352], [0.634635, 0.824149], [0.636637, 0.825939], [0.638639, 0.827721], [0.640641, 0.829495], [0.642643, 0.831262], [0.644645, 0.833021], [0.646647, 0.834772], [0.648649, 0.836515], [0.650651, 0.838251], [0.652653, 0.839978], [0.654655, 0.841698], [0.656657, 0.84341], [0.658659, 0.845115], [0.660661, 0.846811], [0.662663, 0.848499], [0.664665, 0.85018], [0.666667, 0.851852], [0.668669, 0.853516], [0.670671, 0.855172], [0.672673, 0.856821], [0.674675, 0.858461], [0.676677, 0.860093], [0.678679, 0.861717], [0.680681, 0.863332], [0.682683, 0.86494], [0.684685, 0.866539], [0.686687, 0.86813], [0.688689, 0.869713], [0.690691, 0.871288], [0.692693, 0.872854], [0.694695, 0.874412], [0.696697, 0.875962], [0.698699, 0.877503], [0.700701, 0.879036], [0.702703, 0.88056], [0.704705, 0.882076], [0.706707, 0.883583], [0.708709, 0.885082], [0.710711, 0.886573], [0.712713, 0.888055], [0.714715, 0.889528], [0.716717, 0.890993], [0.718719, 0.892449], [0.720721, 0.893896], [0.722723, 0.895335], [0.724725, 0.896765], [0.726727, 0.898186], [0.728729, 0.899599], [0.730731, 0.901003], [0.732733, 0.902398], [0.734735, 0.903784], [0.736737, 0.905162], [0.738739, 0.90653], [0.740741, 0.90789], [0.742743, 0.909241], [0.744745, 0.910583], [0.746747, 0.911916], [0.748749, 0.91324], [0.750751, 0.914555], [0.752753, 0.91586], [0.754755, 0.917157], [0.756757, 0.918445], [0.758759, 0.919724], [0.760761, 0.920993], [0.762763, 0.922254], [0.764765, 0.923505], [0.766767, 0.924747], [0.768769, 0.92598], [0.770771, 0.927203], [0.772773, 0.928418], [0.774775, 0.929623], [0.776777, 0.930819], [0.778779, 0.932005], [0.780781, 0.933182], [0.782783, 0.93435], [0.784785, 0.935508], [0.786787, 0.936657], [0.788789, 0.937796], [0.790791, 0.938926], [0.792793, 0.940046], [0.794795, 0.941157], [0.796797, 0.942258], [0.798799, 0.94335], [0.800801, 0.944432], [0.802803, 0.945504], [0.804805, 0.946567], [0.806807, 0.94762], [0.808809, 0.948663], [0.810811, 0.949697], [0.812813, 0.950721], [0.814815, 0.951735], [0.816817, 0.952739], [0.818819, 0.953734], [0.820821, 0.954719], [0.822823, 0.955693], [0.824825, 0.956658], [0.826827, 0.957613], [0.828829, 0.958558], [0.830831, 0.959493], [0.832833, 0.960418], [0.834835, 0.961334], [0.836837, 0.962239], [0.838839, 0.963134], [0.840841, 0.964018], [0.842843, 0.964893], [0.844845, 0.965758], [0.846847, 0.966612], [0.848849, 0.967457], [0.850851, 0.968291], [0.852853, 0.969115], [0.854855, 0.969928], [0.856857, 0.970732], [0.858859, 0.971525], [0.860861, 0.972307], [0.862863, 0.97308], [0.864865, 0.973842], [0.866867, 0.974593], [0.868869, 0.975334], [0.870871, 0.976065], [0.872873, 0.976785], [0.874875, 0.977495], [0.876877, 0.978194], [0.878879, 0.978883], [0.880881, 0.979561], [0.882883, 0.980229], [0.884885, 0.980885], [0.886887, 0.981532], [0.888889, 0.982167], [0.890891, 0.982792], [0.892893, 0.983406], [0.894895, 0.98401], [0.896897, 0.984603], [0.898899, 0.985185], [0.900901, 0.985756], [0.902903, 0.986316], [0.904905, 0.986865], [0.906907, 0.987404], [0.908909, 0.987932], [0.910911, 0.988448], [0.912913, 0.988954], [0.914915, 0.989449], [0.916917, 0.989933], [0.918919, 0.990405], [0.920921, 0.990867], [0.922923, 0.991318], [0.924925, 0.991757], [0.926927, 0.992186], [0.928929, 0.992603], [0.930931, 0.993009], [0.932933, 0.993404], [0.934935, 0.993788], [0.936937, 0.99416], [0.938939, 0.994521], [0.940941, 0.994871], [0.942943, 0.99521], [0.944945, 0.995537], [0.946947, 0.995853], [0.948949, 0.996157], [0.950951, 0.99645], [0.952953, 0.996732], [0.954955, 0.997002], [0.956957, 0.997261], [0.958959, 0.997508], [0.960961, 0.997744], [0.962963, 0.997968], [0.964965, 0.99818], [0.966967, 0.998381], [0.968969, 0.998571], [0.970971, 0.998748], [0.972973, 0.998914], [0.974975, 0.999068], [0.976977, 0.999211], [0.978979, 0.999342], [0.980981, 0.999461], [0.982983, 0.999568], [0.984985, 0.999664], [0.986987, 0.999747], [0.988989, 0.999819], [0.990991, 0.999879], [0.992993, 0.999927], [0.994995, 0.999962], [0.996997, 0.999986], [0.998999, 0.999998], [1.001, 0.999998], [1.003, 0.999986], [1.00501, 0.999962], [1.00701, 0.999927], [1.00901, 0.999879], [1.01101, 0.999819], [1.01301, 0.999747], [1.01502, 0.999664], [1.01702, 0.999568], [1.01902, 0.999461], [1.02102, 0.999342], [1.02302, 0.999211], [1.02503, 0.999068], [1.02703, 0.998914], [1.02903, 0.998748], [1.03103, 0.998571], [1.03303, 0.998381], [1.03504, 0.99818], [1.03704, 0.997968], [1.03904, 0.997744], [1.04104, 0.997508], [1.04304, 0.997261], [1.04505, 0.997002], [1.04705, 0.996732], [1.04905, 0.99645], [1.05105, 0.996157], [1.05305, 0.995853], [1.05506, 0.995537], [1.05706, 0.99521], [1.05906, 0.994871], [1.06106, 0.994521], [1.06306, 0.99416], [1.06507, 0.993788], [1.06707, 0.993404], [1.06907, 0.993009], [1.07107, 0.992603], [1.07307, 0.992186], [1.07508, 0.991757], [1.07708, 0.991318], [1.07908, 0.990867], [1.08108, 0.990405], [1.08308, 0.989933], [1.08509, 0.989449], [1.08709, 0.988954], [1.08909, 0.988448], [1.09109, 0.987932], [1.09309, 0.987404], [1.0951, 0.986865], [1.0971, 0.986316], [1.0991, 0.985756], [1.1011, 0.985185], [1.1031, 0.984603], [1.10511, 0.98401], [1.10711, 0.983406], [1.10911, 0.982792], [1.11111, 0.982167], [1.11311, 0.981532], [1.11512, 0.980885], [1.11712, 0.980229], [1.11912, 0.979561], [1.12112, 0.978883], [1.12312, 0.978194], [1.12513, 0.977495], [1.12713, 0.976785], [1.12913, 0.976065], [1.13113, 0.975334], [1.13313, 0.974593], [1.13514, 0.973842], [1.13714, 0.97308], [1.13914, 0.972307], [1.14114, 0.971525], [1.14314, 0.970732], [1.14515, 0.969928], [1.14715, 0.969115], [1.14915, 0.968291], [1.15115, 0.967457], [1.15315, 0.966612], [1.15516, 0.965758], [1.15716, 0.964893], [1.15916, 0.964018], [1.16116, 0.963134], [1.16316, 0.962239], [1.16517, 0.961334], [1.16717, 0.960418], [1.16917, 0.959493], [1.17117, 0.958558], [1.17317, 0.957613], [1.17518, 0.956658], [1.17718, 0.955693], [1.17918, 0.954719], [1.18118, 0.953734], [1.18318, 0.952739], [1.18519, 0.951735], [1.18719, 0.950721], [1.18919, 0.949697], [1.19119, 0.948663], [1.19319, 0.94762], [1.1952, 0.946567], [1.1972, 0.945504], [1.1992, 0.944432], [1.2012, 0.94335], [1.2032, 0.942258], [1.20521, 0.941157], [1.20721, 0.940046], [1.20921, 0.938926], [1.21121, 0.937796], [1.21321, 0.936657], [1.21522, 0.935508], [1.21722, 0.93435], [1.21922, 0.933182], [1.22122, 0.932005], [1.22322, 0.930819], [1.22523, 0.929623], [1.22723, 0.928418], [1.22923, 0.927203], [1.23123, 0.92598], [1.23323, 0.924747], [1.23524, 0.923505], [1.23724, 0.922254], [1.23924, 0.920993], [1.24124, 0.919724], [1.24324, 0.918445], [1.24525, 0.917157], [1.24725, 0.91586], [1.24925, 0.914555], [1.25125, 0.91324], [1.25325, 0.911916], [1.25526, 0.910583], [1.25726, 0.909241], [1.25926, 0.90789], [1.26126, 0.90653], [1.26326, 0.905162], [1.26527, 0.903784], [1.26727, 0.902398], [1.26927, 0.901003], [1.27127, 0.899599], [1.27327, 0.898186], [1.27528, 0.896765], [1.27728, 0.895335], [1.27928, 0.893896], [1.28128, 0.892449], [1.28328, 0.890993], [1.28529, 0.889528], [1.28729, 0.888055], [1.28929, 0.886573], [1.29129, 0.885082], [1.29329, 0.883583], [1.2953, 0.882076], [1.2973, 0.88056], [1.2993, 0.879036], [1.3013, 0.877503], [1.3033, 0.875962], [1.30531, 0.874412], [1.30731, 0.872854], [1.30931, 0.871288], [1.31131, 0.869713], [1.31331, 0.86813], [1.31532, 0.866539], [1.31732, 0.86494], [1.31932, 0.863332], [1.32132, 0.861717], [1.32332, 0.860093], [1.32533, 0.858461], [1.32733, 0.856821], [1.32933, 0.855172], [1.33133, 0.853516], [1.33333, 0.851852], [1.33534, 0.85018], [1.33734, 0.848499], [1.33934, 0.846811], [1.34134, 0.845115], [1.34334, 0.84341], [1.34535, 0.841698], [1.34735, 0.839978], [1.34935, 0.838251], [1.35135, 0.836515], [1.35335, 0.834772], [1.35536, 0.833021], [1.35736, 0.831262], [1.35936, 0.829495], [1.36136, 0.827721], [1.36336, 0.825939], [1.36537, 0.824149], [1.36737, 0.822352], [1.36937, 0.820547], [1.37137, 0.818734], [1.37337, 0.816914], [1.37538, 0.815086], [1.37738, 0.813251], [1.37938, 0.811409], [1.38138, 0.809559], [1.38338, 0.807701], [1.38539, 0.805836], [1.38739, 0.803964], [1.38939, 0.802084], [1.39139, 0.800197], [1.39339, 0.798303], [1.3954, 0.796401], [1.3974, 0.794492], [1.3994, 0.792576], [1.4014, 0.790653], [1.4034, 0.788722], [1.40541, 0.786785], [1.40741, 0.78484], [1.40941, 0.782888], [1.41141, 0.780929], [1.41341, 0.778962], [1.41542, 0.776989], [1.41742, 0.775009], [1.41942, 0.773022], [1.42142, 0.771027], [1.42342, 0.769026], [1.42543, 0.767018], [1.42743, 0.765003], [1.42943, 0.762981], [1.43143, 0.760952], [1.43343, 0.758917], [1.43544, 0.756874], [1.43744, 0.754825], [1.43944, 0.752769], [1.44144, 0.750706], [1.44344, 0.748637], [1.44545, 0.746561], [1.44745, 0.744478], [1.44945, 0.742388], [1.45145, 0.740292], [1.45345, 0.73819], [1.45546, 0.73608], [1.45746, 0.733964], [1.45946, 0.731842], [1.46146, 0.729713], [1.46346, 0.727578], [1.46547, 0.725436], [1.46747, 0.723288], [1.46947, 0.721134], [1.47147, 0.718973], [1.47347, 0.716805], [1.47548, 0.714632], [1.47748, 0.712452], [1.47948, 0.710265], [1.48148, 0.708073], [1.48348, 0.705874], [1.48549, 0.703669], [1.48749, 0.701458], [1.48949, 0.699241], [1.49149, 0.697017], [1.49349, 0.694788], [1.4955, 0.692552], [1.4975, 0.690311], [1.4995, 0.688063], [1.5015, 0.685809], [1.5035, 0.683549], [1.50551, 0.681284], [1.50751, 0.679012], [1.50951, 0.676734], [1.51151, 0.674451], [1.51351, 0.672162], [1.51552, 0.669866], [1.51752, 0.667565], [1.51952, 0.665259], [1.52152, 0.662946], [1.52352, 0.660628], [1.52553, 0.658303], [1.52753, 0.655974], [1.52953, 0.653638], [1.53153, 0.651297], [1.53353, 0.64895], [1.53554, 0.646598], [1.53754, 0.64424], [1.53954, 0.641876], [1.54154, 0.639507], [1.54354, 0.637133], [1.54555, 0.634753], [1.54755, 0.632367], [1.54955, 0.629976], [1.55155, 0.62758], [1.55355, 0.625178], [1.55556, 0.622771], [1.55756, 0.620358], [1.55956, 0.617941], [1.56156, 0.615518], [1.56356, 0.613089], [1.56557, 0.610656], [1.56757, 0.608217], [1.56957, 0.605773], [1.57157, 0.603323], [1.57357, 0.600869], [1.57558, 0.59841], [1.57758, 0.595945], [1.57958, 0.593475], [1.58158, 0.591001], [1.58358, 0.588521], [1.58559, 0.586036], [1.58759, 0.583546], [1.58959, 0.581052], [1.59159, 0.578552], [1.59359, 0.576047], [1.5956, 0.573538], [1.5976, 0.571024], [1.5996, 0.568504], [1.6016, 0.56598], [1.6036, 0.563452], [1.60561, 0.560918], [1.60761, 0.55838], [1.60961, 0.555837], [1.61161, 0.553289], [1.61361, 0.550737], [1.61562, 0.54818], [1.61762, 0.545618], [1.61962, 0.543052], [1.62162, 0.540481], [1.62362, 0.537906], [1.62563, 0.535326], [1.62763, 0.532742], [1.62963, 0.530153], [1.63163, 0.52756], [1.63363, 0.524962], [1.63564, 0.52236], [1.63764, 0.519753], [1.63964, 0.517142], [1.64164, 0.514527], [1.64364, 0.511908], [1.64565, 0.509284], [1.64765, 0.506656], [1.64965, 0.504024], [1.65165, 0.501387], [1.65365, 0.498746], [1.65566, 0.496102], [1.65766, 0.493453], [1.65966, 0.490799], [1.66166, 0.488142], [1.66366, 0.485481], [1.66567, 0.482816], [1.66767, 0.480146], [1.66967, 0.477473], [1.67167, 0.474796], [1.67367, 0.472114], [1.67568, 0.469429], [1.67768, 0.46674], [1.67968, 0.464047], [1.68168, 0.46135], [1.68368, 0.45865], [1.68569, 0.455945], [1.68769, 0.453237], [1.68969, 0.450525], [1.69169, 0.447809], [1.69369, 0.44509], [1.6957, 0.442367], [1.6977, 0.43964], [1.6997, 0.43691], [1.7017, 0.434176], [1.7037, 0.431438], [1.70571, 0.428697], [1.70771, 0.425952], [1.70971, 0.423204], [1.71171, 0.420453], [1.71371, 0.417697], [1.71572, 0.414939], [1.71772, 0.412177], [1.71972, 0.409411], [1.72172, 0.406643], [1.72372, 0.403871], [1.72573, 0.401095], [1.72773, 0.398316], [1.72973, 0.395534], [1.73173, 0.392749], [1.73373, 0.389961], [1.73574, 0.387169], [1.73774, 0.384374], [1.73974, 0.381576], [1.74174, 0.378775], [1.74374, 0.375971], [1.74575, 0.373163], [1.74775, 0.370353], [1.74975, 0.367539], [1.75175, 0.364723], [1.75375, 0.361904], [1.75576, 0.359081], [1.75776, 0.356256], [1.75976, 0.353428], [1.76176, 0.350596], [1.76376, 0.347762], [1.76577, 0.344926], [1.76777, 0.342086], [1.76977, 0.339244], [1.77177, 0.336398], [1.77377, 0.33355], [1.77578, 0.3307], [1.77778, 0.327846], [1.77978, 0.32499], [1.78178, 0.322132], [1.78378, 0.31927], [1.78579, 0.316406], [1.78779, 0.31354], [1.78979, 0.310671], [1.79179, 0.307799], [1.79379, 0.304925], [1.7958, 0.302049], [1.7978, 0.29917], [1.7998, 0.296288], [1.8018, 0.293404], [1.8038, 0.290518], [1.80581, 0.28763], [1.80781, 0.284739], [1.80981, 0.281845], [1.81181, 0.27895], [1.81381, 0.276052], [1.81582, 0.273152], [1.81782, 0.27025], [1.81982, 0.267346], [1.82182, 0.264439], [1.82382, 0.26153], [1.82583, 0.258619], [1.82783, 0.255706], [1.82983, 0.252791], [1.83183, 0.249874], [1.83383, 0.246955], [1.83584, 0.244034], [1.83784, 0.241111], [1.83984, 0.238186], [1.84184, 0.235259], [1.84384, 0.23233], [1.84585, 0.2294], [1.84785, 0.226467], [1.84985, 0.223533], [1.85185, 0.220596], [1.85385, 0.217658], [1.85586, 0.214719], [1.85786, 0.211777], [1.85986, 0.208834], [1.86186, 0.205889], [1.86386, 0.202943], [1.86587, 0.199995], [1.86787, 0.197045], [1.86987, 0.194093], [1.87187, 0.19114], [1.87387, 0.188186], [1.87588, 0.18523], [1.87788, 0.182273], [1.87988, 0.179314], [1.88188, 0.176353], [1.88388, 0.173391], [1.88589, 0.170428], [1.88789, 0.167464], [1.88989, 0.164498], [1.89189, 0.16153], [1.89389, 0.158562], [1.8959, 0.155592], [1.8979, 0.152621], [1.8999, 0.149649], [1.9019, 0.146675], [1.9039, 0.1437], [1.90591, 0.140725], [1.90791, 0.137748], [1.90991, 0.13477], [1.91191, 0.13179], [1.91391, 0.12881], [1.91592, 0.125829], [1.91792, 0.122847], [1.91992, 0.119863], [1.92192, 0.116879], [1.92392, 0.113894], [1.92593, 0.110908], [1.92793, 0.107921], [1.92993, 0.104933], [1.93193, 0.101944], [1.93393, 0.0989549], [1.93594, 0.0959646], [1.93794, 0.0929736], [1.93994, 0.0899818], [1.94194, 0.0869892], [1.94394, 0.083996], [1.94595, 0.0810021], [1.94795, 0.0780076], [1.94995, 0.0750124], [1.95195, 0.0720166], [1.95395, 0.0690203], [1.95596, 0.0660233], [1.95796, 0.0630259], [1.95996, 0.060028], [1.96196, 0.0570295], [1.96396, 0.0540307], [1.96597, 0.0510313], [1.96797, 0.0480316], [1.96997, 0.0450315], [1.97197, 0.042031], [1.97397, 0.0390302], [1.97598, 0.0360291], [1.97798, 0.0330277], [1.97998, 0.030026], [1.98198, 0.0270241], [1.98398, 0.024022], [1.98599, 0.0210196], [1.98799, 0.0180172], [1.98999, 0.0150145], [1.99199, 0.0120118], [1.99399, 0.0090089], [1.996, 0.00600597], [1.998, 0.003003], [2, 0]];

polygon(P);

**Comment by t-paul** [comment] 2016-02-15 10:20
Closing as duplicate of #999. Workaound would be to scale the values up so it's not only fractions.

**Closed by t-paul** 2016-02-15 10:20 UTC

**Comment by nophead** [comment] 2016-02-15 10:46
This works

scale(0.001) polygon([for(p = P) p * 1000]);
