### ISSUE TITLE
Editor focus after Find

### ISSUE THREAD

**Issue by jon-bondy** [openscad/openscad#3666] opened 2021-02-13 14:03 UTC
With code visible on the editor form, press <ctrl>F to start a Find and type in a character string that is visible on the screen.  Then press <esc> to quit out of the Find.  Then type something.  Focus is nowhere to be found.  Focus should return to the editor after Find is terminated.  Forcing the user to find the mouse and click in the editor form is inefficient and unnecessary

I am using release 2021.01

**Comment by thehans** [comment] 2021-02-13 20:20
Duplicate of #3357

**Closed by thehans** 2021-02-13 20:20 UTC
