### ISSUE TITLE
ERROR: CGAL error in CGAL_Nef_polyhedron3()

### ISSUE THREAD

**Issue by boelle** [openscad/openscad#1904] opened 2017-01-03 12:59 UTC
I get this error when i try to compile

ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /usr/include/CGAL/Nef_S2/SM_const_decorator.h Line: 326 

script:

rotate([0,0,0])import("Untitled.stl", convexity=3);
rotate([0,0,0])translate([16,423,-232])cube([10,70,2]);

this one does not give an error:

rotate([0,0,0])import("Untitled.stl", convexity=3);
//rotate([0,0,0])translate([16,423,-232])cube([10,70,2]);

the stl has been run through netfabb

**Comment by t-paul** [comment] 2017-01-03 13:02
Netfabb does not fix zero faces by default anymore. Please check the [FAQ entry](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#Why_is_my_imported_STL_file_only_showing_up_with_F5_but_not_F6.3F) for more options.

**Comment by boelle** [comment] 2017-01-03 13:05
"which are currently not handled well in OpenSCAD."

so basicly i'm screwed at the moment unless i'm willing to fiddle with yet another software package?

**Comment by boelle** [comment] 2017-01-03 13:13
blender is out as it will only show things

meshlab seems the only bet until now

should i let this one stay open so stl import can be "fixed" to better handle this?

**Comment by t-paul** [comment] 2017-01-03 13:19
If it's indeed the known zero-faces issue, we have #1864.

**Comment by boelle** [comment] 2017-01-03 13:21
i'm trying the suggestion to use meshlab

is there a 100% sure way to know if its zero face?

i'm not sure if i can share the stl but will ask

**Comment by t-paul** [comment] 2017-01-03 13:28
Blender is usually nice for finding issues using the 3d-printing plugin (needs to be enabled).

**Comment by boelle** [comment] 2017-01-03 13:30
yeah, did the steps in meshlab and that did not help it

will try blender

**Comment by boelle** [comment] 2017-01-03 13:45
i can see the plugin but i cant enable it, the check box is greyed out

need to figure why and how to enable

**Comment by nophead** [comment] 2017-01-03 13:50
NetFabb will remove them. You just have to tell it to.

**Comment by boelle** [comment] 2017-01-03 13:52
also the free version?

**Comment by boelle** [comment] 2017-01-03 13:53
btw i just used https://service.netfabb.com/

**Comment by boelle** [comment] 2017-01-03 13:57
hmm... seems that there is no version for Debian8

am i right or blind?

**Comment by nophead** [comment] 2017-01-03 14:06
Yes the free version I have does it. It is Windows only now.

**Comment by boelle** [comment] 2017-01-03 14:09
bummer

but should meshlab not have done the trick also?

**Comment by nophead** [comment] 2017-01-03 14:19
I don't know, never used it.

The problem is OpenSCAD can only import a small subset of valid STL files,
not even all the ones it made by itself. It can't cope with vertices close
together because it snaps them to a grid and makes triangles degenerate
that didn't have zero area in the file. In Netfabb I can remove degenerate
triangles with a tolerance and I have to increase that from the default to
get a file OpenSCAD will accept.

**Comment by boelle** [comment] 2017-01-03 14:35
opened it in netfabb on my partners pc

everything is green, tried the auto repair and its still the same

are there any good sites like pastebin i could use to share it at

repaired was the same size as the org

**Comment by boelle** [comment] 2017-01-03 14:36
http://www.filedropper.com/1xboxdoornetfabbmm

its from 3d hubs hence the netfabb in the filename, has the customers approval  to share

**Comment by kintel** [comment] 2017-01-03 14:44
@boelle Carsten wrote a tool for detecting and repairing such issues. It's still proprietary, but he's been helpful with testing people's files. See here: http://forum.openscad.org/bug-with-difference-tp19439p19481.html

**Comment by boelle** [comment] 2017-01-03 14:57
will try

the problem with the STL i have is that the text is to deep and there are not enough material to close it off

i print it with the text down

will have a look at link

**Comment by boelle** [comment] 2017-01-03 15:04
tried to post, dont want to gatecrash him

**Comment by nophead** [comment] 2017-01-03 15:19
According to NetFabb it has self intersections in the first S. The free version doesn't fix those but the online version does. I just tried it and it seems that since the last time I used it a few months ago they changed it to produce a 3mf file, which is useless to me.

**Comment by boelle** [comment] 2017-01-03 15:22
that is strange... 

i started out with the online version and still have the issue

time to tripplecheck

**Comment by nophead** [comment] 2017-01-03 15:26
Did you get an STL back or a 3mf?

**Comment by boelle** [comment] 2017-01-03 15:28
stl

https://service.netfabb.com/

**Comment by boelle** [comment] 2017-01-03 15:32
https://tools3d.azurewebsites.net/

gives a 3mf, but that is Microsoft and not Netfabb

**Comment by boelle** [comment] 2017-01-03 15:34
seems that if i just print in 0.3 layers and not 0.2 the text is barely covered

**Comment by nophead** [comment] 2017-01-03 15:44
Yes there is only 0.55mm above the text.

**Comment by boelle** [comment] 2017-01-03 15:46
it will have to make do

its for a 3d scanner based on arduino micro

closing this one as it seems to be a dublicate

**Comment by kintel** [comment] 2017-01-20 06:02
Closing as duplicate - see #1864

**Closed by kintel** 2017-01-20 06:02 UTC
