### ISSUE TITLE
inconsistent render of transparent object in export png

### ISSUE THREAD

**Issue by UBaer21** [openscad/openscad#4002] opened 2021-12-09 11:30 UTC
using version 2021.12.07  `echo(version(),version_num());̀` ↦  [2021, 12], 2.02112e+7  ( should be vector3 according docu)

upd:  still happening with 2022.05.04  on Windows 10Pro

# code used:
```
cylinder(1,10);
color(alpha=.5)rotate([atan2(10,10*sqrt(2))])rotate([0,-45])cube(10);
```

# generates 
-   with copy viewport image (ctrl+shift+C)
 ![image](https://user-images.githubusercontent.com/93376232/145387284-74aa20c9-1f41-4c75-803b-d656e7f07c90.png)
- with export as image 
 ![IssueAlphapngOrder](https://user-images.githubusercontent.com/93376232/145387426-52a9953a-4f52-4ca8-9801-58c733d36599.png)
- and the viewports looks like 
![image](https://user-images.githubusercontent.com/93376232/145387838-33bf33e5-86a2-433e-9805-24370cb777d1.png)

**Comment by thehans** [comment] 2022-08-06 17:05
Duplicate of #3828

**Closed** 2022-08-06 17:44 UTC
