### ISSUE TITLE
assertion violation! Expr: e_below != SHalfedge_handle()  upon rendering

### ISSUE THREAD

**Issue by gvcastellano** [openscad/openscad#4672] opened 2023-06-19 16:08 UTC
Previewing the below design works ok, although the render appears to have an incomplete mesh.
After preview, attempting to render yields:

Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e_below != SHalfedge_handle() File: /usr/include/CGAL/Nef_3/SNC_FM_decorator.h Line: 418 
Geometries in cache: 7
Geometry cache size in bytes: 139928
CGAL Polyhedrons in cache: 2
CGAL cache size in bytes: 247888
Total rendering time: 0:00:00.144
Rendering finished.

Repeating the render does not reproduce the problem nor does it appear to actually render anything.  Restart openscad to reproduce the problem.

---BeginCode---
```
$fa=1;

mink_radius = 2;

  intersection () 
    { 
    minkowski ()
      {
      difference () {
        cylinder( d=44.5-2*mink_radius, h=35 );
          translate ([0, 20, 22])
            rotate ([0, 90, 0])
              cylinder ( h=50, r=17, center = true );
      }
      sphere ( r=mink_radius );
    }
    cylinder( d=49.5, h=41 );
  }
```
---EndCode---

**Environment and Version info (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - System: Dell XPS 64-bit Intel i7-6700HQ
 - OpenSCAD Version  2021.01via std Ubuntu repositories

**Library & Graphics card information**
OpenSCAD Version: 2021.01
System information: Linux 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 Ubuntu 22.04.2 LTS 8 CPUs 30.97 GB RAM
User Agent: OpenSCAD/2021.01 (Linux x86_64; Ubuntu 22.04.2 LTS)
Compiler: GCC "11.2.0" 64bit
MinGW build: No
Debug build: No
Boost version: 1_74
Eigen version: 3.4.0
CGAL version, kernels: 5.4, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.15.3
QScintilla version: 2.11.6
InputDrivers: 
GLib version: 2.71.3
lodepng version: 20180910
libzip version: 1.7.3
fontconfig version: 2.13.1
freetype version: 2.11.1
harfbuzz version: 2.7.4
cairo version: 1.16.0
lib3mf version: 1.8.1
Application Path: /usr/bin
Documents Path: /home/gvc/.local/share
User Documents Path: /home/gvc/Documents
Resource Path: /usr/share/openscad
User Library Path: /home/gvc/.local/share/OpenSCAD/libraries
User Config Path: /home/gvc/.config/OpenSCAD
Backup Path: /home/gvc/.local/share/OpenSCAD/backups
OPENSCADPATH: /home/gvc/git/wgvc/3d/lib
OpenSCAD library path:
/home/gvc/git/wgvc/3d/lib
/home/gvc/.local/share/OpenSCAD/libraries
/usr/share/openscad/libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
/usr/share/fonts
/usr/local/share/fonts
/home/gvc/.local/share/fonts
/home/gvc/.fonts
/usr/share/fonts/X11
/usr/share/fonts/cMap
/usr/share/fonts/cmap
/usr/share/fonts/opentype
/usr/share/fonts/truetype
/usr/share/fonts/type1
/usr/share/fonts/woff
/usr/share/fonts/X11/Type1
/usr/share/fonts/X11/encodings
/usr/share/fonts/X11/misc
/usr/share/fonts/X11/util
/usr/share/fonts/cmap/adobe-cns1
/usr/share/fonts/cmap/adobe-gb1
/usr/share/fonts/cmap/adobe-japan1
/usr/share/fonts/cmap/adobe-japan2
/usr/share/fonts/cmap/adobe-korea1
/usr/share/fonts/opentype/cabin
/usr/share/fonts/opentype/cantarell
/usr/share/fonts/opentype/malayalam
/usr/share/fonts/opentype/mathjax
/usr/share/fonts/opentype/noto
/usr/share/fonts/opentype/opendyslexic
/usr/share/fonts/opentype/urw-base35
/usr/share/fonts/truetype/Gargi
/usr/share/fonts/truetype/Gubbi
/usr/share/fonts/truetype/Nakula
/usr/share/fonts/truetype/Navilu
/usr/share/fonts/truetype/Sahadeva
/usr/share/fonts/truetype/Sarai
/usr/share/fonts/truetype/abyssinica
/usr/share/fonts/truetype/ancient-scripts
/usr/share/fonts/truetype/dejavu
/usr/share/fonts/truetype/droid
/usr/share/fonts/truetype/fonts-beng-extra
/usr/share/fonts/truetype/fonts-deva-extra
/usr/share/fonts/truetype/fonts-gujr-extra
/usr/share/fonts/truetype/fonts-guru-extra
/usr/share/fonts/truetype/fonts-kalapi
/usr/share/fonts/truetype/fonts-orya-extra
/usr/share/fonts/truetype/fonts-telu-extra
/usr/share/fonts/truetype/fonts-tiresias
/usr/share/fonts/truetype/fonts-yrsa-rasa
/usr/share/fonts/truetype/freefont
/usr/share/fonts/truetype/gentium
/usr/share/fonts/truetype/gentium-basic
/usr/share/fonts/truetype/kacst
/usr/share/fonts/truetype/kacst-one
/usr/share/fonts/truetype/lao
/usr/share/fonts/truetype/liberation
/usr/share/fonts/truetype/liberation2
/usr/share/fonts/truetype/libreoffice
/usr/share/fonts/truetype/lohit-assamese
/usr/share/fonts/truetype/lohit-bengali
/usr/share/fonts/truetype/lohit-devanagari
/usr/share/fonts/truetype/lohit-gujarati
/usr/share/fonts/truetype/lohit-kannada
/usr/share/fonts/truetype/lohit-malayalam
/usr/share/fonts/truetype/lohit-oriya
/usr/share/fonts/truetype/lohit-punjabi
/usr/share/fonts/truetype/lohit-tamil
/usr/share/fonts/truetype/lohit-tamil-classical
/usr/share/fonts/truetype/lohit-telugu
/usr/share/fonts/truetype/malayalam
/usr/share/fonts/truetype/noto
/usr/share/fonts/truetype/open-sans
/usr/share/fonts/truetype/openoffice
/usr/share/fonts/truetype/padauk
/usr/share/fonts/truetype/pagul
/usr/share/fonts/truetype/samyak
/usr/share/fonts/truetype/samyak-fonts
/usr/share/fonts/truetype/sinhala
/usr/share/fonts/truetype/teluguvijayam
/usr/share/fonts/truetype/tibetan-machine
/usr/share/fonts/truetype/tiresias
/usr/share/fonts/truetype/tlwg
/usr/share/fonts/truetype/ttf-khmeros-core
/usr/share/fonts/truetype/ubuntu
/usr/share/fonts/type1/gsfonts
/usr/share/fonts/type1/urw-base35
/usr/share/fonts/woff/opendyslexic
/usr/share/fonts/X11/encodings/large
GLEW version: 2.2.0
OpenGL Version: 4.6 (Compatibility Profile) Mesa 22.2.5
GL Renderer: Mesa Intel(R) HD Graphics 530 (SKL GT2)
GL Vendor: Intel
RGBA(8880), depth(0), stencil(0)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(8880), depth(0), stencil(0)

GL Extensions:
GL_3DFX_texture_compression_FXT1
GL_AMD_conservative_depth
GL_AMD_depth_clamp_separate
GL_AMD_draw_buffers_blend
GL_AMD_multi_draw_indirect
GL_AMD_performance_monitor
GL_AMD_pinned_memory
GL_AMD_query_buffer_object
GL_AMD_seamless_cubemap_per_texture
GL_AMD_shader_stencil_export
GL_AMD_shader_trinary_minmax
GL_AMD_texture_texture4
GL_AMD_vertex_shader_layer
GL_AMD_vertex_shader_viewport_index
GL_ANGLE_texture_compression_dxt3
GL_ANGLE_texture_compression_dxt5
GL_APPLE_packed_pixels
GL_ARB_ES2_compatibility
GL_ARB_ES3_1_compatibility
GL_ARB_ES3_2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_compute_variable_group_size
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_direct_state_access
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_fragment_shader_interlock
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gl_spirv
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_gpu_shader_int64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_parallel_shader_compile
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_polygon_offset_clamp
GL_ARB_post_depth_coverage
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_ballot
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_stencil_export
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shader_viewport_layer_array
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_spirv_extensions
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_filter_anisotropic
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_blend_equation_separate
GL_ATI_draw_buffers
GL_ATI_fragment_shader
GL_ATI_separate_stencil
GL_ATI_texture_env_combine3
GL_ATI_texture_float
GL_EXT_EGL_image_storage
GL_EXT_EGL_sync
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_copy_texture
GL_EXT_demote_to_helper_invocation
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_memory_object
GL_EXT_memory_object_fd
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset_clamp
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_semaphore
GL_EXT_semaphore_fd
GL_EXT_separate_specular_color
GL_EXT_shader_framebuffer_fetch
GL_EXT_shader_framebuffer_fetch_non_coherent
GL_EXT_shader_integer_mix
GL_EXT_shader_samples_identical
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_subtexture
GL_EXT_texture
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_object
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_R8
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shadow_lod
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_EXT_vertex_attrib_64bit
GL_IBM_multimode_draw_arrays
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_INGR_blend_func_separate
GL_INTEL_blackhole_render
GL_INTEL_performance_query
GL_INTEL_shader_atomic_float_minmax
GL_INTEL_shader_integer_functions2
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_parallel_shader_compile
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_KHR_texture_compression_astc_ldr
GL_KHR_texture_compression_astc_sliced_3d
GL_MESA_framebuffer_flip_y
GL_MESA_pack_invert
GL_MESA_shader_integer_functions
GL_MESA_texture_signed_rgba
GL_MESA_window_pos
GL_NV_blend_square
GL_NV_compute_shader_derivatives
GL_NV_conditional_render
GL_NV_copy_depth_to_color
GL_NV_copy_image
GL_NV_depth_clamp
GL_NV_fog_distance
GL_NV_fragment_shader_interlock
GL_NV_half_float
GL_NV_light_max_exponent
GL_NV_packed_depth_stencil
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_env_combine4
GL_NV_texture_rectangle
GL_OES_EGL_image
GL_OES_read_format
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_border_clamp
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays

**Comment by jordanbrown0** [comment] 2023-06-19 22:12
[ I don't have an answer, but I do have a few pieces of the puzzle. ]

First, not related to your complaint... use minkowski(convexity=2) or more to get rid of preview artifacts.

Second, only tangentially related... the reason that you don't see the error on a subsequent render is that OpenSCAD caches render results, including failures.  The subsequent render re-uses the failed result, without recalculating it and encountering the error again.  (There is a good argument that this is a bug.)

This problem is unusual in that it appears only when you preview (F5) and then render (F6).  (Most errors of this general sort require only F6.)  Reproduce with Design/Flush Caches, F5, F6.

Here is a somewhat simpler and faster demonstration.

```
$fn = 30;

minkowski()
{
    difference () {
        cylinder ( d=40.5, h=35 );
        translate ([0, 20, 22])
            rotate ([0, 90, 0])
            cylinder ( h=50, r=17, center = true );
    }
    cube(2,center=true);
}

translate([100,0,0]) cube();
```

Likely cause:  something about exactly how the two cylinders fit together causes minkowski to produce bad geometry, that then causes CGAL to die while attempting to import it.  Note that the cube at the end is nowhere near the model; it's only there to cause a CGAL operation.

Workaround: there's a good chance that tweaking the parameters of the model slightly will avoid the problem.

**Comment by gvcastellano** [comment] 2023-06-19 22:21
Thanks for the tips, I meant to add that when mink_radius = 0.9 in the original example there's no trouble with rendering so you presume correctly.

**Comment by Duxah** [comment] 2023-11-01 14:20
Good afternoon. 

![2023-11-01 19 17 04](https://github.com/openscad/openscad/assets/51926215/37ec9654-3b72-4387-81c2-d41e0b12038f)

I'm having the same problem. I mean that when compiling OpenSCAD it produces the same error text. I'll tell you the story from the very beginning - I created a complex object in OpenSCAD, then generated an STL and when generating OpenSCAD did not issue a single warning, everything worked out perfectly. Then I import this STL, add a simple Cube, click the STL button and the program gives this error described above. What to do? It turns out that either the import does not work, or the export does not work. One of two things is not working. I am attaching a screenshot. I can send files if necessary..

Best regards, Eugenii

**Comment by jordanbrown0** [comment] 2023-11-01 17:45
This is probably all known behavior.

OpenSCAD (CGAL, actually) is very picky about what inputs it will accept - and, in particular, some OpenSCAD outputs are not acceptable.  (Yes, that's unfortunate.)

On import, you don't see a problem until you add that cube because CGAL doesn't get involved (and reject the polyhedron) until there's something for it to do.

There are those - who will, I hope, chime in - who know how to examine the STL to figure out exactly what's wrong with it.  There's usually some microscopic defect.

**Comment by Duxah** [comment] 2023-11-01 19:21
(Google translate)
Here is a guess and a suggestion:

1) check the conversion of a string to a double and vice versa, as well as the absence of any alignments to grids, since CGAL is so demanding, as an option - increase the number of decimal places in floating-point numbers when writing STL.

2) it is possible, in theory, as an additional checks after STL compilation, do an automatic test for the closedness of the resulting object, and if everything is ok, then the problem may really be in losses when writing/reading from the file. You can try to compile the STL and immediately add the cube and check the compilation again, as if we had just imported this STL. Thus, we will exclude or confirm the version of losses during writing/reading. But of course, this can only be done by the developer in debug mode, not by the user.

Best regards

**Comment by jordanbrown0** [comment] 2023-11-01 23:34
I haven't looked into the problems in detail; I just know that they are known.  There *is* a grid at about 10^-6 units, and my understanding is that indeed it plays a role in this kind of thing.  I am told that getting rid of the grid introduces other problems, where vertices that are supposed to match up don't.

Binary STL is unfortunately defined using single precision.  ASCII STL could in theory use more, though whether it was useful would depend on whether the consumers used the additional precision.

**Comment by Duxah** [comment] 2023-11-03 19:05
(Google translate)

There are at least 3 algorithms for snapping to the grid - rounding to the bottom, to the top, and from the middle. What method is used when reading STL? To improve, I would like to be able to change the grid snap type in the OpenSCAD settings, because I think this could help solve this problem when it occurs. Nowadays OpenSCAD either works or it doesn't, and then the gnashing of teeth occurs. And with the adjustment it will be like this: if it doesn’t work, then we go into the settings, tweak the parameter and there is a high probability that it will start working. It is very useful to have some settings to solve such problems. Most often, an error occurs during compilation with the text “given mesh is not closed”, and nothing can be done about it - neither MeshLab nor MeshMixer helps, you just waste time on some kind of shamanism with STL. I downloaded many different STL models from the Internet, and even generated STL from STEP format, and all of them did not compile in OpenSCAD. Please add some settings.

OpenSCAD is a fantastic program for solid modeling, and if you finally solve this issue it will be just a fairy tale, but with such errors you start looking for an alternative program

There is one more proposal, I don’t know where to write it, I’ll write it here, in general the gist is this: when we import an STL file, the object always appears God knows where, because every designer designs his model in the coordinates where he wants. I would like to have a function that will set the body to specified coordinates (for example 0,0,0) along the lower left rear edge (as an option). Or it would be nice to have a function GetMinX GetMinY GetMinZ GetMaxX GetMaxY GetMaxZ, then using translate() to move the body where we need it

best wishes

**Comment by jordanbrown0** [comment] 2023-11-03 23:44
With the note again that I have not looked into the problem in detail... it is not that STL coordinates are snapped (though they might be), it is that coordinates are snapped during the creation of the original model and the resulting STL can be defective.

Unfortunately, the current situation is that because of microscopic defects, importing an STL fails very frequently.  It might be possible to have OpenSCAD repair the defects, but so far nobody with the requisite expertise has stepped up to add that feature.

With respect to your last point... I believe it would be relatively easy to have the STL importer accept some kind of alignment option.  It already has a `center` option, that STL import ignores.  It would *not* be easy to export information about the imported STL to the running program, because we don't actually look at the STL until after the program runs.  (We could have a separate function that reads the STL and returns metadata, and #4478's `render()` function can yield information about a geometric object.)  A request for an alignment option would be best made in a separate Github issue, tagged "enhancement request".  But note:  if you intend to modify an object from an STL you have to know a lot about it already; I'd think that knowing its origin would be the least of your problems.

**Comment by kintel** [comment] 2024-04-01 02:54
Status as of 2024-03-24: This seems to be fixed now, both when using the CGAL and Manifold backend.

**Closed by kintel** 2024-04-01 02:54 UTC
Labels: Dep: CGAL, Type: Bug
