### ISSUE TITLE
FR: option to `center` in specified axes

### ISSUE THREAD

**Issue by adcurtin** [openscad/openscad#3187] opened 2020-01-12 22:56 UTC
I'd love to be able to pass something like `center = [1, 1, 0]` to all the functions that can take `center = true` or `center = false` to be able to specify which axes I would like centered, and which ones I would not. (and typically for me, I don't want z centered)

**Comment by kintel** [comment] 2020-01-12 23:10
Duplicate of #265

**Closed by kintel** 2020-01-12 23:10 UTC
