### ISSUE TITLE
New Feature: Add STL export button in toolbar in Preview window

### ISSUE THREAD

**Issue by ThePiGuy** [openscad/openscad#2117] opened 2017-09-30 23:27 UTC
I've stopped using the built-in text editor in favor of Sublime Text, but if I hide the editor, then the buttons to refresh preview/render and export as STL disappear because they are part of the editor view.  There are buttons to preview and render in the preview display area, but no shortcut to export as STL.

Edit: At first I didn't realize that there were the preview/render buttons in the toolbar in the Preview display area/window, so the initial request was to add that feature.  This issue now focuses strictly on adding an STL export button to the preview window.

**Comment by MichaelAtOz** [comment] 2017-10-01 01:01
Duplicate of #1900, closing.
@ThePiGuy re not using the edit windows, see #2052, add any thoughts on menu/docking there.

**Closed** 2017-10-06 00:19 UTC
