### ISSUE TITLE
Diffing a cube trough camera breaks F5

### ISSUE THREAD

**Issue by hroncok** [openscad/openscad#992] opened 2014-10-21 17:31 UTC
See this code:

```
difference() {
  cylinder(r=15,h=20);
  translate([-50,-100,0]) cube(100);
}
```

Be sure to have the default viewport to observe this. Run F5 and zoom in and out.

(F6 is fine. Running on b66fb59.)

Distance ~90:
![Disatnce 90](https://cloud.githubusercontent.com/assets/2401856/4723477/f8f7353a-5947-11e4-8732-aca671114d00.png)

Distance ~170:
![Disatnce 170](https://cloud.githubusercontent.com/assets/2401856/4723476/f8f6724e-5947-11e4-8a53-80aeff12046d.png)

**Comment by kintel** [comment] 2015-01-22 23:04
Closing as duplicate of #496

**Closed by kintel** 2015-01-22 23:04 UTC
