### ISSUE TITLE
Customizer - unable to input decimal separator

### ISSUE THREAD

**Issue by jeanblanchard** [openscad/openscad#3438] opened 2020-09-21 18:17 UTC
# Summary

In OpenSCAD 2019.5, with an OS locale with a comma as a decimal separator (here French), there is no way to input a number with a decimal part in the customizer parameter input field, if the default value does not have one. The ',' and '.' keys have no effect on the field.

# Steps to reproduce
* Set Locale to French
* In OpenSCAD open for example the scad file from here: https://www.thingiverse.com/thing:1170291/files
* In the "width" parameter, try to input a decimal separator.

## Expected
The ',' key (and optionally the '.' key) result in the ',' character in the field

## Actual
',' and '.' have no effect

# Environment
* OpenSCAD 2019.5
* Linux (Solus Plasma)
* Locale French

**Comment by t-paul** [comment] 2020-09-21 18:24
This is unrelated to locale. The problem is that the customizer has currently no way to know the number of digits given in the script. Closing as duplicate of #3315.

**Closed by t-paul** 2020-09-21 18:24 UTC
Labels: Comp: Customizer, Type: Enhancement
