### ISSUE TITLE
Crash upon file open or file save

### ISSUE THREAD

**Issue by M4rc3lv** [openscad/openscad#3678] opened 2021-02-19 11:08 UTC
On Linux Openscad 2021.01 crashes when you acces File Open or File Save from the File menu. Opening Recent Files (and saving them with Ctrl+S) works fine. It seems that it can not show the File dialog.

Applies to version: 2021.01-x86_64 on Linux Mint.
Version 2019.05  does work fine on the same machine.

**Command line**
./OpenSCAD-2021.01-x86_64.AppImage 
 
(AppRun.wrapped:219261): Gtk-WARNING **: 12:04:08.738: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Mint-Y/actions/16/image-missing.svg: Laden van afbeeldingslader /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so mislukt: /usr/lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Mint-Y/actions/16/image-missing.svg: Laden van afbeeldingslader /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so mislukt: /usr/lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end (gdk-pixbuf-error-quark, 5)
Afgebroken (geheugendump gemaakt)

**Comment by t-paul** [comment] 2021-02-19 11:14
Duplicate of #3523

**Closed by t-paul** 2021-02-19 11:14 UTC
