### ISSUE TITLE
Implement Enumerations

### ISSUE THREAD

**Issue by FluxIX** [openscad/openscad#1375] opened 2015-06-28 05:01 UTC
Implement an enumeration container which can hold acceptable enumerated values for an enumerated type. It would make specifying behaviors to functions and modules significantly easier in reusable components.

**Comment by MichaelAtOz** [comment] 2015-06-28 05:50
Duplicate of issue #1032.

**Comment by t-paul** [comment] 2015-06-28 13:10
Closed as duplicate. @FluxIX to get updates on #1032, you can subscribe there.

**Closed by t-paul** 2015-06-28 13:10 UTC
