### ISSUE TITLE
Previewing doesn't work after different issues

### ISSUE THREAD

**Issue by kwendenarmo** [openscad/openscad#2378] opened 2018-04-15 17:03 UTC
I'm developing a project where I need a lot of 3D design, and I found that my version of OpenSCAD stopped previewing with some frequency.
OpenSCAD was previously running, although I can't determine what has changed since then, or if it's the same version. So I decided to compile the master branch again and install it, in case it fixed the problem. It didn't fix it, but it has allowed me to detect the causes that cause it to enter this error state.
I have recently found that the same thing happens to me on my work computer.

When it enters this mode, the only way out is to close the program. The preview doesn't usually work again, but it can still be rendered. It is very similar to what was discussed in Issue #1727. Once it stops previewing, most of the time it doesn't do it again and in fact, the small color coordinate axis of the corner is also no longer displayed.
The times it does preview again, it skips in the preview the items that are part of differences or intersections. And if it previews again, it is because there are no differences or intersections in the part that was previewing.
Whenever you try to preview again, you see how the console information is regenerated, but nothing is shown in the design area, apart from the scale.

It has taken me hours of frustration to design several iterations of the model with these circumstances.

The reasons I have found this to be the case are as follows:
-  After a syntax failure, which happens to me frequently because my laptop keyboard is quite deteriorated.
-  After rendering. After that, it never previews again.
-  I just discovered it right now: After a preview failure, if another OpenSCAD instance is opened (File -> New), and a syntax failure occurs that causes a preview failure in this new instance, and you go back to the first instance, then the preview works again in both instances. Weird. And if syntax errors are made in this first instance, it ignores them and continues to preview them. Even weirder.

Example codes with which this happens:
```
// This previews correctly.
difference() {
    cube([10,10,10]);
    translate([7,7,7]) cube([5,5,5]);
}
```
Remove the last semicolon to produce a syntax error. When you put it back on, stop previewing.

```
$fn=36;
difference() {
    sphere(10);
    cylinder(r=4, h=22, center=true);
    rotate([90,0,0]) cylinder(r=4, h=22, center=true);
    rotate([0,90,0]) cylinder(r=4, h=22, center=true);
}
```
Render the model, once it has been rendered, it does not preview again. (I don't know if the complexity of the piece has anything to do with it, because with the previous example of the cubes it still previews.)

About my system:
```
OpenSCAD Version: 2018.03.25
System information: Linux 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 Linux Mint 18.1 8 CPUs 15.58 GB RAM
Compiler: GCC "5.4.0 20160609" 64bit
Boost version: 1_58
Eigen version: 3.2.92
CGAL version, kernels: 4.7, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.4.0
Qt version: 5.5.1
QScintilla version: 2.9.1
MingW build: No
GLib version: 2.48.2
libzip version: 1.0.1
Application Path: /usr/local/bin
Documents Path: /home/kwendenarmo/.local/share
Resource Path: /usr/local/share/openscad
User Library Path: /home/kwendenarmo/.local/share/OpenSCAD/libraries
User Config Path: /home/kwendenarmo/.config/OpenSCAD
Backup Path: /home/kwendenarmo/.local/share/OpenSCAD/backups
OPENSCADPATH: 
OpenSCAD library path:
/home/kwendenarmo/.local/share/OpenSCAD/libraries
/usr/local/share/openscad/libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 1.13.0
OpenGL Version: 3.0 Mesa 17.2.8
GL Renderer: Mesa DRI Intel(R) Haswell Mobile 
GL Vendor: Intel Open Source Technology Center
RGBA(8880), depth(0), stencil(0)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(8880), depth(0), stencil(0)

GL Extensions:
GL_3DFX_texture_compression_FXT1
GL_AMD_conservative_depth
GL_AMD_draw_buffers_blend
GL_AMD_seamless_cubemap_per_texture
GL_AMD_shader_trinary_minmax
GL_ANGLE_texture_compression_dxt3
GL_ANGLE_texture_compression_dxt5
GL_APPLE_object_purgeable
GL_APPLE_packed_pixels
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_instanced
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_window_pos
GL_ATI_blend_equation_separate
GL_ATI_draw_buffers
GL_ATI_separate_stencil
GL_ATI_texture_env_combine3
GL_ATI_texture_float
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_copy_texture
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_gpu_program_parameters
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset
GL_EXT_polygon_offset_clamp
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_specular_color
GL_EXT_shader_integer_mix
GL_EXT_shader_samples_identical
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_subtexture
GL_EXT_texture
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_object
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_IBM_multimode_draw_arrays
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_INGR_blend_func_separate
GL_INTEL_performance_query
GL_KHR_blend_equation_advanced
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_MESA_pack_invert
GL_MESA_shader_integer_functions
GL_MESA_texture_signed_rgba
GL_MESA_window_pos
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_depth_clamp
GL_NV_light_max_exponent
GL_NV_packed_depth_stencil
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_env_combine4
GL_NV_texture_rectangle
GL_OES_EGL_image
GL_OES_read_format
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_border_clamp
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays
```

**Comment by t-paul** [comment] 2018-04-15 17:37
Sounds like a duplicate of  #1875 - see also http://forum.openscad.org/Object-appears-in-F6-render-but-not-F5-preview-td23809.html

**Comment by kwendenarmo** [comment] 2018-04-15 18:34
Thank you, looking at the other issue you mentioned, I noticed that even though it is a git-master version and recently compiled, it still uses an older version of OpenCSG.
I assumed that this dependency was included in the repository and updated, or that my system would have updated it from its package repositories. so I'd overlooked this.

To update OpenCSG you need to download the latest sources from http://opencsg.org/#download, and compile and install OpenCSG (`make && sudo make install`). It may not compile because it is missing `gl/glut.h`. This is fixed by installing the package `freeglut3-dev`.
Having done this, I downloaded OpenSCAD from git-master and compiled it again.
Once compiled and installed again, it' s done!
```
OpenSCAD Version: 2018.04.15
System information: Linux 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 Linux Mint 18.1 8 CPUs 15.58 GB RAM
Compiler: GCC "5.4.0 20160609" 64bit
Boost version: 1_58
Eigen version: 3.2.92
CGAL version, kernels: 4.7, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.5.1
QScintilla version: 2.9.1
MingW build: No
GLib version: 2.48.2
libzip version: 1.0.1
Application Path: /usr/local/bin
Documents Path: /home/kwendenarmo/.local/share
Resource Path: /usr/local/share/openscad
User Library Path: /home/kwendenarmo/.local/share/OpenSCAD/libraries
User Config Path: /home/kwendenarmo/.config/OpenSCAD
Backup Path: /home/kwendenarmo/.local/share/OpenSCAD/backups
OPENSCADPATH: 
OpenSCAD library path:
/home/kwendenarmo/.local/share/OpenSCAD/libraries
/usr/local/share/openscad/libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 1.13.0
OpenGL Version: 3.0 Mesa 17.2.8
GL Renderer: Mesa DRI Intel(R) Haswell Mobile 
GL Vendor: Intel Open Source Technology Center
RGBA(8880), depth(0), stencil(0)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(8880), depth(0), stencil(0)

GL Extensions:
GL_3DFX_texture_compression_FXT1
GL_AMD_conservative_depth
GL_AMD_draw_buffers_blend
GL_AMD_seamless_cubemap_per_texture
GL_AMD_shader_trinary_minmax
GL_ANGLE_texture_compression_dxt3
GL_ANGLE_texture_compression_dxt5
GL_APPLE_object_purgeable
GL_APPLE_packed_pixels
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_instanced
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_window_pos
GL_ATI_blend_equation_separate
GL_ATI_draw_buffers
GL_ATI_separate_stencil
GL_ATI_texture_env_combine3
GL_ATI_texture_float
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_copy_texture
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_gpu_program_parameters
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset
GL_EXT_polygon_offset_clamp
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_specular_color
GL_EXT_shader_integer_mix
GL_EXT_shader_samples_identical
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_subtexture
GL_EXT_texture
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_object
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_IBM_multimode_draw_arrays
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_INGR_blend_func_separate
GL_INTEL_performance_query
GL_KHR_blend_equation_advanced
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_MESA_pack_invert
GL_MESA_shader_integer_functions
GL_MESA_texture_signed_rgba
GL_MESA_window_pos
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_depth_clamp
GL_NV_light_max_exponent
GL_NV_packed_depth_stencil
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_env_combine4
GL_NV_texture_rectangle
GL_OES_EGL_image
GL_OES_read_format
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_border_clamp
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays
```

Anyway, it would be nice to update the list of dependencies in the README, as well as in the `check-dependencies.sh` script, which continues to validate from 1.3.2.
Maybe add an explicit note to that it may be necessary to manually update OpenCSG.


Does this mean that the original problem has been fixed?
No. No. It continues to fail in the same way as above.

**Comment by t-paul** [comment] 2018-04-15 20:48
The version number shown is the library it's compiled against, so if you still have the one from the distribution installed, it might pick up that at runtime still.
Can you check via `ldd openscad | grep opencsg` where the library is actually loaded from?

**Comment by kwendenarmo** [comment] 2018-04-15 20:57
Of course.

```
ldd `which openscad` | grep opencsg
libopencsg.so.1 => /usr/local/lib/libopencsg.so.1 (0x00007f556134b000)
```
Point to the library I compiled today, the latest version:
```
lrwxrwxrwx  1 root root    19 abr 15 19:55 libopencsg.so.1 -> libopencsg.so.1.4.2
```

**Comment by t-paul** [comment] 2018-04-15 21:06
I'm running out of ideas. I can't reproduce the issue on my system, which is not that different just a bit newer as it's running Debian/Testing.

I also tried the [AppImage](https://download.opensuse.org/repositories/home:/t-paul/AppImage/OpenSCAD-Nightly-latest-x86_64.AppImage) which also did not show the issue. Would you give that a try to compare results with the same binary?

**Comment by kwendenarmo** [comment] 2018-04-15 21:17
Interesting, running the AppImage all seems to work fine. I will test it more intensively soon.
Btw, has the color set in the rendering been changed? The lower (-z) part of the preview appears much darker from the AppImage.

**Comment by kwendenarmo** [comment] 2018-04-15 21:27
At least it seems to be working fine. I'll try it in the next few days and tell you something. Anyway, any idea why my compiled version wasn't working properly?

**Comment by Philius** [comment] 2018-11-02 16:35
I've been getting preview issues for over a month.
I'm using nightly on Debian Stretch amd64.
In case this helps the AppImage I just downloaded is
OpenSCAD-Nightly-0-Build2531.1.glibc2.14-x86_64.AppImage
Animation still blanks out if I change values in the Customizer.
[appimage-library-info.txt](https://github.com/openscad/openscad/files/2543319/appimage-library-info.txt)
[nightly-library-info.txt](https://github.com/openscad/openscad/files/2543332/nightly-library-info.txt)
A cursory glance shows that some libraries in the AppImage are older than those installed on my system.
The issues happen if I use Intel or NVidia through optirun.

**Comment by t-paul** [comment] 2018-11-02 19:47
@Philius can you please be a bit more specific? What issues? Exactly what is described by the OP? Those happen on Stretch or with the AppImage or with both?

As discussed above, one of the important things is OpenCSG which specifically is built for the AppImage to be at version 1.4.2. We can't really have the means to fix that in all older distributions, that would need to be handled by the respecitive maintainers.

**Comment by MichaelPFrey** [comment] 2018-11-03 07:15
> Animation still blanks out if I change values in the Customizer.

Customizer and animations are not really optimized for each other, as both try to influence variables and recompile the design. Recompiling the design requires rebuilding the customizer. I mean: That could be tweaked, but there is the old feature, that you can change the code while the animation is running - and this is where things start to get painful.

**Comment by t-paul** [comment] 2018-11-03 08:44
If the interaction between animation and customizer is the only issue, that seems pretty unrelated to everything discussed here, neither of the two things were mentioned before. Hence my questions to be a bit more specific.

We should have customizer/animation interaction as separate issue with a clear description and not mixed up in a different discussion.

**Comment by Philius** [comment] 2018-11-06 17:09
@t-paul [hypocycloid.scad.gz](https://github.com/openscad/openscad/files/2554222/hypocycloid.scad.gz)
Curious that .scad uploads aren't supported by github :(
Version 2018.11.05.nightly (git e1f043d)
Anyway I open hypocycloid.scad and the screen shows the axes and rulers but no model.
I press reset (in the customizer) and the model appears.
I press animate and the model disappears.
I enter a frame rate and steps and the console flashes but no model animation.

**Comment by t-paul** [comment] 2018-11-06 19:55
The library info of your nightly shows OpenCSG 1.4.0, this version has issues with the drawing buffers, so there's not much to do about this. The issues described in the original post seem to be caused by that.

If your problem shows with the AppImage too (which has OpenCSG 1.4.2), please add your info to the new ticket (#2548) @MichaelPFrey created specifically about interaction between Customizer and Animation.

**Comment by AndKe** [comment] 2018-12-06 13:43
same issue here, highly frustrating.   Always one error away from forced restart.
(openscad-nigtly on snap)

**Comment by t-paul** [comment] 2018-12-06 19:37
Snap (on [snapcraft.io](https://snapcraft.io/openscad-nightly)) builds against "Ubuntu Core 16" which has OpenCSG 1.4.0. There might be a way to also build an updated OpenCSG library.

**Comment by t-paul** [comment] 2019-02-19 18:18
Looks like all cases are caused by older OpenCSG with known bug, so I'm closing this here. If there are new reports with OpenCSG >= 1.4.2, please open a new issue.

**Closed by t-paul** 2019-02-19 18:18 UTC
Labels: Waiting for feedback
