### ISSUE TITLE
OpenSCAD always starts non-maximised irrespective of last state

### ISSUE THREAD

**Issue by Chalmes** [openscad/openscad#1436] opened 2015-09-08 20:22 UTC
Windows 7.

Maximise the OpenSCAD window, and then exit.  When re-opened by double-clicking an associated .scad file, the OpenSCAD window is no longer maximised, and now its size is larger than the screen making the minimise/maximise/close buttons slightly offscreen.

![image](https://cloud.githubusercontent.com/assets/2739794/9746396/d052a61e-56cb-11e5-9d8e-09dc1c92ff8e.png)

**Comment by kintel** [comment] 2015-09-08 20:37
Closing as duplicate of #1265

**Closed by kintel** 2015-09-08 20:37 UTC
