### ISSUE TITLE
better handle new unsaved flename in warning messages

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2979] opened 2019-06-27 05:50 UTC
2019.05
With File/New, not saved 'Untitled.scad' in window title, warnings show as:

```
WARNING: len() parameter could not be converted, in file ./, line 2
WARNING: Unable to convert square(size=[20, 20, 20], ...) parameter to a number or a vec2 of numbers, in file ./, line 9
```

I think `, in file Untitld.scad, line nn` would be better.

**Comment by t-paul** [comment] 2019-06-27 08:34
Duplicate of #2878.

**Closed by t-paul** 2019-06-27 08:34 UTC

**Comment by MichaelAtOz** [comment] 2019-06-27 08:38
oops...
