### ISSUE TITLE
Intersection is interacting with unexpected objects.

### ISSUE THREAD

**Issue by axle12693** [openscad/openscad#4412] opened 2022-11-08 16:03 UTC
In the following toy example, I would expect the red cylinder with radius 1 not to be shown.

`$fn=100;

translate([0.5,0.8,0]) color("green") cylinder(0.2,1,1);
color("red") intersection() {
    translate([.9,0,0]) cylinder(0.2,0.2,0.2);
    cylinder(0.2, 1, 1);
}`

However, where it intersects with the green cylinder, it is shown. Is this a bug, or a fault in my understanding?

Using OpenSCAD 2021.01 on Windows 10 Home.

**Comment by UBaer21** [comment] 2022-11-08 16:24
I got
![image](https://user-images.githubusercontent.com/93376232/200619696-b0530956-cb37-426b-91ff-a226945f67a9.png)
you may see z-fighting so while the red and green share the same plane you see the color bleeding through.
You can use render() (after the color) to calculate the points in preview.

**Comment by Scopeuk** [comment] 2022-11-08 16:28
trying this I am seeing z fighting at angles but it occurring where it should not, the colour modifier appears to be causing elements that were "removed" by the intersection to show as z fighting over the green shape
![image](https://user-images.githubusercontent.com/44125258/200620920-a6fd2035-33ab-4245-9ccb-1dc50678529d.png)

swapping the order to
`$fn=100;
color("red") intersection() {
translate([.9,0,0]) cylinder(0.2,0.2,0.2);
cylinder(0.2, 1, 1);
}
translate([0.5,0.8,0]) color("green") cylinder(0.2,1,1);
`

resolves the visual issues. this looks like a bug to me.

**Comment by UBaer21** [comment] 2022-11-08 16:31
@Scopeuk  Sorry should have clarified that i used an z-offset to get rid of the z-fighting - i thought the bug was about wrong geometry .. those z-fighting happens all the time with all objects involved when not using render.

**Comment by Scopeuk** [comment] 2022-11-08 16:33
the z fighting is expected, the issue is the size of the red component, it should be much smaller, we appeared to have colour coded it's constituent parts rather than the result of the intersection

**Comment by UBaer21** [comment] 2022-11-08 16:50
when coloring the intersection objects this can be seen 
![image](https://user-images.githubusercontent.com/93376232/200626013-307518de-8ed2-4249-b945-9b3717c77377.png)
```
$fn=36;
translate([0.5,0.8,0]) color("green") cylinder(0.2,1,1);
intersection() {
color("red")translate([.9,0,0]) cylinder(0.2,0.2,0.2);
color("blue")cylinder(0.2, 1, 1);
}
```

**Comment by thehans** [comment] 2022-11-08 16:54
Duplicate of #1000

**Closed by thehans** 2022-11-08 16:54 UTC
