### ISSUE TITLE
export and import of presets

### ISSUE THREAD

**Issue by krhackbarth** [openscad/openscad#3836] opened 2021-07-08 20:32 UTC
I'd like to see functionality (that doesn't involve json file editing) whereby I could export a preset and another person could import that preset - for the same OpenSCAD program.

**Comment by t-paul** [comment] 2021-07-08 22:08
I assume that is about customizer presets, in that case it's a duplicate of #3137.

**Closed by t-paul** 2021-07-08 22:08 UTC
