### ISSUE TITLE
MacOS Dark Mode - Customizer Font Unreadable

### ISSUE THREAD

**Issue by RedFrez** [openscad/openscad#3239] opened 2020-03-02 22:36 UTC
When using MacOS (Catalina 10.15.3) in the Dark Appearance Mode, the customizer text remains black and is incredibly difficult to read. This is not a problem if in light mode. 

![OpenScad Mac Dark](https://user-images.githubusercontent.com/30352852/75724093-3d887880-5ca3-11ea-8d89-41bbf6a27158.png)

Less important, it would be nice if the console inverted colors.

**Comment by t-paul** [comment] 2020-03-02 22:48
Duplicate of #2785.

**Closed by t-paul** 2020-03-02 22:48 UTC
