### ISSUE TITLE
Problem with mounted file system on Windows

### ISSUE THREAD

**Issue by hugob123** [openscad/openscad#3564] opened 2020-12-31 09:53 UTC
I have a problem with OpenScad on my new Win 10 system. I try to use a mounted file system. A disk is mounted on C:/data. This works just like a simple mount on Unix (and it is somethinge else than a shortcut).
when I try to open an file, it throws an error. See attachment.
The version I am using is  2020.11.20.ci6197 (git 8a905133a)
The OS is Win 10 (Pro version) with the latest updates 
Until now OpenScad is the first and only software that I have installed that has a problem with these mounted drives.
The path contains no spaces nor weird characters..

![afbeelding](https://user-images.githubusercontent.com/3153529/103404874-77413e80-4b55-11eb-9b10-8a9f6413ab86.png)

**Comment by t-paul** [comment] 2020-12-31 16:07
Duplicate of #1309.

**Closed by t-paul** 2020-12-31 16:07 UTC
