### ISSUE TITLE
Intersection with if(false)... renders nothing in 2020.12-RC3

### ISSUE THREAD

**Issue by JeffreyRodriguez** [openscad/openscad#3554] opened 2020-12-26 19:42 UTC
### 2020.12-RC3
Expected (2019.05):
![image](https://user-images.githubusercontent.com/505322/103158128-6ff1ed80-476f-11eb-9008-4c603d0e77d6.png)

Actual (2020.12-RC3):
![image](https://user-images.githubusercontent.com/505322/103158109-2903f800-476f-11eb-87a3-c117b4f8daea.png)

Removing the false condition renders as expected (2020.12-RC3):
![image](https://user-images.githubusercontent.com/505322/103158187-13430280-4770-11eb-9fda-e94c99c11536.png)

Code to reproduce:
```
intersection() {
  cube();
  
  if (false)
  cylinder();
}
```

System information: 5.4.0-58-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

**Comment by t-paul** [comment] 2020-12-26 19:48
Duplicate of #3452.

**Closed by t-paul** 2020-12-26 19:48 UTC
