### ISSUE TITLE
# at the beginning of the line hangs Emacs

### ISSUE THREAD

**Issue by alexander31415926535** [openscad/openscad#3410] opened 2020-08-17 15:33 UTC
When i try to add # (shift-3 on Mac) at the beginning of the line, emacs hangs. Manual restart is needed. It is possible to add # sign anywhere else but the beginning of the line.

**Comment by t-paul** [comment] 2020-08-17 15:35
Duplicate of #2969.

**Closed by t-paul** 2020-08-17 15:35 UTC

**Comment by t-paul** [comment] 2020-08-17 15:38
Note that the linked issue seems to reference a fix, but I don't see a PR for that here yet. Maybe see if that works for you.
