### ISSUE TITLE
Wrong line number of included file in error message

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3093] opened 2019-10-15 23:54 UTC
Introduced after 2019.06.21

The error is at line 247, later versions say it is 281.
![Capture include line number wrong](https://user-images.githubusercontent.com/1972961/66877913-3ff37a00-f003-11e9-8eee-6b1b6416944c.JPG)

**Comment by t-paul** [comment] 2019-10-24 18:23
Is that with warnings as error? And is it actually the same place in the file causing the error? There could be changes to warnings between the versions causing the different behavior.

**Comment by MichaelAtOz** [comment] 2019-10-24 22:46
> Is that with warnings as error?

If you mean stop on first warning, no, and is is an ERROR. See prefs below.
Note the error (fabricated this time), was due to changing assign() to basic assignments, assign() between to other transformations was valid, but assignment is not. As people may be doing this more often when assign(0 gets dropped, I wonder is a clearer error message is possible?

> And is it actually the same place in the file causing the error?

Not sure what you mean, OP was two Openscads running at the same time with the same source files. Same error in the included file, later version reported it as a different line number.

![Capture 20191006 line number error](https://user-images.githubusercontent.com/1972961/67530747-d3b3fd00-f70b-11e9-8515-b6713ddae7ab.JPG)

**Comment by t-paul** [comment] 2019-10-25 23:15
I can't reproduce that so far. Maybe a caching issue when working with multiple tabs?

**Comment by MichaelAtOz** [comment] 2019-10-25 23:55
Here is the include library with the fabricated error at line 253.
[text_on.zip](https://github.com/openscad/openscad/files/3774170/text_on.zip)
With a fresh run of 2019.10.06, and `include <text_on.scad>` the only code at line 1, F5 gives error at line 253.
If I insert blank lines before it the reported line number goes up.
![Capture 20191006 line number error B](https://user-images.githubusercontent.com/1972961/67610495-f06d3500-f7de-11e9-972a-b2cb604e69af.JPG)

**Comment by MichaelAtOz** [comment] 2019-10-26 00:42
I can't see if it would matter, but the library is accessed via the first directory here
`OPENSCADPATH: C:\Users\MeB\Documents\3D-REPRAP\OpenSCAD\OpenSCAD Libraries;C:\Users;C:\test;C:\test2;C:\test-uc-?` (hmm, that ? was a unicode char...)

**Comment by t-paul** [comment] 2019-10-26 00:55
Ahh, I see, that error is not using the full location object but the separate `yylineno` which is not rest at `include<>`. Should be easy to fix.

**Comment by t-paul** [comment] 2019-10-26 01:13
#3106

**Comment by t-paul** [comment] 2019-11-11 14:59
Fixed via https://github.com/openscad/openscad/commit/0fd84dbc4634f3be1b904fd31b1b49b05137c923

**Closed by t-paul** 2019-11-11 14:59 UTC
