### ISSUE TITLE
rands() fails when the start and end of the range are the same.

### ISSUE THREAD

**Issue by mrbenbritton** [openscad/openscad#452] opened 2013-08-10 21:19 UTC
Hello all:

I want to be able to pass the spread into rands. If the spread is zero OpenSCAD stops responding and needs to be killed. I was expecting it to return the start/end of range number.

Windows 7, OpenSCAD 2013.06

```
// This fails if spread = 0.
// This works if spread != 0.
spread = 0;
random_numbers = rands(1-spread, 1+spread, 1);
```
##

**Comment by ZoomDomain** [comment] 2015-09-17 02:54
I have another issue, that it doesnt work inside a loop using figures from another rands...

I can find a workaround for this but I am surprised it's just produces non random results.

seed = rands(0,190,1)[0]; //seed used to randomize two groups of random numbers.
echo(seed);

t= rands(0,1,20,seed); //first group of random numbers

for(i = [0 : 4]) // have four groups of similar objects, i.e. all on the same random row
{ 
r = rands(0,1,40,t[i]); 
    for(h = [0 : 24]) // where each group can use a different set of random values
    { 
         foobar(...r[h])
    }


}

**Comment by kintel** [comment] 2015-09-17 03:51
Good catch. The problem is that the seed is truncated to int.

**Comment by donbright** [comment] 2015-09-18 23:55
i will fix this tonight

**Comment by donbright** [comment] 2015-09-19 06:10
pushed first attempt, branch https://github.com/openscad/openscad/compare/issue452part2

still needs some work, currently 0.01101b and 0.00001101b produce same seed. also, what to do about infinite range inputs. need to do regression test data also.

**Comment by donbright** [comment] 2015-09-24 03:04
I copied python's floating point hash code, https://github.com/python/cpython/blob/master/Python/pyhash.c ,  and added some checks for infinite inputs to rands(), i have tested on 

x86-32 debian 7 
amd64 debian 7
amd64 ubuntu 14.04

will continue testing and do a pull request soon(TM)

**Comment by donbright** [comment] 2015-09-29 01:17
tests also pass on

32 bit SPARC, Solaris SunOS 5.10
ppc64 fedora linux 18

**Comment by kintel** [comment] 2015-10-16 17:34
@donbright How is it going with that branch - is it ready to be merged?

**Comment by donbright** [comment] 2015-10-24 03:02
also tested on netbsd 32bit
C++ code tested on MacOSX PPC 

cleaning patch now

**Comment by donbright** [comment] 2015-11-15 03:30
sooo anything i can do to bring this to closable status?

**Comment by kintel** [comment] 2015-11-15 03:51
I merged your pull request. Are there other outstanding issues related to this?

**Comment by donbright** [comment] 2015-11-15 05:07
there is nothing i know of.

**Comment by kintel** [comment] 2015-11-16 15:35
Printing  ```std::numeric_limits<double>``` gives different output on i686 vs. x86_64, reported by @keenerd. See below for test failure excerpt. Failing test is echotest_rands.

```
@@ -20,21 +20,21 @@

 WARNING: resetting to 89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
 WARNING: rands() cannot create an infinite number of results
 WARNING: resetting number of results to 1
-ECHO: "rands(1/0,1/0,1/0,-1/0)", [-9300377652654166128060603475850713000293501474922443063507207026945588318717091192025028882115570951042626583985011686900155640117874164051603353244310517845033408717801751661166920239068617262628971552363024772601967872546644706234854673867869142431130697461329893306385034235452701527814810567411813580800]
-WARNING: rands() range min cannot be infinite
-WARNING: resetting to -89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
-WARNING: rands() range max cannot be infinite
-WARNING: resetting to 89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
-WARNING: rands() cannot create an infinite number of results
-WARNING: resetting number of results to 1
-ECHO: "rands(1/0,1/0,1/0,1.1)", [2559225604731159729917496516459263182383250788247167445377934305240165062728205398216921128075335520484433677462146112065036394690237323498542875537267016320184083079702537573615936740527526504319749001754762987901298548632442051353785468197833271658422571592504792508314029496796671198751403171214549581824]
-WARNING: rands() range min cannot be infinite
-WARNING: resetting to -89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
-WARNING: rands() range max cannot be infinite
-WARNING: resetting to 89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
-WARNING: rands() cannot create an infinite number of results
-WARNING: resetting number of results to 1
-ECHO: "rands(1/0,1/0,1/0,-1.1)", [-34765946307431883058945607364533820105256535554593193644123039389802319268408110417279252824405518608310450404570801207189334070336781804804635669671465126173915687410738020586168641757496968446960001628511321633335414193452473365380029593204318411587833969829568468890108549759673084562613546738345796698112]
+ECHO: "rands(1/0,1/0,1/0,-1/0)", [-9300377652654164880660410016650830715060555826898339271350169254784624879625064668767596464013029835443898151087698506061126362497564636568829610498314479883051034789782113961163374644640069439167895649636157783443619907206692210403098139417325149375596154681302294864434467438105175501340751048446807375872]
+WARNING: rands() range min cannot be infinite
+WARNING: resetting to -89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
+WARNING: rands() range max cannot be infinite
+WARNING: resetting to 89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
+WARNING: rands() cannot create an infinite number of results
+WARNING: resetting number of results to 1
+ECHO: "rands(1/0,1/0,1/0,1.1)", [2559225604731169397268995825258350892938579560433971834594977039487631715691410953462022368370029166374579032416323263567513296247636161490039381818736310525547481021854729748643415097348772136143087247887982153878495280017073894049898610189549217838815278137718680433430922176239997903925364443193347670016]
+WARNING: rands() range min cannot be infinite
+WARNING: resetting to -89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
+WARNING: rands() range max cannot be infinite
+WARNING: resetting to 89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
+WARNING: rands() cannot create an infinite number of results
+WARNING: resetting number of results to 1
+ECHO: "rands(1/0,1/0,1/0,-1.1)", [-34765946307431878069344833527734290964324752962496778475494888301158465512040004324249523151995354145915536672981548483833216959855543694873540698687480974325986191698659469786154459379782777153115698017603853676702022332092663382053003455402142439365695798709458075122306282570282980456717308662485771878400]
 WARNING: rands() range min cannot be infinite
 WARNING: resetting to -89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184.000000
 WARNING: rands() range max cannot be infinite
@@ -48,21 +48,21 @@
```

**Comment by donbright** [comment] 2015-11-17 23:45
ok having some trouble tracking this down. 

```
#include <iostream>
#include <limits>
main() {
     std::cout << std::numeric_limits<double>::max() << "\n";
}
```

gives me 

    1.79769e+308

on i386 NetBSD 7, i686 Ubuntu 12, and x86_64 Ubuntu 14...

will continue testing...

**Comment by donbright** [comment] 2015-11-18 00:15
Where are all those digits coming from?

I am running master branch tests on i686 and i get this under 

    tests/echotest-output/rands-actual.echo

WARNING: rands() cannot create an infinite number of results
WARNING: resetting number of results to 1
ECHO: "rands(1/0,1/0,1/0,-1/0)", [-9.30038e+306]
WARNING: rands() range min cannot be infinite

**Comment by donbright** [comment] 2015-11-18 00:20
oh i see... its in the 2015.03 branch that this is happening... ok.

**Comment by donbright** [comment] 2015-11-18 00:50
OK it seems like the double max is the same on both... and the hash_floating_point returns same on both. and cast int32 to uint32 is same on both.... will have to keep testing. 

here is a basic test program

```
#include <iostream>
#include <limits>
#include <stdint.h>
#include <cmath>

/* Hash a floating point number, copied almost line by line from 
Python's pyhash.c, originally by the Python team, Mark Dickinson, et al. 
The copyright License for this code can be found in under 
../doc/Python-LICENSE.TXT. Changes from the original code include 
de-scattering typedefs, and removing the -1 special return case.
This is designed so srand() will work better with floating point 
numbers. An oversimplified explanation is that the code calculates the 
Remainder of the input divided by 2^31, in a very portable way. See also:
http://bob.ippoli.to/archives/2010/03/23/py3k-unified-numeric-hash/
https://github.com/python/cpython/blob/master/Python/pyhash.c
https://github.com/python/cpython/blob/master/Include/pyhash.h
http://stackoverflow.com/questions/4238122/hash-function-for-floats
http://betterexplained.com/articles/fun-with-modular-arithmetic/
*/
typedef int32_t Py_hash_t;
typedef uint32_t Py_uhash_t;
typedef double Float_t;
Py_hash_t hash_floating_point(Float_t v)
{
    int _PyHASH_BITS = 31;
    //if (sizeof(Py_uhash_t)==8) _PyHASH_BITS=61;

    Py_uhash_t _PyHASH_MODULUS = (((Py_uhash_t)1 << _PyHASH_BITS) - 1);
    Py_uhash_t _PyHASH_INF = 314159;
    Py_uhash_t _PyHASH_NAN = 0;

    int e, sign;
    Float_t m;
    Py_uhash_t x, y;

    if (!std::isfinite(v)) {
        if (std::isinf(v))
            return v > 0 ? _PyHASH_INF : -_PyHASH_INF;
        else
            return _PyHASH_NAN;
    }

    m = frexp(v, &e);

    sign = 1;
    if (m < 0) {
        sign = -1;
        m = -m;
    }

    /* process 28 bits at a time;  this should work well both for binary
       and hexadecimal floating point. */
    x = 0;
    while (m) {
        x = ((x << 28) & _PyHASH_MODULUS) | x >> (_PyHASH_BITS - 28);
        m *= 268435456.0; // 2**28
        e -= 28;
        y = (Py_uhash_t)m;  /* pull out integer part */
        m -= y;
        x += y;
        if (x >= _PyHASH_MODULUS)
            x -= _PyHASH_MODULUS;
    }

    /* adjust for the exponent;  first reduce it modulo _PyHASH_BITS */
    e = e >= 0 ? e % _PyHASH_BITS : _PyHASH_BITS-1-((-1-e) % _PyHASH_BITS);
    x = ((x << e) & _PyHASH_MODULUS) | x >> (_PyHASH_BITS - e);

    x = x * sign;
    return (Py_hash_t)x;
}

main() {
std::cout.precision(800);

double x =   std::numeric_limits<double>::max()/2;
double y =  -std::numeric_limits<double>::max()/2;
uint32_t seedx = static_cast<uint32_t>(hash_floating_point( x ) ) ;
uint32_t seedy = static_cast<uint32_t>(hash_floating_point( y ) ) ;
std::cout << x << "\n";
std::cout << hash_floating_point(x) <<  "\n";
std::cout << seedx <<  "\n";
std::cout << y << "\n";
std::cout << hash_floating_point(y) <<  "\n";
std::cout << seedy <<  "\n";
}
// end test.cc

linux x86_64:
don@serebryanya:~$ ./a.out 
89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184
2147483136
2147483136
-89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184
-2147483136
2147484160


netbsd i386

don@blue:~$ ./a.out 
89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184
2147483136
2147483136
-89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184
-2147483136
2147484160

```

**Comment by kintel** [comment] 2015-11-18 01:01
@donbright: FYI: This was reported by @keenerd while testing on Arch

**Comment by donbright** [comment] 2015-11-18 01:06
thanks... any chance of a --info dump (sysinfo.txt) ???  (interested in the boost version)

**Comment by donbright** [comment] 2015-11-18 01:59
narrowed it down. 

the hashing and casting is all fine. it's boost. 

                            boost::uniform_real<> distributor( min, max );
                            distributor(deterministic_rng);

this returns different values on 32bit and 64bit machines. 

which......

once was "buggy", now is deprecated!!!

http://www.boost.org/doc/libs/1_44_0/doc/html/boost/uniform_real.html

http://www.boost.org/doc/libs/1_51_0/boost/random/uniform_real.hpp

**Comment by donbright** [comment] 2015-11-18 02:26
in -std=c++11 this works  the same on both 

```
#include <random>
#include <iostream>

int main()
{
    std::mt19937 gen;
    std::cout.precision(1000);
    double lo = - std::numeric_limits<double>::max() / 2 ;
    double hi = + std::numeric_limits<double>::max() / 2 ;
    std::uniform_real_distribution<> dis(lo, hi);
    std::cout << lo << '\n';
    std::cout << hi << '\n';
    std::cout << dis(gen) << '\n';
}

```

**Comment by donbright** [comment] 2015-11-18 04:33
minimal boost example - this has different output on a 32bit x86 machine vs 64bit. both on gcc and clang. (this is not the deprecated "uniform_real")

```
#include <iostream>
#include <boost/random/mersenne_twister.hpp>
#include <boost/random/uniform_real_distribution.hpp>

int main()
{
    boost::mt19937 gen;
    gen.seed(4294653137UL);
    std::cout.precision(1000);
    double lo = - std::numeric_limits<double>::max() / 2 ;
    double hi = + std::numeric_limits<double>::max() / 2 ;
    boost::random::uniform_real_distribution<double> boost_distrib(lo, hi);
    std::cout << "lo " << lo << '\n';
    std::cout << "hi " << hi << "\n";
    std::cout << "boost distrib g4 " << boost_distrib(gen) << '\n';
}

```

**Comment by donbright** [comment] 2015-11-19 03:17
think i tracked it down to boost uniform_real_distribution.hpp

this line inside generate_uniform_real() :

        T result = numerator / divisor * (max_value - min_value) + min_value;

results in 

     numerator / divisor * (max_value - min_value) = 

80584279090461619279203108390001465398741782288000055235951531374633042071297178188269750434267868134727602892772179545217005023326857927332630420107458240647991546570473889376955824806126047209408962701864542198550323745904966767848049605798192531706268215640742468277984054355006948412810391445680248848384

      with min_value of 

-89884656743115785407263711865852178399035283762922498299458738401578630390014269380294779316383439085770229476757191232117160663444732091384233773351768758493024955288275641038122745045194664472037934254227566971152291618451611474082904279666061674137398913102072361584369088590459649940625202013092062429184

adding those two terms together gives the different results. 


the code seems to be as follows

gcc -S shows assembler,

32 bit

```
        fldl    56(%esp)
        fdivl   48(%esp)
        fldl    20(%ebp)
        fsubl   12(%ebp)
        fmulp   %st, %st(1)
        faddl   12(%ebp)
        fstpl   16(%esp)
```

whilst on 64 bit

```
        movsd   -40(%rbp), %xmm0
        movapd  %xmm0, %xmm1
        divsd   -32(%rbp), %xmm1
        movsd   -72(%rbp), %xmm0
        subsd   -64(%rbp), %xmm0
        mulsd   %xmm1, %xmm0
        addsd   -64(%rbp), %xmm0
        movsd   %xmm0, -80(%rbp)
```

**Comment by donbright** [comment] 2015-11-25 02:08
Apparently the problem boils down to the fact that on 32 bit x86 cpus, gcc uses extended precision (80 bits) on c++ math binary floating point expressions, but on 64 bit x86 cpus gcc uses SSE which is only 64 bits IEEE double precision (aka 53 bits mantissa). (counter intuitive. more bits on CPU = less bits in FPU calcs per default)  

CGAL has been dealing with these issues for years . https://github.com/CGAL/cgal/blob/da3d119acbe8e517cb1880cc124f0305b4bfc89d/Number_types/include/CGAL/FPU.h
So... I'm kind of wondering...

Would it be OK if OpenSCAD forces gcc on 32-bit x86 processors to use plain old 64 bit double precision for all calculations ? This can apparently be done on program startup with

      fldcw

http://www.network-theory.co.uk/docs/gccintro/gccintro_70.html

**Comment by kintel** [comment] 2015-11-25 03:21
For this particular issue (how to deal with infinity), I don't think it really matters. The only issue is how to make the tests work across platforms.

Down the road, however, this may become a lot more interesting (and might already be in terms of temporary result for various calculations).

**Comment by donbright** [comment] 2015-11-25 23:40
it reminds me a lot of this issue ( that i dropped the ball on )

https://github.com/openscad/openscad/issues/756

https://github.com/openscad/openscad/issues/978

**Comment by t-paul** [comment] 2020-06-05 19:36
Can't reproduce anymore with latest release.

**Closed by t-paul** 2020-06-05 19:36 UTC
