### ISSUE TITLE
fast-csg: segfault on render

### ISSUE THREAD

**Issue by adrianVmariano** [openscad/openscad#4421] opened 2022-11-21 01:00 UTC
Runing in 2022.11.11 with all the fast-csg stuff turned on and lazy union turned on, I get a segfault and messages that read:

Error: Failed to find the next edge to walk to along the patch border!

```
include<BOSL2/std.scad>
include<BOSL2/rounding.scad>


head_diam=14.2;
shaft_diam=8;
depth=18;
thickness=2;

function slot(slotwidth, slotheight, slotradius, topradius) = let(
    angle = 85,
    slot = round_corners(
        turtle([
            "right",
            "move", slotwidth,
            "left", angle,
            "move", slotwidth/2,
            "right", angle,
            "move", slotheight,
            "left",
            "move", slotwidth,
            "left",
            "move", slotheight,
            "right", angle,
            "move", slotwidth/2,
            "left", angle,
            "move", slotwidth
        ]),
        radius = [0,0,topradius, slotradius, slotradius, topradius, 0,0], closed=false
    )
) apply(left(max(column(slot,0))/2)*fwd(min(column(slot,1))), slot);
diam = head_diam+2*thickness;
wall = thickness;
height = depth;
$fn=32;
//ycopies(n=2,spacing=26)
right_half()
    difference(){
        cyl(d=diam, rounding2=wall/2, h=height, anchor=BOTTOM);
        down(.01)cyl(d=diam-2*wall, rounding2=-wall/2, h=height+.02, anchor=BOTTOM);
        zrot_copies(n=3) //rots=[120, 240])
          bent_cutout_mask(diam/2-wall/2, wall+.03, subdivide_path(apply(back(0),slot(shaft_diam*1.2, depth, 0, shaft_diam/4)),250));
}
up(.01)cuboid([22,50,2],anchor=TOP,rounding=7,edges="Z");
```

**Comment by thehans** [comment] 2022-11-21 12:24
I was able to reproduce on Linux Mint 21 with a debug build.  Here is backtrace from gdb.  
At first I was not able to reproduce the crash (error messages were shown, but no segfault).  But that was only because I had "Stop on first warning" enabled.

Here is some of the command line output:
```
Error: Failed to find the next edge to walk to along the patch border!                         
Error: Failed to find the next edge to walk to along the patch border!                                                                                                                         
Error: Failed to find the next edge to walk to along the patch border!                                                                                                                         
Error: Failed to find the next edge to walk to along the patch border!                                                                                                                         
Error: Failed to find the next edge to walk to along the patch border!                         
Error: Failed to find the next edge to walk to along the patch border!                                                                                                                         Error: Failed to find the next edge to walk to along the patch border!                                                                                                                         
CGAL error: precondition violation!                                                                                                                                                            
Expression : CGAL::is_valid_polygon_mesh(tm)                                                                                                                                                   
File       : /usr/include/CGAL/Polygon_mesh_processing/orientation.h                                                                                                                           
Line       : 190                                                                                                                                                                               Explanation:                                                                                                                                                                                   
Refer to the bug-reporting instructions at https://www.cgal.org/bug_report.html                                                                                                                
                                                                                               
Thread 28 "QThread" received signal SIGSEGV, Segmentation fault.
```

<details>
<summary>And backtrace from GDB</summary>

```C++
#0  0x0000555555df0522 in CGAL::SNC_indexed_items::SHalfedge<CGAL::SNC_structure<CGAL::Epeck, CGAL::SNC_indexed_items, bool> >::set_index (this=0x0, idx=8370)
    at /usr/include/CGAL/Nef_3/SNC_indexed_items.h:157
#1  0x0000555555ed1ffb in CGAL::Face_graph_index_adder<CGAL::SNC_indexed_items, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >, CGAL::SNC_structure<CGAL::Epeck, CGAL::SNC_indexed_items, bool>, CGAL::SM_index_pmap<CGAL::Point_3<CGAL::Epeck>, CGAL::SM_Halfedge_index> >::resolve_indexes (this=0x7ffff02bc1e0) at /usr/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h:159
#2  0x0000555555ed14f9 in CGAL::polygon_mesh_to_nef_3<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >, CGAL::SNC_structure<CGAL::Epeck, CGAL::SNC_indexed_items, bool>, CGAL::SM_index_pmap<CGAL::Point_3<CGAL::Epeck>, CGAL::SM_Face_index>, CGAL::SM_index_pmap<CGAL::Point_3<CGAL::Epeck>, CGAL::SM_Halfedge_index> > (P=..., S=..., fimap=..., himap=...)
    at /usr/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h:316
#3  0x0000555555e85585 in CGAL::polygon_mesh_to_nef_3<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >, CGAL::SNC_structure<CGAL::Epeck, CGAL::SNC_indexed_items, bool> > (sm=..., snc=...)
    at /usr/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h:337
#4  0x0000555555e85370 in CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>::Nef_polyhedron_3<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> > > (this=0x5b4b1ade790, pm=...)
    at /usr/include/CGAL/Nef_polyhedron_3.h:627
#5  0x0000555555e85251 in __gnu_cxx::new_allocator<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool> >::construct<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >&> (this=0x7ffff02bc730, __p=0x5b4b1ade790, __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/ext/new_allocator.h:162
#6  0x0000555555e8503d in std::allocator_traits<std::allocator<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool> > >::construct<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >&> (__a=..., __p=0x5b4b1ade790, __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/alloc_traits.h:516
#7  0x0000555555e84da8 in std::_Sp_counted_ptr_inplace<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>, std::allocator<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool> >, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >&> (this=0x5b4b1ade780, __a=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:519
#8  0x0000555555e84b98 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>, std::allocator<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool> >, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >&> (this=0x7ffff02bca38, __p=@0x7ffff02bca30: 0x0, __a=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:651
#9  0x0000555555e84ae0 in std::__shared_ptr<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool> >, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >&> (this=0x7ffff02bca30, __tag=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1342
#10 0x0000555555e84a7d in std::shared_ptr<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool> >::shared_ptr<std::allocator<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool> >, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >&> (this=0x7ffff02bca30, __tag=..., __args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr.h:409
#11 0x0000555555e849e0 in std::allocate_shared<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>, std::allocator<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool> >, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >&> (__a=..., __args=...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr.h:862
#12 0x0000555555e6fb91 in std::make_shared<CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epeck> >&> (__args=...)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr.h:878
#13 0x000055555645013b in CGALHybridPolyhedron::convertToNef (this=0x5b4b00a55d0) at /home/hans/projects/openscad/src/geometry/cgal/CGALHybridPolyhedron.cc:412
#14 0x000055555644e349 in CGALHybridPolyhedron::nefPolyBinOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CGALHybridPolyhedron&, std::function<void (CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>&, CGAL::Nef_polyhedron_3<CGAL::Epeck, CGAL::SNC_indexed_items, bool>&)> const&) (this=0x5b4b00a7f90, 
    opName="nef difference", other=..., operation=...) at /home/hans/projects/openscad/src/geometry/cgal/CGALHybridPolyhedron.cc:317
#15 0x000055555644ec55 in CGALHybridPolyhedron::operator-= (this=0x5b4b00a7f90, other=...) at /home/hans/projects/openscad/src/geometry/cgal/CGALHybridPolyhedron.cc:175
#16 0x0000555555e66b89 in CGALUtils::applyOperator3DHybrid (children=std::__cxx11::list = {...}, op=OpenSCADOperator::DIFFERENCE)
    at /home/hans/projects/openscad/src/geometry/cgal/cgalutils-applyops-hybrid.cc:121
#17 0x0000555555e32f30 in CGALUtils::applyOperator3D (children=std::__cxx11::list = {...}, op=OpenSCADOperator::DIFFERENCE)
    at /home/hans/projects/openscad/src/geometry/cgal/cgalutils-applyops.cc:41
#18 0x0000555555bea51d in GeometryEvaluator::applyToChildren3D (this=0x7ffff02bdd78, node=..., op=OpenSCADOperator::DIFFERENCE)
    at /home/hans/projects/openscad/src/geometry/GeometryEvaluator.cc:164
#19 0x0000555555be99c3 in GeometryEvaluator::applyToChildren (this=0x7ffff02bdd78, node=..., op=OpenSCADOperator::DIFFERENCE)
    at /home/hans/projects/openscad/src/geometry/GeometryEvaluator.cc:106
#20 0x0000555555bed253 in GeometryEvaluator::visit (this=0x7ffff02bdd78, state=..., node=...) at /home/hans/projects/openscad/src/geometry/GeometryEvaluator.cc:654
#21 0x0000555555769c1c in BaseVisitable::acceptImpl<CsgOpNode> (state=..., node=..., visitor=...) at /home/hans/projects/openscad/src/core/BaseVisitable.h:30
#22 0x0000555555768e75 in CsgOpNode::accept (this=0x5b4f836c810, state=..., visitor=...) at /home/hans/projects/openscad/src/core/CsgOpNode.h:9
#23 0x00005555558e10b7 in NodeVisitor::traverse (this=0x7ffff02bdd78, node=..., state=...) at /home/hans/projects/openscad/src/core/NodeVisitor.cc:30
#24 0x00005555558e0f79 in NodeVisitor::traverse (this=0x7ffff02bdd78, node=..., state=...) at /home/hans/projects/openscad/src/core/NodeVisitor.cc:20
#25 0x00005555558e0f79 in NodeVisitor::traverse (this=0x7ffff02bdd78, node=..., state=...) at /home/hans/projects/openscad/src/core/NodeVisitor.cc:20
#26 0x00005555558e0f79 in NodeVisitor::traverse (this=0x7ffff02bdd78, node=..., state=...) at /home/hans/projects/openscad/src/core/NodeVisitor.cc:20
#27 0x00005555558e0f79 in NodeVisitor::traverse (this=0x7ffff02bdd78, node=..., state=...) at /home/hans/projects/openscad/src/core/NodeVisitor.cc:20
#28 0x0000555555be9117 in GeometryEvaluator::evaluateGeometry (this=0x7ffff02bdd78, node=..., allownef=true) at /home/hans/projects/openscad/src/geometry/GeometryEvaluator.cc:59
#29 0x00005555565a0732 in CGALWorker::work (this=0x5b4894152e0) at /home/hans/projects/openscad/src/gui/CGALWorker.cc:36
#30 0x000055555561afa3 in CGALWorker::qt_static_metacall (_o=0x5b4894152e0, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7ffff02bdfe0) at OpenSCAD_autogen/MXUWEOXILK/moc_CGALWorker.cpp:88
#31 0x00007ffff50737c8 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff4e4cc4e in QThread::started(QThread::QPrivateSignal) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff4e4ec89 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff48ddb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#35 0x00007ffff496fa00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
</details>

So, the behavior for CGAL errors is set such that it should throw an exception, which our code catches, thus avoiding a segfault.

From the command line output, it looks like this is happening, but then some further processing occurs which results in a crash.
Without digging into the source code yet, I am guessing that the exception handling part here is not properly cancelling the overall operation but attempting to continue working on this bad data.

**Comment by kintel** [comment] 2024-11-28 04:50
Closing as fast-csg has been deprecated

**Closed by kintel** 2024-11-28 04:50 UTC
Labels: Comp: Fast-CSG
