### ISSUE TITLE
Issues with small scale polygons due to resolution limit / clean-up when calling Clipper

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#999] opened 2014-10-30 18:59 UTC
Reported on the mailing list: http://forum.openscad.org/Performance-regression-2014-10-02-tp9989p9994.html

There is an anomaly with $fn, where increasing this value actually decreases it.

```
linear_extrude(height=1)
difference() {
    square([1,1]);
    translate([0.5, 0]) circle(r=0.25, $fn=300); // more coarse
    translate([1, 0.5]) circle(r=0.25, $fn=30);
}
```

Looks like this only happens for small values. With the same model scaled up 10 times, the issue does not occur.

![openscad-fn-issue](https://cloud.githubusercontent.com/assets/1330241/4849978/da7e4542-6065-11e4-996f-eba72d0d0bdd.png)
##

**Comment by dlaw** [comment] 2015-08-20 19:58
I am struggling to work around this issue. I use openscad to model keys for mechanical locks, which are relatively small and precise. It is natural to use units of inches for consistency with industry documentation. I take a Minkowski sum with a 0.029 inch radius circle with `$fn=360` or thereabouts. An error of 0.001 inches is significant.

I am happy to take a stab at providing a patch, but I would like to hear your thoughts about what the most elegant / correct solution would be. A flag to disable vertex cleanup for individual operations? Or a way to locally or globally alter the magic number 0.001 in src/clipper-utils.cc, a la `$fn` and friends?


More details, if you're interested:

I had to change my code from
```
  intersection() {
    minkowski() {
      circle(0.029, $fn = 360);
      polygon(...);
    }
    square(...);
  }
```
to
```
  scale(.001)
  intersection() {
    minkowski() {
      scale(1000)
      circle(0.029, $fn = 360);
      scale(1000)
      polygon(...);
    }
    scale(1000)
    square(...);
  }
```
which is tremendously inelegant.

Here are some photos showing the error introduced. Each display window is one inch wide.
![bad](https://cloud.githubusercontent.com/assets/606010/9393900/e9cfc5fa-4752-11e5-8ea0-2ce46b2a13a5.png)
![good](https://cloud.githubusercontent.com/assets/606010/9393901/e9d31d36-4752-11e5-9708-91483fdaa165.png)

**Comment by PraiseSatan** [comment] 2015-08-20 21:35
I would recommend either changing the implementation of $fs, so that is the minimum size used everywhere (and having an appropriate default), adding a new variable to do that just for this, or having it so the minimum value is defined as the minimum value the software can support and $fn is used properly without collapsing vertices.

**Comment by engblom** [comment] 2016-02-15 13:59
Currently when the cleanup function kicks in, it might make $fn=10 to have higher resolution than $fn=1000. This I think is a bug. 
I can understand some cleanup begins once you have points too close to each other, but why does it not remove just a few points until it is under that limit? In worst case almost all of the points will be gone.

In my case it went down from 1000 points to 8 when the cleanup begun.  This meant that even 10 points in the same area gave better resolution than 1000 (as no cleanup happened). In my case, the cleanup begun kicking in around 70 points, so the limit was much higher than the 8 points.

**Comment by t-paul** [comment] 2016-02-15 14:56
When using `polygon()` the cleanup issue is the same, but not related to `$fn` as it's not used for user generated points.
The root cause is the same though, as it's a parameter when calling the 2D library (Clipper).

**Comment by nophead** [comment] 2016-02-15 15:10
@kintel,
  When you said 
>The consequence of not doing this tends to be an explosion in processing time for subsequent operations.

Where are these close together vertices coming from? Any vertices in a polygon are there because the user put them there, so if they want to remove them to speed things up they can. Others presumably come from high values of $fn. Again this is what the user has demanded. I don't see any reason for removing any vertices except perhaps co-linear ones. Aren't all vertices directly or indirectly created by the user and if that makes it slow they have the choice of reducing them themselves? 

Presumably this is what happened when CGAL was doing the 2D stuff and there is nothing slower than CGAL. Are you saying the new 2D subsystem slows down more than CGAL did?

**Comment by doug-moen** [comment] 2016-02-15 15:34
@kintel said Before accepting results of 2D operations, we clean the results by removing vertices which are very close together, or which are collinear with neighbor vertices. This assumes that the modeling unit is relatively small (typically millimeters) and removes vertices which, when removed, causes an error less than 0.001 millimeters.

@dlaw said [For his model] An error of 0.001 inches is significant.

If introducing small errors is necessary for performance, then there should be a way to control the error tolerance for the cleanup operation. Something like Trygon's `$fe` error tolerance variable.

**Comment by t-paul** [comment] 2016-02-15 15:40
All `$fX` definitions, including `$fe` are based on a radius. How to apply that to polygons or bezier curves?

**Comment by nophead** [comment] 2016-02-15 15:47
But why does anything need "cleanup"? That implies something is generating spurious extra vertices, but what is it? As far as I can see the only vertices are those defined by the user's code, either explicitly or implicitly.

**Comment by t-paul** [comment] 2016-02-15 15:52
Right now I see only one place, but that is generic processing for the result polygons coming back from the Clipper library which does the 2D handling.
At this point it's currently not known where the data is coming from, a user defined `polygon()` or a complex CSG operation. As mentioned before, maybe it would be an option to clean-up relative to the bounding box instead of using absolute values. I can't judge if it would be ok to just remove the cleanup completely.

**Comment by nophead** [comment] 2016-02-15 16:05
But 2D boolean operations are deterministic, you should only get vertices where you expect them. The only exception is curve approximation in things like circle, text and offset with a radius, but they should be controlled by $fn and friends.

I can't say I have ever noticed any spurious 2D vertices that I didn't understand were a consequence of my code.

**Comment by doug-moen** [comment] 2016-02-15 16:28
`$fe` is not "based on a radius". It is an absolute linear measure of error
tolerance. `$fe` means that that the polygonal approximation to a surface
curve that OpenSCAD creates should not deviate more than `$fe` units from
the true mathematical curve. In the case of circular primitives, Trygon's
`$fe` implementation specifies "the maximum acceptable distance from the
centre of the facet to the true circular arc, measured normal to the facet".

`$fe` seems relevant to this discussion, since @dlaw mentioned an error
tolerance for his project (we know it is less than 0.001in), and since the
definition of "very close together" in the cleanup code could be recast in
terms of an error tolerance.

**Comment by t-paul** [comment] 2016-02-15 17:20
The forum post I've seen has `min(45,2*acos(1-$fe/r))` which is based on a given radius.

So when defining `$fe' more generally as "deviation from the true value", that still leaves the question of how to calculate for polygon or bezier input. In case of bezier curves, there is at least a definition of the "true" curve, for user specified or calculated polygons that's not available.

(Bezier is not directly related to this issue, but would make sense for `text()` and `trace()` which both generate conic/cubic bezier segments and would benefit from that too).

**Comment by doug-moen** [comment] 2016-02-15 20:14
Here's the `$fe` forum post: http://forum.openscad.org/fe-Tolerance-based-arc-approximation-td14212.html

`function fa(r)=($fn>0)?360/$fn:($fe>0)?($fe<r)?min(45,2*acos(1-$fe/r)):45:$fa;`

The `fa` function converts `$fe`, an absolute linear measure, to a `$fa` value, an angular measure. To convert a distance to an angle, you need the radius as an input parameter.

As for fixing the actual bug in the general case, I don't know for sure. Obviously we want to fix the reported problem where increasing `$fn` has the paradoxical effect of decreasing the resolution.

The cleanup code in ClipperUtils::toPolygon2d contains a hard coded constant 0.001, which is part of the problem. This value needs to be controlled by the model, not be hard coded. Assuming we want to fix the cleanup code, instead of just eliminating it, then...

In the original bug report for #999, there is
```
linear_extrude(height=1)
  difference() {
    square([1,1]);
    translate([0.5, 0]) circle(r=0.25, $fn=300); // more coarse
    translate([1, 0.5]) circle(r=0.25, $fn=30);
  }
```

Maybe we could associate an error tolerance with each 2D object (ClipperLib::PolyTree). The error tolerance for the above circles are computed from their $fn and radius. The two circles in this example have different error tolerances. The error tolerance for a difference is the minimum of the error tolerances of its children. When toPolygon2d() is called, it uses the error tolerance of its argument, rather than using a hard coded constant. I realize this requires a data structure change; sorry.

**Comment by engblom** [comment] 2016-02-16 06:10
What about having a variable to control if the cleanup function should run or not. That gives the possibility of fast prototyping, but still a chance to have a final good rendering. That would probably only require a very small change in the cleanup function making it returning the unmodified object if the variable is set.

I came from Blender to OpenSCAD because I wanted easier control over how the object I create would look like. Automatic cleanup takes away the control I hoped to be able to gain with OpenSCAD.

**Comment by doug-moen** [comment] 2016-02-16 17:53
Instead of a global variable, how about a module, 'simplify(t) shape', where t is an error tolerance. Using t=0 means no vertices are removed unless they are colinear with other vertices. This would provide finer control, and you could still turn the behaviour on and off using a global variable if you wanted to.

**Comment by kintel** [comment] 2016-02-17 16:56
I believe we added this cleanup mostly to handle the potentially large amount of vertices in 2D polygons as a result of a projection of a 3D object into the 2D plane. It is indeed an optimization - I _think_ the subsequent code should be stable enough to handle the larger amount of vertices. Using an error metric for such approximation sounds like a decent idea, i.e. a global $fe, a local $fe, or a separate simplification module.

Note that Clipper already uses a fixed point representation of vertices, so the vertices are quantized in any case.

**Comment by doug-moen** [comment] 2016-04-10 16:05
This bug is being reported fairly frequently in the forum.

As a quick fix, why don't we disable the optimization?

Later, if a more correct way of addressing the performance issue can be found, then we can apply it.

**Comment by kintel** [comment] 2016-04-10 20:09
@doug-moen It's worth trying as this is more than slightly annoying. We can perform some performance regression tests while at it.

**Comment by kwikius** [comment] 2016-07-20 17:17
I think I just hit this issue. I am generating aerofoil sections as polygons where the chord is normalised to 1, which is pretty standard for aerofoils. After a recent upgrade my aerofoils are losing most of their shape! I guess I can normalise them to some other value but, it seems like a strange optimisation. Perhaps the ability this optimisation on or off?

**Comment by nophead** [comment] 2016-07-21 19:17
It is a regression as older versions didn't do it and I don't remember anybody complaining about too many vertices so I strongly suggest it should just be removed.

**Comment by thehans** [comment] 2017-10-13 18:34
I think the best approach would be to minimize the effect of this polygon cleanup.

Currently the cleaning distance is set as follows:
https://github.com/openscad/openscad/blob/master/src/clipper-utils.cc#L58
```CLEANING_DISTANCE = 0.001 * CLIPPER_SCALE```

https://github.com/openscad/openscad/blob/master/src/clipper-utils.h#L8
```CLIPPER_SCALE = 1 << 16```

The default cleaning distance from clipper lib is basically the length of one diagonal (1.415):
http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Functions/CleanPolygons.htm

So CLEANING_DISTANCE = 65.536, and using the default will substitute that with 1.415, allowing for 
65.536/1.415 = about 46x improvement in resolution before cleanup starts altering your shapes.

**Comment by thehans** [comment] 2017-10-13 18:45
I guess I should also clarify that after looking at clipper's algorithm, I think there are flaws in its logic.  

As kintel mentioned in his first comment to this issue, 
> [Clipper] removes vertices which, when removed, causes an error less than 0.001 millimeters.

This sounds reasonable at first glance, but the problem is that it iteratively removes vertices and then compares the removal of subsequent vertices against this new altered path, not the original path.

This means that as you attempt to create higher and higher resolution, clipper destroys your shape more and more.  Say for example you draw a small circle with vertices so close that all of them are within the cleaning distance of their adjacent vertex, clipper will remove ALL of the vertices!

So my proposed change above is a bit of a band-aid but I think it will significantly reduce the occurences of people complaining about OpenSCAD screwing up their shapes.

**Comment by kintel** [comment] 2017-12-27 06:21
Fixed by #2123

**Closed by kintel** 2017-12-27 06:21 UTC

**Comment by nathanielvirgo** [comment] 2018-09-04 12:59
Although apparently fixed, this bug/feature should be documented, since the current release still has it. I just came across it in the context of trying to project a complex part that is not tiny but has curved surfaces, and it took me ages to work out what was going on.

Is there a workaround? I tried scaling up to a much bigger size, then doing the projection, then extruding it, then scaling back down, but this had no effect.

**Comment by thehans** [comment] 2018-09-05 16:32
@nathanielvirgo If you can provide a concise test case that fails on recent dev snapshot, and post it to github, it would greatly help to troubleshoot the issue you are seeing.  

Scaling up, doing 2d related operations, then scaling back down should also alleviate this class of problem, so I'm thinking the issue you are encountering may be unrelated or some newly discovered issue.  Hard to say without a reproducible test case. 

The fix for this was basically to just change the scale at which clipper considers vertices removable, but if very very small/subtle features are used then it is possible that it could still cause issues.

The core of this issue actually lies with the way that clipper performs its cleanup operation, and should ideally be reported and tracked with the clipper project.  However I don't believe an issue tracker exists for the original library, and I don't think any new development is being done for it.   We may still be able to patch some fix to clipper's algorithm, I suspect a proper solution will come at the cost of ~2x slowdown/memory consumption for the clipper cleanup operation, requiring a full copy of the original path to compare against (probably not a big deal since clipper is already pretty efficient).

**Comment by thehans** [comment] 2018-09-05 16:37
Actually, I was mistaken, and there is a bug tracker( https://sourceforge.net/p/polyclipping/bugs/ ), I just didn't see a link to it directly from the project homepage ( http://www.angusj.com/delphi/clipper.php )
