### ISSUE TITLE
Edges preview and render jaggedly in Orthogonal View

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#1483] opened 2015-11-13 05:56 UTC
Edges are rendered jaggedly with triangles of the wrong shaded color showing through presumably from the faces behind them?   

This is more apparent with a view that is somewhat zoomed in.

Runnning this script in the gui, and clicking "View All"
`cube(0.1,center=true);`

produces these images:
preview
![screenshot from 2015-11-12 23 45 16](https://cloud.githubusercontent.com/assets/252233/11139707/5ebd13c2-8998-11e5-9c17-9161f3824556.png)

render
![screenshot from 2015-11-12 23 45 23](https://cloud.githubusercontent.com/assets/252233/11139708/5ebd15b6-8998-11e5-9e14-839e21c82546.png)

This is on Linux Mint 17.2
Openscad 2015.03
NVIDIA Corporation GT216GLM [Quadro FX 880M] (rev a2)

**Comment by kintel** [comment] 2015-11-13 06:01
This is z buffer tearing and is caused by z-buffer floating point inaccuracy.
We could fix this by modifying our front/back clipping planes in real-time based on the projected bounding box of the design. I think we currently don't, so very small objects are likely to tear like this.
As usual, such issues tend to be put on the back burner until we rewrite the rendering code: https://github.com/openscad/openscad/wiki/Project%3A-Improve-OpenGL-rendering

**Comment by thehans** [comment] 2015-11-13 06:09
I noticed this doesn't happen on my Windows machine, is it just down to difference in graphics card hardware or something else?

I could render a cube all the way down to cube(0.00000000000000000001, center=true);
and the edges looked perfect.

**Comment by thehans** [comment] 2015-11-13 06:32
Also, not sure if this is helpful, but I tried smaller and smaller cubes on my linux machine.  Around size 0.002 or smaller, the edges all render perfectly smoothly, its just that the entire object is inside out now.
`cube(0.001,center=true);`

![screenshot from 2015-11-13 00 27 47](https://cloud.githubusercontent.com/assets/252233/11140217/bd080a7c-899d-11e5-9fef-113b9367d692.png)

**Comment by thehans** [comment] 2015-11-13 07:04
Also, whatever is used to render when -o flag is called, does not exhibit this issue.

**Comment by thehans** [comment] 2015-11-13 10:12
OK I realize now that I had been viewing in Ortho mode.  There is no difference between the windows and linux versions as I previsouly though, my  linux openscad just happened to have ortho turned on.

**Comment by kintel** [comment] 2015-11-13 17:00
@thehans oh, good catch :)

**Comment by kintel** [comment] 2015-11-13 17:05
Fixed by #1484

**Closed by kintel** 2015-11-13 17:05 UTC
Labels: Rendering
