### ISSUE TITLE
Incorrect polyhedron causes segmentation fault

### ISSUE THREAD

**Issue by sschroe** [openscad/openscad#2616] opened 2018-12-01 15:26 UTC
With the current master i get a segmentation fault when trying to render the following file with an incorrect polyhedron:

```
cube(1);

polyhedron(
       points=[[3, 0, 0],
               [5, 0, 0],
               [8, 6, 0],
               [0, 6, 0],

               [3, 0, 2],
               [5, 0, 2],
               [8, 6, 3],
               [0, 6, 3]],

       faces=[ [0, 1, 2, 3],
               [0, 4, 5, 1],
               [1, 2, 6, 5],
               [3, 0, 4, 7],
               [2, 3, 7, 6],
               [4, 5, 6, 7]]
);
```
This polyhedron contains several incorrect faces that are backwards. With the 2015 release (and also older library versions) openscad does not crash but the polyhedron simply does not show up in the render (which is expected). I also checked an commit from around August and the crash seemed to exist there as well so it does not seem to be an very recent issue.

#2464 seems to report a very similar crash.

A debug build on commit 1270e5a6b5b with gdb yields the following:
```
#0  0x00005555557b057e in CGAL::HalfedgeDS_halfedge_base_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> >::opposite() (this=0x0) at /usr/include/CGAL/HalfedgeDS_halfedge_base.h:56
#1  0x00005555559665c4 in CGAL::opposite<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::allocator<int> >(boost::graph_traits<CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::allocator<int> > >::halfedge_descriptor, CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::allocator<int> > const&) (h=...) at /usr/include/CGAL/boost/graph/graph_traits_Polyhedron_3.h:367
#2  0x000055555595d75b in CGAL::polygon_mesh_to_nef_3<CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::allocator<int> >, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > > > > >, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > > > >(CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::allocator<int> >&, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>&, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > > > > >, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > > >) (P=..., S=..., fimap=..., himap=...) at /usr/include/CGAL/Nef_3/polygon_mesh_to_nef_3.h:232
#3  0x0000555555956c81 in CGAL::polyhedron_3_to_nef_3<CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::allocator<int> >, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> >(CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::allocator<int> >&, CGAL::SNC_structure<CGAL::Cartesian<CGAL::G
```

Version details:
```
OpenSCAD Version: 2018.12.01
System information: Linux 4.18.0-19.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 4.18-23.1~sid (2018-11-16) x86_64 Debian GNU/Linux buster/sid 4 CPUs 15.62 GB RAM
Compiler: GCC "8.2.0" 64bit
Boost version: 1_62
Eigen version: 3.3.5
CGAL version, kernels: 4.13, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.11.2
QScintilla version: 2.10.4
InputDrivers: 
MingW build: No
GLib version: 2.58.1
lodepng version: 20180910
libzip version: 1.1.2
fontconfig version: 2.13.1
freetype version: 2.9.1
harfbuzz version: 2.1.1
lib3mf version: (not enabled)
Application Path: /home/envil/Source/openscad
Documents Path: /home/envil/.local/share
Resource Path: /home/envil/Source/openscad
User Library Path: /home/envil/.local/share/OpenSCAD/libraries
User Config Path: /home/envil/.config/OpenSCAD
Backup Path: /home/envil/.local/share/OpenSCAD/backups
OPENSCADPATH: 
OpenSCAD library path:
/home/envil/.local/share/OpenSCAD/libraries
/home/envil/Source/openscad/libraries
```

**Comment by t-paul** [comment] 2018-12-01 15:36
Probably duplicate of #2464.

**Comment by t-paul** [comment] 2018-12-04 17:32
Yes, looking at the stack trace this is the same issue... copying over the example. Thanks for the small test case.

**Closed by t-paul** 2018-12-04 17:32 UTC
Labels: Crash
