### ISSUE TITLE
Openscad 2021.01-x86_64 AppImage crashes on Linux Mint 20 when opening or saving a file

### ISSUE THREAD

**Issue by DaniAngel** [openscad/openscad#3712] opened 2021-03-08 06:08 UTC
Greetings,
I am using Linux Mint 20 to run the OpenSCAD2021.01-x86_64.appimage.  It opens up to the welcome screen where clicking "open"  results in the program crashing and window disappearing. If I hit "new" from the welcome screen, I can type code into the editor and get it to preview.  I cannot save, as it results in the same behaviour as trying to "open" a file. My 2019.05 version seems to work okay....

Any help would be appreciated.  What other info do you need?

Dani

**Comment by t-paul** [comment] 2021-03-08 09:37
Duplicate of  #3523, no solution yet, but some workarounds listed in that issue.

**Closed by t-paul** 2021-03-08 09:37 UTC

**Comment by DaniAngel** [comment] 2021-03-08 10:01
Thank you!
