### ISSUE TITLE
Add CONTRIBUTING file

### ISSUE THREAD

**Issue by keikoro** [openscad/openscad#4418] opened 2022-11-14 19:44 UTC
It would be helpful if the repository included a [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file to let people know what kinds of contributions are welcome/needed and what the requirements for PRs are (could be anything from code formatting rules to inclusion of tests/docs to collaborative Git usage).

GitHub displays the contents of this file to users when they open new PRs, which helps catch problems with contributions/reduce admin workload.

**Comment by thehans** [comment] 2022-11-14 20:00
Duplicate of #2364

**Closed by thehans** 2022-11-14 20:00 UTC
