### ISSUE TITLE
Where is the projection?

### ISSUE THREAD

**Issue by RonaldoCMP** [openscad/openscad#2063] opened 2017-07-02 15:06 UTC
```
epsilon = 0.001;
projection() cube([epsilon,10,10]);
```

This projection is void; however

```
epsilon = 0.001;
square([epsilon,10]);
```

is not.

**Comment by PRouzeau** [comment] 2017-07-02 18:24
cube vector is [x,y,z]
projection is done in z on plane x,y, so you are projecting a very thin line.
Projection have no thickness, while 2D primitives have a thickness of 1. Projections are for drawing export.
Square z default to 1, so you see it, but if you project it, you don't see more than on your first example

**Comment by RonaldoCMP** [comment] 2017-07-02 19:06
I am projecting to a very narrow rectangle to be precise.

Preview of 2D polygons seems to have a thickness of 1 (and this is a debatable topic ) but its render()ization has no thickness. The operator projection() generates a 2D polygon like any other and it has no thickness. 

Note that everything would be fine if epsilon was set greater than 0.001.

**Comment by thehans** [comment] 2017-07-02 20:19
Probably related to this issue:  https://github.com/openscad/openscad/issues/999

You can work around the issue with something like this:

```
epsilon = 0.001;
scaleAdjust = 100;

scale(1/scaleAdjust) 
  projection() cube(scaleAdjust*[epsilon,10,10]);
```

**Comment by RonaldoCMP** [comment] 2017-07-04 13:51
It seems to be.

The work around I have adopted is:

epsilon = 0.001;
scale([epsilon,1]) projection() cube([epsilon,10,10]);


2017-07-02 17:19 GMT-03:00 Hans L <notifications@github.com>:

**Comment by kintel** [comment] 2017-09-09 21:56
Closing as duplicate of #999.
@RonaldoCMP Feel free to add your test as a comment to #999 and we'll pick that up eventually

**Closed by kintel** 2017-09-09 21:56 UTC
