### ISSUE TITLE
Blank screen error.

### ISSUE THREAD

**Issue by 44knight44** [openscad/openscad#3885] opened 2021-09-16 06:59 UTC
I am using OpenSCAD version 2021.09.09.ci8596 (git 227325893) . When I right click the view screen around the middle the window turns black. I found this error by accident. Lucky the menu still works so I can save my work. Just to let you know what I found.

**Comment by nophead** [comment] 2021-09-16 07:24
Yes I get the same problem on Win7 64. I have to quit and start again each time I accidentally right click when dragging.

Right click shows the call stack that drew the pixel you clicked on but it has broken after the last release. If I resize the black window I get a broken view drawn in it when it is repainted.

![image](https://user-images.githubusercontent.com/566149/133568414-b0aef300-2eb1-4676-a0fa-60534c980b17.png)

**Comment by nophead** [comment] 2021-09-21 09:47
Interestingly if I do copy viewport image the result is correct.  It seems that the windows are drawn correctly but displayed with a black mask over the top with transparent holes in it. In the holes the window contents are shown correctly and menus are drawn correctly over the top.

**Comment by MichaelAtOz** [comment] 2021-09-21 11:48
It may be unrelated, but I have been unable to run snapshots for a long while, #3719 with windows display issues, WITH S/W RENDERING. But I suspect it points to some underlying problem.

**Comment by PRouzeau** [comment] 2021-09-30 18:52
See also  #3725

**Comment by t-paul** [comment] 2021-09-30 18:55
Thanks, this is indeed a duplicate of  #3725.

**Closed by t-paul** 2021-09-30 18:55 UTC
Labels: Type: Bug
