### ISSUE TITLE
crashes when polyhedron has a collapsed face

### ISSUE THREAD

**Issue by mrvn** [openscad/openscad#1448] opened 2015-10-05 12:19 UTC
I've build a polyhedron shaped like a cube with one side smaller than the opposite side. The size is parametric depending on the size of the surrounding structure.

Now to do a print test I scaled down my object to the point where the smaller side of the polyhedron became a line instead of a rectangle. Effectively the whole thing became a 3 sided prism. I'm guessing that does bad things to calculating the normals and triangulation and openscad crashed.

**Comment by TakeItAndRun** [comment] 2015-10-05 21:27
Would you mind shareing your code?

2015-10-05 14:19 GMT+02:00 Goswin von Brederlow <notifications@github.com>:

**Comment by mrvn** [comment] 2015-10-06 08:43
w = 1; // crash with w = 0

    polyhedron(
        points=[[0,     0, 0],
                [1,     1, 0],
                [1 + w, 1, 0],
                [2 + w, 0, 0],
                [0,     0, 1],
                [1,     1, 1],
                [1 + w, 1, 1],
                [2 + w, 0, 1]],
        faces=[[0, 3, 2, 1],
               [0, 1, 5, 4],
               [1, 2, 6, 5],
               [2, 3, 7, 6],
               [3, 0, 4, 7],
               [4, 5, 6, 7]]);

**Comment by kintel** [comment] 2015-10-06 13:43
Duplicate of #1325 - fixed in master

**Closed by kintel** 2015-10-06 13:43 UTC
