### ISSUE TITLE
Crash when using mirror and using difference inside translate

### ISSUE THREAD

**Issue by cocsackie** [openscad/openscad#2189] opened 2017-11-09 01:10 UTC
When working on a model I encountered crash. I managed to simplify it as much as it can be:

```
mirror([1,0,0]) union() {
    difference() {
        cube([60, 35, 14]);
        translate([0,31,0]) cube([45,3,3]);
    }
    
    translate([0,31,3]) {
        difference() {
            rotate([0,90,0]) cylinder(h=45, r=3);
            translate([0,-3,0]) cube([45,3,3]);
        }
    }
}
```

I cannot tell what this script is doing, but I hope its simple enough that you can debug it.

**What can be done, so that there will be no crash:**

- Removing mirroring
- Changing hierarchy so that `translate([0,31,3])` is inside `difference()` (other way around than it is now)
- Removing any line within difference (with or without removing difference itself)

**What still crashes:**

- Union replaced with module is crashing as well

This happend under Windows 7 (x64) on OpenSCAD 2015.03 as well as OpenSCAD 2017.01.20 commit 59df0d1

**Comment by kintel** [comment] 2017-11-09 01:19
Could you paste the result of Help->Library Info->Details for `OpenSCAD 2017.01.20`?

**Comment by kintel** [comment] 2017-11-09 01:19
My first hunch is that this is a duplicate of #1655

**Comment by cocsackie** [comment] 2017-11-09 01:30
Maybe it is duplicate, but I encountered the problem in stable version, and tried Development Snapshots and the bug occurs as well. Even if it's a bug in other artifact, the problem still exists here and by reading #1655 it was solved there. Then why newer version of that artifact isn't used?

```
OpenSCAD Version: 2017.01.20 (git 59df0d1)
System information: Windows(TM) 6.1 SP 1.0 NTW 1 MSDN 724833 8 CPUs 7.98 GB RAM
Compiler: GCC "4.9.4" 64bit
Boost version: 1_60
Eigen version: 3.2.5
CGAL version, kernels: 4.6.3, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.7.0
QScintilla version: 2.8.4
MingW build: MingW64
GLib version: 2.44.1
libzip version: 
Application Path: C:/DOCUMENTS/openscad/openscad-2017.01.20
Documents Path: C:\Users\admin\Documents
Resource Path: C:/DOCUMENTS/openscad/openscad-2017.01.20
User Library Path: C:/Users/admin/Documents/OpenSCAD/libraries
User Config Path: C:\Users\admin\AppData\Local/OpenSCAD
Backup Path: C:/Users/admin/Documents/OpenSCAD/backups
OPENSCADPATH: 
OpenSCAD library path:
C:/Users/admin/Documents/OpenSCAD/libraries
C:/DOCUMENTS/openscad/openscad-2017.01.20\libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 1.12.0
OpenGL Version: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
GL Renderer: AMD Radeon HD 6900 Series
GL Vendor: ATI Technologies Inc.
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QGLWidgetGL Extensions:
GL_AMDX_debug_output
GL_AMDX_vertex_shader_tessellator
GL_AMD_blend_minmax_factor
GL_AMD_conservative_depth
GL_AMD_debug_output
GL_AMD_depth_clamp_separate
GL_AMD_draw_buffers_blend
GL_AMD_framebuffer_sample_positions
GL_AMD_multi_draw_indirect
GL_AMD_name_gen_delete
GL_AMD_performance_monitor
GL_AMD_pinned_memory
GL_AMD_query_buffer_object
GL_AMD_sample_positions
GL_AMD_seamless_cubemap_per_texture
GL_AMD_shader_atomic_counter_ops
GL_AMD_shader_stencil_export
GL_AMD_shader_trace
GL_AMD_texture_cube_map_array
GL_AMD_texture_texture4
GL_AMD_transform_feedback3_lines_triangles
GL_AMD_vertex_shader_layer
GL_AMD_vertex_shader_tessellator
GL_AMD_vertex_shader_viewport_index
GL_ARB_ES2_compatibility
GL_ARB_ES3_1_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_direct_state_access
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_imaging
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counters
GL_ARB_shader_bit_encoding
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_stencil_export
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_shadow_ambient
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_snorm
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_draw_buffers
GL_ATI_envmap_bumpmap
GL_ATI_fragment_shader
GL_ATI_separate_stencil
GL_ATI_texture_compression_3dc
GL_ATI_texture_env_combine3
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_bindable_uniform
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_copy_buffer
GL_EXT_copy_texture
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_histogram
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset_clamp
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_specular_color
GL_EXT_shader_image_load_store
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_stencil_wrap
GL_EXT_subtexture
GL_EXT_texgen_reflection
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_bptc
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_object
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_EXT_vertex_attrib_64bit
GL_IBM_texture_mirrored_repeat
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_KTX_buffer_region
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_copy_depth_to_color
GL_NV_copy_image
GL_NV_depth_buffer_float
GL_NV_explicit_multisample
GL_NV_float_buffer
GL_NV_half_float
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_OES_EGL_image
GL_SGIS_generate_mipmap
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays
GL_WIN_swap_hint
WGL_EXT_swap_control
```

**Comment by kintel** [comment] 2017-11-09 01:40
#1655 was a bug in a 3rd party library - we had to wait until the fix was made available.
If you go to http://files.openscad.org/snapshots/, you can pick one of the later experimental Windows build. The main website hasn't been updated yet; we should probably do that.

**Comment by cocsackie** [comment] 2017-11-09 01:55
I downloaded OpenSCAD-2017.08.30-x86-64.zip, and it is not crashing. I was certain though, that the version from the website (developer snapshots) was the newest available.

**Comment by kintel** [comment] 2017-11-09 01:56
thx - we'll rebuild a new Windows version and update the website.

**Comment by kintel** [comment] 2017-11-09 01:56
Closing as duplicate of #1655

**Closed by kintel** 2017-11-09 01:56 UTC

**Comment by cocsackie** [comment] 2017-11-09 02:57
@kintel Sorry to address this again, but there still seems to be a problem, this is not a crash though. I opened the simplified model in the newest version of openscad and there was no crash. I returned to my original model and in console a CGAL error appeared.

Still using OpenSCAD-2017.08.30-x86-64.zip.

It seems to be more related to CGAL itself than openscad, but I am not aware of internals of openscad nor CGAL's, so I can't really tell. I hope if that is the case, that someone with knowledge of CGAL will be able to point the problem to CGAL developers.

Simplified again (similar to previous code):
```
module part() {
    difference() {
        cube([60, 35, 14]);
        translate([0,31,0]) cube([45,3,3]);
    }

    translate([0,31,3]) {
        difference() {
            rotate([0,90,0]) cylinder(h=45, r=3);
            translate([0,-3,0]) cube([45,3,3]);
        }
    }
}

part();
mirror([1,0,0]) part();
```

The error (above code):
```
ERROR: CGAL error in CGALUtils::applyBinaryOperator union: CGAL ERROR: assertion violation! Expr: itl != it->second.end() File: /opt/mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Nef_3/SNC_external_structure.h Line: 1152
```

PS
Wasn't really sure if I should open a new issue or not... but the code above is very similar to previous one...

PS2
I am aware that this is developer snapshot version of openscad... though I am curios - why there was no stable build for a long time? or is it just because the Linux is primarily supported?

**Comment by kintel** [comment] 2017-11-09 03:04
PS We release simultaneously for all platforms, we just haven't gotten around to making a stable release in a while.

**Comment by cocsackie** [comment] 2017-11-09 03:46
Well, thank you for a quick answer.

I understand that current implementation or used libraries might have limitations which cause that workarounds are needed, but because error occurs instead of informing a user, that at this stage this program doesn't support this is causing confusion. Especially, that FAQ does mention only that coincident surfaces are going to make preview flicker (which can be easily be seen without any errors in CGAL console output occuring). AFAIK rendering is different from preview and works without flickering in those cases.

When there is an error in the source code, the user is notified, that he or she made a mistake. But in this case we get an error and there is no way to tell if it is user's fault and it even suggests that something that was not predicted occured (it's an assertion failure).

I suggest you consider this not only as a bug, but as an improvement potential as well.
Even if this is not possible to be done by openscad contributors, maybe you could persuade CGAL contributors to support it, so openscad could benefit from it.

**Comment by kintel** [comment] 2017-11-09 03:49
There's significant work to be done in this domain. For a taste, see https://github.com/openscad/openscad/labels/CGAL

Help is always welcome if you're interested in contributing towards improving  code, error messages, documentation, communication with CGAL staff etc.
