### ISSUE TITLE
OpenSCAD does not support import of DXF files with POLYLINE

### ISSUE THREAD

**Issue by KeithSloan** [openscad/openscad#2060] opened 2017-06-13 12:18 UTC
FreeCAD tries to support minkowski requests by calling OpenSCAD. But with 2D objects that are polygons the import fails 

> tmp/fc-02618-424920-000002.dxf". 
WARNING: Unsupported DXF Entity 'POLYLINE' (1) in "../../tmp/fc-02618-424920-000002.dxf". 

Openscad request 

> minkowski(){import(file = "/tmp/fc-02618-424919-000001.dxf"); import(file = "/tmp/fc-02618-424920-000002.dxf");}

[files.zip](https://github.com/openscad/openscad/files/1071305/files.zip)

**Comment by t-paul** [comment] 2017-06-13 17:29
Duplicate of #1307.

**Closed by t-paul** 2017-06-13 17:29 UTC
