### ISSUE TITLE
Model corrupted with repeated translate (larger translation = more corruption)

### ISSUE THREAD

**Issue by blb75** [openscad/openscad#5263] opened 2024-08-19 21:54 UTC
**Describe the bug**
I have a complex shape (tree structure) that is made with pairwise hulls (not sure if relevant but I couldn't reproduce this error with just a sphere).

I've attached an STL of it to make a minimal example that fails for debugging purposes, but please note that the issue occurs whether it is loaded from STL or from its native module.

**To Reproduce**
Repeat the STL with a translation. The larger the translation, the fewer repeats needed to create the corruption.
Even with many repeats, if the translation is small, the model remains as expected.
Even with a single repeat, if the translation is large, the model is corrupted.

**Expected behavior**
The model fidelity is independent of the translation magnitude.

**Code reproducing the issue**
//This will fail:
for (it_repeat=[0:1])
{
translate([100000*it_repeat,0,0])
    import("minimal_fail.stl");
}

//This will not, if it is alone (above code is commented out)
//If both for loops are run, this will also fail (whether this is run first or second)
for (it_repeat=[0:10])
{
translate([10*it_repeat,0,0])
    import("minimal_fail.stl");
    }

**Screenshots**
Base model
<img width="936" alt="image" src="https://github.com/user-attachments/assets/62a2dabc-0a71-46aa-82c4-e6a9e0591db8">
Many small translation repeats
<img width="799" alt="image" src="https://github.com/user-attachments/assets/68fc418c-5d30-4648-b44c-3cb4183db9bc">
One large translation repeat
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/57343adf-2572-43e9-aa91-47ba76937766">
[minimal_fail.stl.zip](https://github.com/user-attachments/files/16665645/minimal_fail.stl.zip)

**Environment and Version info (please complete the following information):**
 - OS: macOS 13.6.7
 - System: Intel Mac
 - OpenSCAD Version 2024.08.11

Thank you!

**Comment by UBaer21** [comment] 2024-08-19 22:31
can't reproduce on windows

**Comment by thehans** [comment] 2024-08-19 22:58
I can reproduce on Linux, with manifold enabled.  
I was expecting the far away model to show more degradation, but surprisingly the origin-centered one is most affected.  (There is some artifact on the far object, but much less pronounced).
![issue5263](https://github.com/user-attachments/assets/5a128624-b910-4e32-b034-00a3641ea619)

As far as I know, its an issue of precision, where the model coordinate values are converted to 32-bit float for manifold and this causes problems when combined with large absolute coordinates.

I think there is a possibility of manifold supporting 64bit float in the future which would alleviate this.

Seems like a duplicate of #4871

**Closed by thehans** 2024-08-19 22:58 UTC
Labels: Type: Bug

**Comment by pca006132** [comment] 2024-08-20 01:01
Not that far in the future: https://github.com/elalish/manifold/pull/895

Do note that this is not really about repeated translates, I think if you do many small translates with the same resulting translation as the large translates, they should have similar effect.

There is also another way to alleviate this with lower precision, by normalizing each object (scale and translate to [-1, 1]) and maintain this normalization parameters. Probably not worth it though as we are switching to double precision.
