### ISSUE TITLE
Multi-threaded Geometry rendering [$1,275]

### ISSUE THREAD

**Issue by achiestdragon** [openscad/openscad#391] opened 2013-06-04 12:40 UTC
add multiple processor threading support to the compile and render
so that it can run 100% on all available cores/ht threads on the system rather than just the one ?
##

**Comment by kintel** [comment] 2016-11-08 02:58
Update: Looks like CGAL is aiming to include better thread safeness in CGAL 4.10: https://github.com/CGAL/cgal/pull/648

**Comment by thure** [comment] 2016-11-19 21:51
Glad to see this is still making progress!

**Comment by qharley** [comment] 2016-11-20 07:20
So am I. My projects are reaching complexity that cannot render any more,
even if I split it up in components. I was forced to learn OnShape to
complete a recent project.

I miss my OpenScad

**Comment by Lenbok** [comment] 2020-06-17 05:37
I just got an email from BountySource that any bounties posted more than two years ago are going to be gobbled up by them. It would suck if most of the bounties on this evaporated - we have two potential solutions in progress.

**Comment by MichaelAtOz** [comment] 2020-06-17 06:55
@Lenbok could you please forward that to oz.at.michael at gmail.com
If necessary we can claim the bounty and repost it.

**Comment by MichaelAtOz** [comment] 2020-06-17 07:30
@Lenbok strike that, found it in my inbox too.

**Comment by gingerbeardman** [comment] 2020-08-07 17:02
Just upgraded to 6-core system, and this is more noticeably lacking than it was on my old 2-core system.

+1

**Comment by mrwm** [comment] 2020-09-13 05:23
Hi guys, I'd like to add to the bounty. Should I add it to this issue or should I post it to #2405 on bountysource?

**Comment by MichaelAtOz** [comment] 2020-09-13 06:02
@mrwm You would add it to this issue. If you really want to, the size of the bounty doesn't correlate with people with the right skills being motivated.

**Comment by mrwm** [comment] 2020-09-13 23:55
I was just making sure where to post the bounty as I read Lenbok's comment concerning bountysource nulling the funds. Anyways, bounty added and thanks for this awesome software!

**Comment by Corallus-Caninus** [comment] 2021-03-12 23:29
Has Clang/Clang++ with Polly optimization in the LLVM been considered for this?

**Comment by Naegolus** [comment] 2022-05-04 17:30
Cool challenge

**Comment by parvit** [comment] 2022-06-18 23:22
Hi everyone, i've looked at this issue and i think i could work on it but before taking it on i would like to have some points clarified.

I don't see it feasible to parallelize directly the low-level CGAL geometry generation routines as it would imply a complete rewrite.

What instead i see possible after a bit of profiling is to parallelize the `CGALUtils::apply*3D` family of methods as they pretty much repeatedly apply the same operation on a set of Geometries.

Now with that said, my main question: 
If i were to modify those methods such as that instead of applying an operation on the entire set, worker threads would work on a subset of that initial set and then combine the sub-results at the end on the main thread, _would it change the final result_?

My reasoning would be that it should not change the result, but if i'm wrong then i don't see any point of attack for this at the current state so i would not work on it.

**Comment by jkavalik** [comment] 2022-06-19 07:48
@parvit one way to test it would be to try changing the order they are processed now (reverse, random) and compare results. IMHO there should not be a shared state and so the order should not matter but I have no idea if that's true in reality.

**Comment by t-paul** [comment] 2022-06-19 16:52
@parvit I'm not sure it's the best approach trying to parallelize the "old" NEF operations. The recent work on using the newer corefinement mesh operations (called fast-csg in the nightly builds) seems much more promising.

As for the geometry operations in general, the results *should* be the same handling the CSG tree according to the defined operations. Of course in the real world there could be differences, e.g. due to floating point precision and such, but that's already the case without multi-threading so I suppose that's something that needs to be accepted or mitigated by designing defensivly (like making sure unioned geometry overlaps).

**Comment by parvit** [comment] 2022-06-19 17:23
@t-paul Thank you for the response, the point i was trying to make is that i was planning to optimize/parallelize the methods _that execute_ the operations on the geometries. 

In fact it would not matter what kind of operation you were doing, it would just be equally distributed among the cores, boosting the cpu utilization of the available the cores which was what the request i understood from the original post.

If instead you are asking that the change be to optimize the _operations themselves_ then:
1. I would not recommend it as it would most probably _slow down_ the execution via the overhead of creating many threads for cheap operations repeated many times
2. The only viable solution would be to port all the operations to a GPU-accelerated environment (eg. opencl) to leverage a much more efficient way to do these calculations

Please clarify the intent and scope of the request so i can evaluate the next steps.

**Comment by gingerbeardman** [comment] 2022-06-20 08:41
I recently moved to M1 Mac and somehow (magic) this is much more performant with my rendering. 

Previous runtime: 29 minutes
M1 runtime: 9 minutes

Might be useful information for anybody wondering if they should upgrade!

**Comment by parvit** [comment] 2022-07-05 19:58
Hi all,
i've continued to develop the original proposal as i've not received feedback to the contrary.

Please review and test my PR at #4293.

**Comment by parvit** [comment] 2022-07-09 17:00
Hello, if i can help in speeding up the review process with some specific tests you would want to run please let me know.

**Comment by jkavalik** [comment] 2022-07-09 19:01
@parvit Hello, I am interested in this feature so I tried to compile and test it. My setup is a bit non-standard, using cygwin on windows to build the cross-compiler. It took quite some time and couple ad-hoc patches but I got it built and it seems to work most of the time.
But I have a problem with the Minkowski operator - it does not work at all when multicore-ops is enabled and fast-csg is disabled - tested on a simple example - without fast-csg I get empty results, with fast-csg it works fine. Unfortunately my "real-world" example does not work even with fast-csg enabled - without it I get only non-minkowski parts, with it totally empty results (in render, but there is something butchered in preview). It works with fast-csg _without_ multicore-ops so there is something else fishy there than just requiring fast-csg.

The "simple example" is just
```
minkowski() {
    cube(5);
    sphere(3, $fn=32);
}
```
The more complex (simplified a bit)

```
module poly_path4908(h)
{
  scale([25.4/90, -25.4/90, 1]) union()
  {
    difference()
    {
       linear_extrude(height=h)
         polygon([[-0.576956,-141.710680],[65.826271,105.991064],[-92.302387,38.769408],[-94.083058,25.697896],[-6.192129,-141.673840],[-0.576956,-141.710680]]);
       %translate([0, 0, -1])
         linear_extrude(height=2*h-1)
           polygon([[1.004164,-96.101480],[-2.406364,-95.597938],[-30.851865,-27.733386],[-31.673768,-18.409445],[7.543206,96.612489],[10.707107,94.294165],[16.714273,-84.641997],[1.004164,-96.101480],[1.004164,-96.101480]]);
    }
  }
}


module shape(h){ poly_path4908(h);

}

module fullVolume () {
minkowski(){
    shape(0.001);
    union(){
       cylinder(r=1,h=10);
       cylinder(h = 10, r1=5,r2=1);
    }}
}


difference(){
    fullVolume();
    translate([0,0,(-10)]) shape(30);
}

```
It even changes the preview results in a weird way by removing the % on line 11 - with it the "internal" shape is shown as gray preview and otherwise valid minkowski result can be seen (but not rendered), without it the second operand in minkovski (a cone) is shown instead.

**Comment by parvit** [comment] 2022-07-09 22:33
@jkavalik Thank you for the support i'll see to understand if there's some issue your script is triggering (it seemed fine with my local tests).

**Comment by parvit** [comment] 2022-07-09 23:44
It seems that the fix was easier than i expected, for some reason i put a condition on the minkowsky operation which was unwarranted.
Included also is the change in behavior for the subtraction i've mentioned previously.

@jkavalik 
Here's the results of the two scripts you provided (i've tried with fast-csg option on and off), i think the result is correct now:
![result_script_1](https://user-images.githubusercontent.com/93098480/178125924-40cbdfda-8006-49ef-bfa0-5175e3b1d17b.png)
![result_script_2](https://user-images.githubusercontent.com/93098480/178125925-c381f765-48e6-4099-b6cd-12148525fd28.png)

**Comment by jkavalik** [comment] 2022-07-10 08:35
@parvit Great, works now! :)
From my short testing, the parallelization helps a little bit in "my" cases. but nothing overwhelming and actually the fast-csg is more beneficial here, but as they work well together, every little bit counts. And I am sure that there are many cases more parallelizable than what I am doing.

About the build artifacts - thanks, that's what I was originally searching for, but I only found test result reports in the github gui :facepalm:

**Comment by parvit** [comment] 2022-07-10 08:49
@jkavalik Yes, as i mentioned in the PR, this is not a silver bullet, because it is limited by the fact that it cannot operate on a by-facet/by-vertex way.

That would require ditching CGAL completely and work with something like OpenCL (which i would even be open to do... but it would have to be a significantly higher bounty)

**Comment by qharley** [comment] 2022-07-10 10:01
I will give it a shot later.  I have a couple of heavy projects I can try on the platform.

**Comment by gingerbeardman** [comment] 2022-07-10 12:55
If there's a Universal Mac build I can also give it a try on
- an Intel Mac mini (currently 26 minute tun time)
- an M1 Pro MacBook Pro 9currently 9 minute run time)
-

**Comment by parvit** [comment] 2022-07-10 14:25
@gingerbeardman 
Is this one ok? https://app.circleci.com/pipelines/github/openscad/openscad/2835/workflows/28797625-1fae-4ab0-8c7d-dcd5a1310ca9/jobs/11983/artifacts

If not then i can't help as i don't have a mac environment to build.

**Comment by gingerbeardman** [comment] 2022-07-10 14:26
> @gingerbeardman 
> 
> Is this one ok? 

I'll try it!

**Comment by parvit** [comment] 2022-07-10 14:29
@gingerbeardman Yes it comes from the automatic execution on CircleCI for my last commit.

**Comment by qharley** [comment] 2022-07-10 16:42
Is there a config option you need to change for it to work?  I still only get 100% on one of the cores of my machine

**Comment by jkavalik** [comment] 2022-07-10 16:45
@qharley yes, has to be enabled in gui or cli - https://github.com/openscad/openscad/wiki/Experimental-Features

**Comment by qharley** [comment] 2022-07-10 16:54
Right!  Now I at least have 2 of 8 cores running at 100%

**Comment by parvit** [comment] 2022-07-10 17:36
@qharley Yeah it depends heavily on the script you're using (eg. you might have something like a union of 4 elements, that would consequently only use 2 cores even if you have more)

**Comment by parvit** [comment] 2022-07-12 09:57
@gingerbeardman The good option would be to compile it on your system.

Other than that i could suggest using [Wine](https://wiki.winehq.org/MacOS), but then the tests would be kind of moot.

**Comment by parvit** [comment] 2022-07-13 05:24
Hi everyone, seen that you seem to be using the change and that no one seems to have reported anymore outstandig issues, could we begin to look into merging the PR and then close the ticket?

**Comment by wolfwood** [comment] 2022-07-13 05:35
I won't be able to spend time getting a test build going for several weeks,
but my model found regressions in fast-csg, reported as #4114, so maybe it
would be a good test case for this as well, if you are interested in giving
it a try.

**Comment by t-paul** [comment] 2022-07-19 17:13
The ticket can only be closed with the PR merged (it's ok to keep it as an experimental feature). With vacation season in full swing at least in lots of places on the northern half of earth this may be a bit slow.
I'm buried in work which does not help either, but I'll try to get the changes integrated into a branch that can build the macOS snapshot so we can get some testing on that platform too.
Issue #2399 has a number of test cases that were used to stress test that earlier attempt, so those scripts are probably a good set to run against #4293 too.

**Comment by parvit** [comment] 2022-07-19 19:26
understood, i'll to put some time also into the tests you indicated as soon
as i can.

Il Mar 19 Lug 2022, 19:13 Torsten Paul ***@***.***> ha
scritto:

**Comment by parvit** [comment] 2022-07-29 07:27
Hi, i managed to execute the test that @wolfwood indicated on my machine (not VM but the native windows 10) and i've gotten these results.

| Model | stock render | fast-csg | multicore-ops | fast-csg + multicore-ops |
| ----- | ------------ | -------- | ------------- | ------------------------ |
| rest  | 7.97 | 37.01 | 8.02 | 37.02 |
| thumb | 75.20 | 15.51 | 75.95 | 15.62 |
| plate | 517.58 | 116.68 | 490.77 | 109.80 |
| fingers | 193.04 | 53.96 | 194.39 | 53.60 |
| assembly | 803.39 | 178.55 | 781.05 | 185.90 |

I'll also try in the near term to examine the examples in #2399.

Let me know.

**Comment by gingerbeardman** [comment] 2022-07-29 12:58
What are the numbers in the table and how to read them? Do they show worthwhile multi-core improvements?

**Comment by parvit** [comment] 2022-07-29 13:30
Sorry for assuming it was clear from the other posts, it's timings in seconds for rendering the *Model* scad files with the various combination of options.

To run it you need to download the branch from #4114 and the [hyperfine](https://github.com/sharkdp/hyperfine) tool.

If you can test on windows attached is my [batch script](https://github.com/openscad/openscad/files/9220282/time.bat.txt) for doing so.

**Comment by gingerbeardman** [comment] 2022-07-29 15:19
My models should see some benefits, that's great.

**Comment by gingerbeardman** [comment] 2022-07-29 19:06
Let me know where to send a download link

**Comment by parvit** [comment] 2022-07-30 06:59
Sent you a private email.

**Comment by gingerbeardman** [comment] 2022-07-31 16:11
Replied!

**Comment by parvit** [comment] 2022-08-08 09:00
Hi everyone, i've run that benchmark on the models sent me by @gingerbeardman and the results are mostly in line with the behavior of the previous round.

| Model | stock render | multicore-ops | fast-csg | fast-csg + multicore-ops |
| ----- | ------------ | ------------- | -------- | ------------------------ |
| _bubble.scad | 26.261099312 | 25.721508112 | 9.843301312 | 10.274663711999999 | 
| _buggy.scad | 17.188363407999997 | 16.697093508 | 15.678693608 | 15.926036208000001 | 
| _bus.scad | 4.998928614 | 5.028808914 | 6.178917314 | 6.088393314 | 
| _car.scad | 5.195643966 | 5.222250666 | 6.421972866 | 6.897909766 | 
| _city.scad | 5.355683514 | 5.401664513999999 | 6.798045114 | 7.1530325139999995 | 
| _cooper.scad | 4.052142894 | 4.063257794 | 2.1846763940000002 | 2.073138194 | 
| _cow.scad | 9.194655786 | 8.959258886 | 4.636112886 | 5.060754286 | 
| _drone.scad | 2.40718992 | 2.43829662 | 1.0952695700000001 | 1.21281537 | 
| _drone_old.scad | 2.301967798 | 2.2683364980000005 | 1.2523536480000002 | 1.447934348 | 
| _float.scad | 4.908594592 | 4.880892492 | 6.068473792 | 6.182992992 | 
| _forklift.scad | 6.673330346 | 6.724709146 | 4.577328546 | 4.583223446000001 | 
| _formula.scad | 8.877310846 | 9.065790646 | 5.796507246 | 6.006130145999999 | 
| _garbage.scad | 4.881669006 | 4.911801406 | 6.323921006 | 6.6850502060000005 | 
| _gilbern.scad | 5.278760242 | 5.238386942 | 6.626416642 | 2.342223542 | 
| _golf.scad | 11.987676018 | 12.104213118 | 7.215667418 | 8.142311418 | 
| _hover.scad | 7.015388486 | 6.985626086 | 1.4838841360000001 | 1.4604859860000001 | 
| _lada.scad | 4.915930306 | 4.964025606 | 6.3396219060000005 | 6.345804006 | 
| _landy.scad | 5.139970012 | 5.4241343120000005 | 7.030295212 | 6.637298812 | 
| _mini.scad | 4.38933923 | 4.38713063 | 5.72513253 | 5.76192193 | 
| _moai.scad | 4.3758837239999995 | 4.3916699239999994 | 1.2645088740000001 | 1.251016174 | 
| _moai_hover.scad | 2.811739208 | 2.828624208 | 3.315520508 | 3.343184708 | 
| _moai_wheels.scad | 2.024906416 | 2.013010916 | 1.374398416 | 1.378067766 | 
| _monster.scad | 5.746840206 | 5.754997406 | 5.483778506 | 5.588535706 | 
| _moto.scad | 1.888618452 | 1.885370852 | 1.3234275020000001 | 1.333523702 | 
| _pickup.scad | 4.790301962 | 4.795665462 | 6.184600362 | 6.714444462 | 
| _porsche.scad | 3.846746612 | 3.864111112 | 2.203478212 | 2.389340312 | 
| _r4.scad | 4.904752588 | 4.791256588 | 6.276386488000001 | 6.354884188000001 | 
| _rc.scad | 3.59162253 | 3.55777823 | 3.42250023 | 3.70033943 | 
| _safari.scad | 5.035603558 | 5.1418254580000005 | 5.651646758000001 | 5.5968067580000005 | 
| _scargo.scad | 6.21579527 | 6.30490317 | 6.47639267 | 7.52034187 | 
| _sheep.scad | 2.217535908 | 2.2101542079999996 | 1.736179008 | 1.961900608 | 
| _soda.scad | 0.700188792 | 0.7062994419999999 | 0.30886335866666664 | 0.3173263364444445 | 
| _taxi.scad | 12.836944134 | 12.917744934 | 7.822374534 | 7.7894376339999996 | 
| _townace.scad | 4.8645498400000005 | 4.93594904 | 6.838139040000001 | 6.96552174 | 
| _trueno.scad | 5.604805566 | 5.626452666 | 6.839159266 | 7.174020966 | 
| _twingo.scad | 5.88281852 | 6.17885592 | 7.00106382 | 7.01672582 | 
| _van.scad | 4.489768452 | 4.543267152 | 5.850868852 | 6.584820952 | 
| _wedge.scad | 3.604679432 | 3.5867000320000004 | 5.415746532 | 5.383629132 | 
| _wheels.scad | 2.883249272 | 2.8733519719999996 | 5.3471037720000005 | 5.173599072 | 

* _plane.scad : error `WARNING: Mixing 2D and 3D objects is not supported in file _plane.scad, line 77
WARNING: Ignoring 3D child object for 2D operation in file _plane.scad, line 77
Current top level object is not a 3D object.`

**Comment by wolfwood** [comment] 2022-08-08 14:57
@parvit thank you for taking the time to understand my test harness and to test with my models. I'm sure they results were disappointing, but its good to characterize the performance on as many test cases as possible when doing this kind of work.

**Comment by parvit** [comment] 2022-08-08 15:17
> @parvit thank you for taking the time to understand my test harness and to test with my models. I'm sure they results were disappointing, but its good to characterize the performance on as many test cases as possible when doing this kind of work.

you're right but it was not unexpected at this point, it might be time i have to try the alternative as a prototype.

**Comment by eliliam** [comment] 2022-11-28 23:50
Any update on this? For some models it takes nearly 2 minutes to render on my Ryzen 5900X since it's only using a single core's performance.

**Comment by parvit** [comment] 2022-11-28 23:55
sorry i haven't been able to rework my solution at the moment, i'll see in the near future to do it.

**Comment by parvit** [comment] 2023-01-18 07:25
Hi all, 
i've reworked the current approach using the great library [kigumi](https://github.com/unageek/kigumi) which is based on CGAL and seems to be very promising.

I have not been able to run the battery of rendering tests again however i've found that in some cases it even outperforms the hybrid operations.

It does however have a drowback:
1. It _requires_ C++20 (at this time i've added a cmake option EXPERIMENTAL_CXX_20 to disable it altogether)

I'll see to make again the tests in the near term.

**Comment by t-paul** [comment] 2023-01-18 09:33
@parvit hold the horses, I'm not sure that's going into a viable direction. We'll have to see if jumping on a 3 month old library with no releases is a good idea and and the possibility to actually use C++20 is years out. This will at least some discussion.

When looking at libraries, a very interesting option is https://github.com/elalish/manifold/ which also has a number of nice promises plus options to run on GPU. Also it's ok with C++17 which is a more realistic restriction currently.

**Comment by parvit** [comment] 2023-01-18 19:41
> @parvit hold the horses, I'm not sure that's going into a viable direction. We'll have to see if jumping on a 3 month old library with no releases is a good idea and and the possibility to actually use C++20 is years out. This will at least some discussion.
> 
> When looking at libraries, a very interesting option is https://github.com/elalish/manifold/ which also has a number of nice promises plus options to run on GPU. Also it's ok with C++17 which is a more realistic restriction currently.

Fair. i'll investigate the library you linked.

**Comment by ochafik** [comment] 2023-02-25 16:33
@t-paul @parvit I've hacked a quick, work-in-progress [Manifold](https://github.com/elalish/manifold/) integration in https://github.com/openscad/openscad/pull/4533. In theory it should support some level of multithreading (through either TBB or OMP) but I'm not seeing multicore usage just yet w/ TBB. Monothreaded speed seems already ace though.

**Comment by t-paul** [comment] 2023-02-25 19:57
Awesome, as Github only allows one reaction, a couple more here...  :heart_eyes: :+1: :tada:

CPU level multithreading would be great to start with, hopefully Manifold may get some more flexible (not vendor specific) GPU support too. I'm not sure CUDA would be a good choice for OpenSCAD, unless the support could co-exist with the other options.

**Comment by pca006132** [comment] 2023-02-27 15:45
Generic GPU support is hard. We use thrust for multithreading, which provides high level primitives that can be executed on CPU and GPU, and it seems unlikely that thrust will work on generic GPU support (at least in a short period of time). They don't even have dynamic backend selection, we have to hack our way out (we dynamically switch between single thread, multithread, and CUDA based on some heuristics, note that it is not well-tuned but just some random numbers). C++ standard parallelism sounds great, but I don't think the vendors are willing to invest their time to this instead of building their own C++ dialect.

From my observation, you don't really get much performance from using CUDA on normal meshes, you probably need millions of vertices to get decent speedup from CUDA. The overhead of data transfer, launching kernels and synchronization is just too large. And it would be better to spend more time on tuning those heuristics, parallelize other parts of the algorithm such as triangulation, work on things like caching, more efficient data structures, rather than trying to do generic GPU support. I actually think that SIMD might be more promising than using CUDA, our current bottleneck is actually sorting and it seems that there is some nice SIMD sorting implementation [here](https://github.com/google/highway/tree/master/hwy/contrib/sort).

**Comment by ochafik** [comment] 2023-02-27 16:46
@pca006132 Vulkan might be the best bet for cross vendor GPU acceleration. Works with NVidia and even Apple silicon (on which there’s zero penalty for memory transfers, given it’s all shared between CPU and GPU) through MoltenVK (uses Metal)

**Comment by ochafik** [comment] 2023-02-27 16:50
@pca006132 re SIMD, I’ve incidentally been working on faster maths in the openscad language itself using Eigen to store vectors / matrices when possible (it uses SIMD heavily, and can even tap into specialised acceleration on apple silicon although not sure yet whether it helps with small matrices). Code that does lots of geometry processing in user land (e.g using the BOSL2 library) should benefit a lot from that when I’m done (also, script execution will be the new bottleneck if/once Manifold ships in OpenSCAD 🤣)

**Comment by pca006132** [comment] 2023-02-27 17:38
Interesting, I think Eigen is typically used for large matrices, not sure if users will write large matrices in openscad scripts.
 I thinking having a numpy like interface might allow users to write more optimized code. 

Yeah, with faster CSG, users will probably write more complicated models and the scripts will become the bottleneck. I'm actually a student researching on compiler optimization things, so perhaps I can help someday :)

**Comment by ochafik** [comment] 2023-02-27 18:16
@pca006132 Yes I've ended up with large matrices w/ BOSL2 (lots of points, transformed / interpolated in batches). The big issue w/ OpenSCAD's handling of lists is it's completely generic (e.g. adding two vectors involves countless type checks and dynamic dispatches on each element), so I've taken an approach similar to [what V8 does w/ Arrays](https://itnext.io/v8-deep-dives-understanding-array-internals-5b17d7a28ecc), optimistically using optimized storage (also, reserving the right size) and gracefully degrading to more generic lists when the component types are not uniform / unsupported.

The [work in progress is in this branch](https://github.com/ochafik/openscad/compare/master...fast-linalg2?expand=1)

Also, Eigen excels at doing stuff w/ matrices of dynamic sizes, but also with SIMD optimizations on small, fixed-size matrices. It even has optimized paths for multadds, e.g. `out = a * b + c * d` only starts doing computations in the assignment, the RHS holds a compile-time AST encoded as C++ template types and the best implementation for the entire operation will be picked at compile time.

It's hard to combine w/ the dynamic nature of OpenSCAD's value system _in general_, so I've decided to capture only the most common AST shapes / subtypes in one big variant / union. Bit involved but got it mostly working.

**Comment by ioquatix** [comment] 2023-02-28 10:23
I can confirm Vulkan is a good target, having built cross platform renderers on Linux (native) and macOS (MoltenVK).

**Comment by ochafik** [comment] 2023-03-16 17:04
As a quick update, I'm happy to report that I'm making good progress with https://github.com/openscad/openscad/pull/4533: between Manifold's own parallelism and the parallel rewrite I've done to minkowski (only in the Manifold case for now), I'm now a bit shocked that some renders just slow down my mac noticeably 🤪. Here are [some examples of timings](https://gist.github.com/ochafik/70a6b15e982b7ccd5a79ff9afd99dbcf).

**Comment by t-paul** [comment] 2023-03-18 15:35
Autoclosed via Manifold work. This probably will cover the multi-thread topic as @ochafik shows, but lets get it back to open for a bit for verification...

**Comment by wolfwood** [comment] 2023-03-19 06:14
some perf numbers, including some models `fast-csg` regressed on:

|Model | `manifold` | stock render | `fast-csg` `fast-csg-exact` `fast-csg-exact-callbacks` `fast-csg-remesh` `fast-csg-trust-corefinement`| speedup over stock |
|:---:|---:|---:|---:|---:|
| _rest_          | **0.7351** |  4.096| *18.349* | **5.57x** |
| _thumb_      | **0.8607**| 62.391 | *117.351* | **72.49x** |
| _plate_        | **2.149** | *575.098* | 62.544 | **267.63x** |
| _fingers_     |  **1.577** | 159.499 | *207.602* | **101.14x** |
| _assembly_ | **2.794** | *554.994* | 350.813 | **197.23x** |

Absolutely incredible!

**Comment by pca006132** [comment] 2023-08-10 16:14
In case you guys are interested about how manifold scale with more cores, I just got some numbers for a PR:

![curve](https://user-images.githubusercontent.com/12198657/259770715-a211358a-f7bf-47e0-915c-3de80bac3017.png)

This is run with a i5-13600 KF @ 3.5GHz (turbo boost disabled), and I took average over 5 runs, with benchmarks in the manifold testcases. This is not using openscad but I think the graph should be similar when manifold is turned on and *the script is not using hull nor minkowski*. Not perfect scaling, it probably can only use 10 cores and get closer to 4x speedup. Throwing more cores on it beyond this point will not help much (at least for now).

**Comment by eliliam** [comment] 2023-09-13 18:36
Is this nearing the point where it can be merged? It seems like things are working pretty well for the users above who have benchmarked it, I'd love to see this merged into master so that we all can make use of this!

**Comment by pca006132** [comment] 2023-09-13 18:38
@eliliam this is already merged as an experimental feature. It is still not so stable, so it is not enabled by default.

**Comment by thehans** [comment] 2023-09-13 18:48
@eliliam See the "Development Snapshots" section of the downloads page: http://openscad.org/downloads.html#snapshots
If you install a recent snapshot, then you can open menu Edit -> Preferences -> Features -> check the box labeled `manifold` to enable it.

**Comment by holgerlembke** [comment] 2023-10-03 11:59
Oh, wow. Congratulations. Wow. Oh.

CGAL cache size in bytes: 96001888
Total rendering time: 0:03:36.436
Top level object is a 3D object:
   Simple:     yes
   Vertices:    19208
   Halfedges:   59944
   Edges:       29972
   Halffacets:  21474
   Facets:      10737
   Volumes:         2
Rendering finished.

CGAL cache size in bytes: 0
Total rendering time: 0:00:03.420
Top level object is a 3D object:
   Facets:      37352
Rendering finished.




![image](https://github.com/openscad/openscad/assets/2034993/db396ab0-0c3d-4840-b327-92b755196fec)

**Comment by gingerbeardman** [comment] 2023-10-03 17:34
Can I make use of this when using openscad from the command line?

I've checked Edit -> Preferences -> Features -> Fast-CSG  and Manifold

**Comment by pca006132** [comment] 2023-10-03 17:40
@gingerbeardman `--enable manifold`

**Comment by t-paul** [comment] 2023-10-03 17:48
@gingerbeardman I would advise against using both manifold and fast-csg at the same time, that's 2 separate geometry related experimental features on top of each other.

**Comment by gingerbeardman** [comment] 2023-10-03 17:59
Understood. So I'd suggest that perhaps the prefs should prevent checking both?

Anyway, I sadly do not see any benefits for my workflow (very small models, rendering using --animate to get single frames from each 360' angle)

**Comment by t-paul** [comment] 2023-10-03 18:06
No, I'm not suggesting that at all. The "experimental" does mean exactly that. May unlock nice new features so those can be tested by a wider audience than just 1 or 2 developers, but *could* break things and there's no guaranty they will ever be released in that exact implementation. 

Yes, for that workflow neither the amazing speed for processing high vertex count designs nor the internal multithreading would help much. If that's generating images in preview mode, even less so.

Also, that animation is awesome :heart_eyes:.

**Comment by gingerbeardman** [comment] 2023-10-03 18:29
I understand (that I don't understand 😆) no worries.

I did parallelise my workflow as much as I could, on Intel it was maxing out and locking up the computer for 26 minutes. After upgrading to M1 Pro, the task completes in 9 minutes with a full responsive computer. I just like to check in to see if anything has changed.

Anyway, off topic 🤭

**Comment by tpimh** [comment] 2023-10-04 10:02
Sorry for more off topic 😅

@gingerbeardman Are you publishing your game anywhere? Also interested in the workflow using OpenSCAD for 3D modelling and sprite sheet generation.

**Comment by kintel** [comment] 2023-10-04 12:30
@gingerbeardman Would it be possible to publish that sprite sheet generator somewhere? That could be an interesting test case for future optimizations.

**Comment by gingerbeardman** [comment] 2023-10-04 15:09
@tpimh really version of game is [on itch](https://gingerbeardman.itch.io/daily-driver)

@kintel sure! I uploaded it here, with a sample car model. Some aspects of the Makefile have been commented out for this example: https://github.com/gingerbeardman/openscad-spritesheet

The sprite sheet generator is a Frankenstein combination of a Makefile and several shell scripts that evolved over time (months/years). I only use OpenSCAD for exporting the initial frames. After this I use image magick to resize, split into channels, recolour, dither, and stitch together. 

I'm sure it could be optimised more, but I generally only refer render a single car at time which currently takes only 16 seconds and that's fine by me.

**Comment by edoardoo** [comment] 2024-03-25 14:03
I'm crying... A model that was taking ~2hrs to render now it takes only a handful of seconds. 
Thank you for doing this! I'm really grateful for your work!
It really enables me to test  and develop designs faster ❤️

**Comment by tcurtin** [comment] 2024-03-25 15:34
I just upgraded to 2024.03.18 and holy WOW.  From minutes to seconds and a return to total usability.  IMPRESSIVE UPGRADE - thanks to the folks who have made this happen!!!

**Comment by gingerbeardman** [comment] 2024-03-25 17:28
@tcurtin where do I get that version?

**Comment by edoardoo** [comment] 2024-03-25 17:41
I think it's a nightly, you can get them from the official website, just
scroll down on the download page.

**Comment by ioquatix** [comment] 2024-03-25 22:21
Any timeframe for an official release? Sounds amazing :)

**Comment by kintel** [comment] 2024-03-29 14:33
No timeframe yet, but we're working on finalizing and stabilizing experimental features like this for release.

**Comment by vortex64** [comment] 2024-04-03 01:56
Thanks to all those responsible.  Just donated.

**Comment by Gisi0** [comment] 2024-05-24 08:03
Works great, reduce rendering time from hours (I don't waited to the end) under one minute.

**Comment by Windy-Lion** [comment] 2024-07-07 17:35
This works great for speeding up the generation of parts with Minkowski operations, but it does not seem to affect the speed of CSG Products generation, in fact for the one trial I selected which makes use of rather large nested for() operations to generate cam profiles, it seems to slow the preview down, which means that for animations like this, it might be faster to use the old method, depending on the model. Is there any work to improve the speed of CSG Products generation for nested for() loops?
![image_2024-07-07_132604817](https://github.com/openscad/openscad/assets/96323644/b61a7b30-cd67-43a4-98ad-639b33ae51d3)
![anim2](https://github.com/openscad/openscad/assets/96323644/8daab726-125b-4477-8bc8-bd3490eea201)

It does still drastically improve the speed of the final render, though, which is nice.
![image](https://github.com/openscad/openscad/assets/96323644/a701dcd9-79b6-4dbc-ad74-451f35bc3815)

**Comment by kintel** [comment] 2024-07-07 19:53
@Windy-Lion The Manifold isn't going to affect previews much, unless you use the `render()` function, so your observations make sense.

**Comment by lwan288** [comment] 2024-10-31 00:00
> manifold

Hi,   May I ask which version are you using?   I just upgraded openscad on my machine to 2024.10.28, but unfortunately didn't find manifold in preferences...
![image](https://github.com/user-attachments/assets/46dd7357-27d5-4054-ab65-33e757001c58)

Here is the version I installed on Windows 11
![image](https://github.com/user-attachments/assets/7577369a-0328-4f78-a091-6990cf4f5b28)

**Comment by t-paul** [comment] 2024-10-31 00:02
See https://fosstodon.org/@OpenSCAD/113256867413539398

**Comment by TobseF** [comment] 2024-11-21 23:51
To speed up the rendering, change the rendering option to the new 
**Manifold**:

*Edit* > *Preferences* > *Advanced* >  *3D Rendering* > *Backend* → **Manifold (new/fast)**  
Then restart OpenScad to use the new rendering engine.

![Screenshot Settings](https://github.com/user-attachments/assets/12f96190-9111-4990-9f6d-172a2d9aeffa)


This Option [is available](https://fosstodon.org/@OpenSCAD/113256867413539398) since version `2024.09.28`.

**Rendering time Before**: `0:00:21.824`  
**Rendering time After**:   `0:00:00.013`

So it's about 1678 x faster than the old one. Don't know why this is not the default option.

**Comment by kintel** [comment] 2024-11-22 02:06
Let's close this!
To bad BountySource embezzled the large bounty : (


@TobseF It will be made default soon - there are still a couple of issues + tests we need to sort out.

**Closed by kintel** 2024-11-22 02:06 UTC
Labels: Type: Enhancement, BountySource-is-Insolvent, Dep: CGAL
