### ISSUE TITLE
Discuss SSAO

### ISSUE THREAD

**Issue by TLC123** [openscad/openscad#3090] opened 2019-10-08 16:44 UTC
Prompted by a discussion in the forum about shadows (shading) and shape perception i low light regions.
The issue was that it is some times hard  to distinguish the shape of geometry in the less exposed regions.  

True ambient occlusion is excellent to convey shape information but to expensive in real time.
Fake screen space ambient occlusion is fast but lack some of that excellence, still is plausibly useful.
I don't have any experience of SSAO in cad environments but its prevalent in games these days. 
In its simplest form, implementation is as i understand it a medium trivial image postprocess. 
Given that a depth-map is accessible.

My question to community is what is there any obvious reason to belive this is a hard/impossible feature not worth investigation as an option?

**Comment by nophead** [comment] 2019-10-08 16:56
I don't know that it needs anything more than a non-diffuse light source. The problem is that any flat surface is all the same shade exactly when lit with a diffuse light, so another overlapping face at the same angle can't be distinguished unless it is a different colour. 

If the light were a point source then the angle of incidence would vary across a flat face so the shade would vary.

I don't know if this is possible with OpenCSG as it seems to use trick of two diagonally opposed light to get around a problem with inside faces.

**Comment by t-paul** [comment] 2020-02-16 15:46
Closing as there's no discussion happening. Maybe repost on the forum to see if there's feedback to be collected. We can open a new issue if there's a clearer view of how this feature would fit into OpenSCAD.

**Closed by t-paul** 2020-02-16 15:46 UTC
Labels: Type: Discussion
