### ISSUE TITLE
OpenScad will not load on Mac

### ISSUE THREAD

**Issue by RetiredJake** [openscad/openscad#5094] opened 2024-04-20 02:25 UTC
**Describe the bug**
Downloaded "OpenSCAD-2021.01.dmg" on 4/19/24. When trying to install, received the following error message:
“OpenSCAD.app” cannot be opened because the developer cannot be verified.
Perhaps some verification certificate has expired ?
Can really use some help so I can get the program loaded and start learning it.
**To Reproduce**
1. Download "OpenSCAD-2021.01.dmg"
2. Click on downloaded file
3. See error

**Expected behavior**
Software to be installed and opened
**Code reproducing the issue**
If applicable, add trimmed down, self-contained code demonstrating the issue.

**Screenshots**
![Screen Shot 2024-04-19 at 9 20 54 PM](https://github.com/openscad/openscad/assets/167362674/4413cf0e-9d95-4656-bae2-e8f0d9ee1b70)

**Environment and Version info (please complete the following information):**
 - OS: macOS 12.7.4 Monterey
 - System: 2015 MacBook Pro
 - OpenSCAD Version [OpenSCAD-2021.01.dmg] downloaded from "https://openscad.org"

**Library & Graphics card information**
If applicable, add the content of the Help->Library Info window, or the output of running the `openscad --info` command.

**Additional context**

**Comment by kintel** [comment] 2024-04-20 03:14
If you Ctrl-click on the icon, you can bypass the "unverified developer" check: https://support.apple.com/en-ca/guide/mac-help/mh40616/mac

We're currently not signing our binaries due to Apple's stringent developer policy (they only accept incorporated entities for non-personal account and charges an annual fee), so we haven't been motivated to jump through the hoops.

**Comment by kintel** [comment] 2024-04-20 03:15
Closing as duplicate of #880

**Closed by kintel** 2024-04-20 03:15 UTC
Labels: Type: Bug
