### ISSUE TITLE
Macintosh Sequoia 15.1 prevent OpenSCAD v2021.01 from opening

### ISSUE THREAD

**Issue by DeanDavis** [openscad/openscad#5398] opened 2024-10-29 15:48 UTC
**Describe the bug**
Trying to launch OpenSCAD.app Mac version 21.01 on Mac running Sequoia 15.1 give an error
The Application "Finder" does not have permission to open "(null)."
![Screenshot 2024-10-29 at 11 39 42 AM](https://github.com/user-attachments/assets/b7deb5c2-2f8c-400a-99e5-f50d252b3a76)

**To Reproduce**
Double Click OpenSCAD.app file

**Expected behavior**
Program Starts

**Environment and Version info (please complete the following information):**
 - OS: macOS 15.1 Sequoia
 - System: Apple M1
 - OpenSCAD Version 2021.01.31 (from info.plist) downloaded directly from OpenSCAD website

**Additional context**
Workaround is to open the contents of OpenSCAD.app and open "OpenSCAD" directly from MacOS folder.

**Comment by sciencejoan** [comment] 2024-10-29 19:18
Seeing same behavior after upgrading MacOS this morning on Intel (2019) iMac as well as Macbook with M2 chip.

**Comment by Behodar** [comment] 2024-10-30 00:15
Same here. Updated from 14.7 to 15.1 this morning, and now I'm getting the same error when launching OpenSCAD 2021.01, although I can use the mentioned workaround of running the binary directly from inside the Contents/MacOS folder (albeit with a Terminal window stuck open).

Presumably it's broken for everyone?

**Comment by kintel** [comment] 2024-10-30 02:57
I'm going to prioritize this now that macOS 15 is out, and Apple didn't withdraw their annoying policy change.

**Comment by kintel** [comment] 2024-10-31 03:22
Closing this as duplicate of #880

**Closed by kintel** 2024-10-31 03:22 UTC
Labels: Type: Bug
