### ISSUE TITLE
nested colors

### ISSUE THREAD

**Issue by holgerlembke** [openscad/openscad#5446] opened 2024-11-21 19:51 UTC
Nested colors work like designed, but the design is annoying. :-)

I like to design my parts like shown in the example. There is often a single big color() bracket around everything. If I add a part into another part it looses its color. I understand the current concept of color()-nesting with its "the outer wins" style and that it is following the openscad nesting concept (and have read https://github.com/openscad/openscad/issues/4057). But it is annoying, because now most of the time I have to add multiple color()s into the part design. (Did I miss any ideas how to avoid?)

My proposal would be to add a keyword "sealed" into the color() command. It locks the color-attribut after setting it. Then the design could be nested in a more convenient way.
```
outerpartA();
translate([15,0,0]) outerpartB();

module outerpartA() {
    color("red") {
        translate([0,0,10]) sphere(d=10);
        innerpartA();
        //....xxx
    }
}

module innerpartA() {
    color("blue") {
        cube([10,10,10],center=true);
        //....xxx
    }
}


module outerpartB() {
    {
        color("red") translate([0,0,10]) sphere(d=10);
        innerpartA();
        //....xxx
    }
}

module innerpartB() {
    color("blue") {
        cube([10,10,10],center=true);
        //....xxx
    }
}


module outerpartC() {
    color("red") {
        translate([0,0,10]) sphere(d=10);
        innerpartA();
        //....xxx
    }
}

module innerpartC() {
    color("blue",sealed) {
        cube([10,10,10],center=true);
        //....xxx
    }
}


```

**Comment by kintel** [comment] 2024-11-28 04:24
Duplicate of #492 - that issue also discusses some ideas

**Closed** 2024-12-06 02:41 UTC
Labels: Type: Enhancement
