### ISSUE TITLE
Import of freecad 3mf fails silently (stl works)

### ISSUE THREAD

**Issue by fallingcats** [openscad/openscad#4723] opened 2023-08-19 01:03 UTC
**Describe the bug**
When importing a 3mf file exported from a freecad 0.21 project the import does not throw errors but does not get rendered in any way. Importing a freecad exported stl file of the same object works though.  

**Expected behavior**

**Code reproducing the issue**
```
// works
import("exports/activ energy XYZ562a socket v08.stl");

// does not work
import("exports/activ energy XYZ562a socket v08.3mf");
```

**Environment and Version info (please complete the following information):**
    Operating System: Arch Linux 
    KDE Plasma Version: 5.27.7
    KDE Frameworks Version: 5.108.0
    Qt Version: 5.15.10
    Kernel Version: 6.1.44-1-lts (64-bit)
    Graphics Platform: X11
    Processors: 8 × AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 15.0 GiB of RAM
    Graphics Processor: AMD Radeon Graphics
    Manufacturer: HP
    Product Name: HP ENVY x360 Convertible 15-ee0xxx
 - OpenSCAD Version 2021.01

**Additional context**
Zip containing both files: [activ energy XYZ562a socket.zip](https://github.com/openscad/openscad/files/12384634/activ.energy.XYZ562a.socket.zip)

**Comment by UBaer21** [comment] 2023-08-19 06:25
Just tested with 2023.08.08 where it seems to work fine.

**Comment by fallingcats** [comment] 2023-08-21 17:58
> Just tested with 2023.08.08 where it seems to work fine.

Sorry, I can't confirm that, building something newer locally fails for me

**Comment by t-paul** [comment] 2023-08-21 18:29
I can't reproduce on Debian/testing with both 2021.01 release and latest snapshot version. But essentially all builds (except Flatpak I believe) still use lib3mf 1.8.x. As far as I know Arch already uses lib3mf 2.x.

In Flatpak, I'm seeing:
WARNING: Could not read file '/tmp/o/activ energy XYZ562a socket-Cut v08.3mf', import() at line 1

So it seems the file is not compatible with the official 3mf library. This probably means the issue can't be soved on OpenSCAD side.

**Comment by UBaer21** [comment] 2023-08-21 18:31
![image](https://github.com/openscad/openscad/assets/93376232/21fe14fe-5a34-45fc-9e94-86e614337274)

works fine on  win with 2023.08.13  maybe try a full path

**Comment by fallingcats** [comment] 2023-08-21 18:40
> @fallingcats can you provide the error msg from the console?

As I tried to say with "fails silently", there is no error msg in the integrated console

**Comment by t-paul** [comment] 2023-08-21 18:45
See my comment above, dev version shows a warning. It's possible that is missing in the release.

**Comment by fallingcats** [comment] 2023-08-21 18:46
Oh, it seems openscad only shows an error once, not repeatedly when pressing Preview/F5. Here is the complete (but probably useless log):

```
Parsing design (AST generation)...
Saved backup file: /home/bernhard/.local/share/OpenSCAD/backups/unsaved-backup-LwTJCtkv.scad
Compiling design (CSG Tree generation)...
Compiling design (CSG Products generation)...
WARNING: Could not read file '/home/bernhard/Projects/3D Printer/designs/scooter battery mount/exports/activ energy XYZ562a socket-Cut v08.3mf', import() at line 1 
Geometries in cache: 2
Geometry cache size in bytes: 304
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized tree has 1 elements!
Compile and preview finished.
Total rendering time: 0:00:00.023
```

If you could provide a static binary, I could try that.

**Comment by t-paul** [comment] 2023-08-21 18:49
You could try with the AppImage, either release or dev snapshot from the [download page](https://openscad.org/downloads.html). Those still use the old lib3mf for reading files.

You can ignore the warning banner there, I'm about to remove that, downloads should be working fine again.

**Comment by UBaer21** [comment] 2023-08-21 18:51
Ok i now had i very weird experience .. Autocad (meshmixer) couldn't open it. Microsoft3D builder could - after i saved it there Scad couldn't open it anymore (nor Meshmixer) .. 
Then i opened the original again in SCAD rendered (in union with cube) and exported it - this could be opened with meshmixer ..  @fallingcats  can you give it a try (rename the zip to 3mf as github doesn't support 3mf)
[activeEnergySCAD.zip](https://github.com/openscad/openscad/files/12400456/activeEnergySCAD.zip)

**Comment by fallingcats** [comment] 2023-08-21 18:59
> You could try with the AppImage, either release or dev snapshot from the [download page](https://openscad.org/downloads.html). Those still use the old lib3mf for reading files.

Both dev and regular AppImage versions work for me. It seems the error may come from the way it's packaged in Arch. I will investigate further.

**Comment by fallingcats** [comment] 2023-08-21 19:03
> @fallingcats can you give it a try (rename the zip to 3mf as github doesn't support 3mf)
> [activeEnergySCAD.zip](https://github.com/openscad/openscad/files/12400456/activeEnergySCAD.zip)

Also does not work in my distribution provided version

**Comment by fallingcats** [comment] 2023-08-22 00:36
> But essentially all builds (except Flatpak I believe) still use lib3mf 1.8.x. As far as I know Arch already uses lib3mf 2.x.
The version of lib3mf-1 the openscad package of arch depends on is 1.8.1-6, see [archive](https://archive.archlinux.org/packages/l/lib3mf-1/)/[package](https://archlinux.org/packages/extra/x86_64/lib3mf-1/), [openscad package](https://archlinux.org/packages/extra/x86_64/openscad/).
I've tried 1.8.1-5 which was the current version during release of openscad 2021.01, but that didn't change anything.

**Comment by jordanbrown0** [comment] 2023-08-22 01:15
> Oh, it seems openscad only shows an error once, not repeatedly when pressing Preview/F5

We really need to fix it so that the result from an error isn't cached like that.  This is a common confusion.  (But unrelated to the question of why it can't read this file.)

**Comment by t-paul** [comment] 2023-08-25 17:55
Root cause is the `item` line 
```
 <build>
  <item objectid="1" transform="1 0 0 0 1 0 0 0 1 166.887435 102.433224 0" printable="1"/>
 </build>
```
raising the error "Lib3MF Error 5 (Wanted to convert string with non-numeric characters to double)".

This is essentially the same issue as #4204 which is an upstream bug https://github.com/3MFConsortium/lib3mf/issues/282 - I have `LC_NUMERIC=de_DE.UTF-8` set so the notation with '.' is invalid.

**Comment by t-paul** [comment] 2023-08-25 19:39
Upstream PR submitted https://github.com/3MFConsortium/lib3mf/pull/322 - but closing as duplicate.

You can register for notifications in #4204 if you want to follow updates.

**Closed by t-paul** 2023-08-25 19:39 UTC
Labels: Type: Bug

**Comment by fallingcats** [comment] 2023-08-26 01:43
> This issue starts to break OpenSCAD installations as some Linux distributions have moved to lib3mf v2.2.0. At this point, I'm aware of **Arch** and Fedora **shipping this version**.

@t-paul Sorry but I've been trying to tell you that this is [wrong](https://github.com/openscad/openscad/issues/4723#issuecomment-1687242834). If you don't believe me look here:
- https://archlinux.org/packages/?sort=&q=lib3mf
- https://gitlab.archlinux.org/archlinux/packaging/packages/openscad/-/blob/main/PKGBUILD#L36

**Comment by t-paul** [comment] 2023-08-26 02:16
AUR ships v2.2.0, so people might use it.

**Comment by fallingcats** [comment] 2023-08-26 02:45
> AUR ships v2.2.0, so people might use it.

Please remember that the AUR is "completely unofficial" and not part of the distribution. It is not "shipped by arch" but random users.
I've tried that package, it does not even build (for me). In any case a 2.0 -> 2.2 regression shouldn't be the cause of my problem?
