### ISSUE TITLE
Does transparency work incorrectly or is it intended that way?

### ISSUE THREAD

**Issue by kberkut** [openscad/openscad#4259] opened 2022-05-13 05:32 UTC
Does transparency work incorrectly or is it intended that way?

![image](https://user-images.githubusercontent.com/57869227/168217357-9fa66bd2-8ac2-4e31-90e2-5c00bcae619d.png)
![image](https://user-images.githubusercontent.com/57869227/168217443-6e516a7b-06c9-4c91-8b07-9d6a206cd9d2.png)

**Comment by LookoutHill** [comment] 2022-05-14 01:02
It appears that I am seeing the same issue - transparency is only one way (or so it would appear from my model). One picture is the view from above (the subfloor is opaque) and the other is seen from below (the subfloor is transparent). The responsible snippet is: color(alpha = 0.1) { /* Omitted the code to place plywood panels, but it contains no other color manipulations or % operators. */ }
![2022-05-13 (1)](https://user-images.githubusercontent.com/52175833/168404889-cc73f70e-2903-405b-87e1-0f6f3ff2bf56.png)
![2022-05-13](https://user-images.githubusercontent.com/52175833/168404890-ee1d9008-be9b-4a59-86d8-eccf040cdcc6.png)
.

**Comment by jordanbrown0** [comment] 2022-05-14 01:50
@kberkut @LookoutHill cut your problem case down to a minimum demonstration and supply the program, please.  Transparency is quite limited and perhaps you are hitting its limits.

Here's a program that demonstrates an ... interesting ... behavior that is more wrong than I expected:

```
translate([0,0,0]) cube(10);
translate([0,0,10.1]) color(alpha=0.2) cube(10);
translate([0,0,20.2]) cube(10);
```

Looking down, it's kind of what you'd expect:
![image](https://user-images.githubusercontent.com/31949071/168405856-5a9a7322-5488-4eb2-bf25-a20fac95ad37.png)

Looking up, however...
![image](https://user-images.githubusercontent.com/31949071/168405883-7156f2c5-1129-4806-a626-7c430acd0b73.png)
Note that you can see through the upper cube.

I'm not so much surprised that there are artifacts, as that they are asymmetric.

**Comment by jordanbrown0** [comment] 2022-05-14 03:17
A bit of memory refresh and experimentation later...

Order matters.  Have the transparent objects be after the non-transparent objects.

```
translate([0,0,0]) cube(10);
translate([0,0,20.2]) cube(10);
translate([11,11,10.1]) color("blue") cube(10);
translate([-11,-11,10.1]) color("blue") cube(10);
translate([0,0,10.1]) color(alpha=0.3) cube(10);
```
works pretty well.  Moving the transparent cube to the top:
```
translate([0,0,10.1]) color(alpha=0.3) cube(10);
translate([0,0,0]) cube(10);
translate([0,0,20.2]) cube(10);
translate([11,11,10.1]) color("blue") cube(10);
translate([-11,-11,10.1]) color("blue") cube(10);
```
... not so well.

This is the source of the asymmetry I observed in my previous experiment.

**Comment by jordanbrown0** [comment] 2022-05-14 03:36
I believe that the reason for this is that preview basically operates by drawing all of the faces and letting the display driver and hardware figure out which ones are closest to the camera.  A transparent face lets some of the existing image through.

So if you draw the solid object first, and then the transparent object that is in front of it, the transparent faces let the solid object show through.

If, on the other hand, you draw the transparent object first, there is nothing to show through, and then when you draw the solid object behind it, well, it's behind something existing and so doesn't show.

None of this is "right", of course, but it's how the high-speed preview stuff works.

**Comment by kberkut** [comment] 2022-05-14 04:22
> @kberkut @LookoutHill Same result.

`translate([0,0,0]) color("red") cube(10);
translate([0,0,10.1]) color(alpha=0.1) cube(10);
translate([0,0,20.2]) color("green") cube(10);`

![image](https://user-images.githubusercontent.com/57869227/168410374-de5808e3-5b23-4e6f-9188-de10dcbf9f9d.png)
![image](https://user-images.githubusercontent.com/57869227/168410386-505a1a48-bf17-481c-aeb2-e93a9a27ef49.png)
![image](https://user-images.githubusercontent.com/57869227/168410400-8f47c1a7-e00e-4725-a2e0-3d430103823e.png)
Linux ARCH 5.17.5-arch1-2

Another simple example.
`$fn=100;
module any_tube(diametr_outer, height, thinkness){
  rotate_extrude(convexity = 10) 
  translate([diametr_outer/2-thinkness,0,0])
  square([thinkness,height]);
}
module move(x=0,y=0,z=0,rx=0,ry=0,rz=0)
{translate([x,y,z]) rotate([rx,ry,rz]) children();}
color("red", 0.2) any_tube(160,300,0.5);
color("blue") cylinder(300,55,55);
`
![image](https://user-images.githubusercontent.com/57869227/168410463-3ccffeca-7b92-4444-9332-b4a405d770d1.png)
![image](https://user-images.githubusercontent.com/57869227/168410478-02e8bb6c-fea3-4388-a762-959ccadf1c26.png)

**Comment by kberkut** [comment] 2022-05-14 04:27
![2022-05-13](https://user-images.githubusercontent.com/52175833/168404890-ee1d9008-be9b-4a59-86d8-eccf040cdcc6.png) .
Cool) I designed a frame house in sketchup. If you are interested, please contact)

**Comment by jordanbrown0** [comment] 2022-05-14 04:55
Swap the cylinder and the any_tube to put the transparent object (the any_tube) last, and you get this:

![image](https://user-images.githubusercontent.com/31949071/168411138-279357df-84ce-4ecb-85ae-06d250533450.png)

Similarly for the green/transparent/red stack, if you put the transparent cube after the green cube, you get this:
![image](https://user-images.githubusercontent.com/31949071/168411221-e832a840-479c-48ad-9582-5396818e8670.png)
Note that we are seeing the bottom of the green cube, rather than seeing through it.

Looks to me like this is a duplicate of #1390, but I don't have the authority to close it.

**Comment by kberkut** [comment] 2022-05-14 05:07
Confirm. It is enough to swap places. But still, this is wrong behavior. This is a bug.

![image](https://user-images.githubusercontent.com/57869227/168411559-d0402ea1-8984-4c29-a923-500fcbea10b8.png)

**Comment by jordanbrown0** [comment] 2022-05-14 05:08
Yep.  Ref #1390.  Known for a long time.  Very hard to fix.

**Comment by kberkut** [comment] 2022-05-14 05:13
Alternatively, add an entry about this feature of OpenSCAD to the help section.

"For the correct display of transparent objects, the location of instructions (modules) should be from the inside of the model to the outside."

But unfortunately this is not always possible, especially in complex models.

**Comment by kberkut** [comment] 2022-05-14 05:18
![image](https://user-images.githubusercontent.com/57869227/168411849-cdc0e1c2-a1d3-4e2a-9a92-34ae309c6f87.png)

$fn=100;

module any_tube(diametr_outer, height, thinkness){
  rotate_extrude(convexity = 10) 
  translate([diametr_outer/2-thinkness,0,0])
  square([thinkness,height]);
}

module move(x=0,y=0,z=0,rx=0,ry=0,rz=0)
{translate([x,y,z]) rotate([rx,ry,rz]) children();}

// The correct location.
color("red", 0.2) any_tube(10,300,0.5);
color("blue", 0.2) any_tube(30,300,0.5);
color("green", 0.2) any_tube(50,300,0.5);
color("pink", 0.2) any_tube(70,300,0.5);

// The incorrect location.
move(x=100) color("red", 0.2) any_tube(10,300,0.5);
move(x=100) color("pink", 0.2) any_tube(70,300,0.5);
move(x=100)color("green", 0.2) any_tube(50,300,0.5);
move(x=100)color("blue", 0.2) any_tube(30,300,0.5);

**Comment by jordanbrown0** [comment] 2022-05-14 05:21
See the note I just added to #1390 about a problem that can't be solved with ordering.

**Comment by LookoutHill** [comment] 2022-05-14 05:33
@jordanbrown0 @kberkut Sweet! Moved the subfloor code to the end of the program and all is well. Thanks! A note in the documentation near % and color() would go a long ways towards managing this issue.

**Comment by jordanbrown0** [comment] 2022-05-14 05:47
I added a caution to the [documentation for color()](https://en.wikibooks.org/w/index.php?title=OpenSCAD_User_Manual/Transformations#color):

Warning: alpha processing (transparency) is order-sensitive. Transparent objects must be listed after non-transparent objects to display them correctly. Some combinations involving multiple transparent objects cannot be handled correctly. See issue [#1390](https://github.com/openscad/openscad/issues/1390).

(I don't understand the publication process for the documentation; it might not be immediately visible to others.)

**Comment by kberkut** [comment] 2022-05-14 06:16
> I added a caution to the [documentation for color()](https://en.wikibooks.org/w/index.php?title=OpenSCAD_User_Manual/Transformations#color):
> 
> Warning: alpha processing (transparency) is order-sensitive. Transparent objects must be listed after non-transparent objects to display them correctly. Some combinations involving multiple transparent objects cannot be handled correctly. See issue [#1390](https://github.com/openscad/openscad/issues/1390).
> 
> (I don't understand the publication process for the documentation; it might not be immediately visible to others.)

I think the example with the mutual arrangement of pipes will be more understandable and friendly for new users. Including the picture.

**Comment by t-paul** [comment] 2022-05-14 17:24
Closing as duplicate of #1390.

**Closed by t-paul** 2022-05-14 17:24 UTC

**Comment by MichaelAtOz** [comment] 2022-05-15 08:17
Note also #310.
