### ISSUE TITLE
Unable to render a union with a SVG path when curve self-intersects.

### ISSUE THREAD

**Issue by lubosz** [openscad/openscad#5200] opened 2024-07-01 10:09 UTC
**Describe the bug**
For paths that contain self-intersections caused by an inverted handle direction, rendering a union with the extruded path fails with:
```
ERROR: The given mesh is not closed! Unable to convert to CGAL_Nef_Polyhedron.
```
The error is produced in [cgautils](https://github.com/openscad/openscad/blob/d4c36aa2bb7c20d9e3dd847ce96ebe6011bae39b/src/geometry/cgal/cgalutils.cc#L73) when a `CGAL_Polyhedron` is not closed.

The object can be previewed without an error.

A mesh of only the extruded SVG can be rendered  without an error.

SVGs in the wild can contain this issue without being apparent due to the path's complexity.

**To Reproduce**
1. Clone the repro repo https://github.com/lubosz/openscad-svg-bug
2. Open `svg-bug.scad`
3. Render the mesh

**Expected behavior**
The mesh should be able to render, as correctly visible in the preview.  It would be nice for OpenSCAD to handle this or to have a way to analyze which nodes caused the issue.

**Code reproducing the issue**
```javascript
// Produces "ERROR: The given mesh is not closed! Unable to convert to CGAL_Nef_Polyhedron. "
svg_path = "broken/a.svg";

// Works
// svg_path = "working/a.svg";

union() {
  // Commenting the cube line avoids the issue
  cube([50, 50, 1], center=true);

  linear_extrude(2) import(svg_path, center=true);
}
```

**Screenshots**

| A bezier path node with handle directions that cause self-intersection. (Inkscape) |
|:--| 
| ![Broken node](https://github.com/openscad/openscad/assets/295622/03aa96c0-bf16-408f-a155-67002c6676cb) | 

| Fixed bezier path node. (Inkscape) |
|:--| 
| ![Working node](https://github.com/openscad/openscad/assets/295622/fbcf04cb-a0a1-4013-adaa-bbabeda99546) | 

| Preview works without errors. |
|:--| 
| ![Preview works](https://github.com/openscad/openscad/assets/295622/51d9a043-f3a5-41a9-8e8a-1ad46af0e163) | 

| Without creating a union the mesh can be rendered. |
|:--| 
| ![Mesh creation works](https://github.com/openscad/openscad/assets/295622/56162eac-ae06-4976-97ed-42b32a455fab) | 

**Environment and Version info (please complete the following information):**
 - OS: Arch Linux
 - System: AMD PC 64-bit
 - OpenSCAD Version: Built from source using git master at `d4c36aa2bb7c20d9e3dd847ce96ebe6011bae39b` and
Version `2021.01-11` installed from Arch Linux

**Comment by nophead** [comment] 2024-07-01 11:59
I think you can fix it by applying a miniscule `offset()`. That passes it through the 2D Clipper library that is very good at fixing broken polygons.

**Comment by lubosz** [comment] 2024-07-01 12:10
> `offset`

@nophead You are right! Applying `offset(0.00001)` to the import avoided the issue!
An offset of `0.000001` was not enough, `0.00001` seems to be needed, which did not introduce any noticeable visible change.

**Comment by nophead** [comment] 2024-07-01 12:47
You can always offet again with -0.0001 to not change the dimensions.

**Comment by kintel** [comment] 2024-07-01 14:33
Closing as duplicate of #5053.
Note: This works when using the Manifold backend

**Closed by kintel** 2024-07-01 14:33 UTC
Labels: Type: Bug

**Comment by lubosz** [comment] 2024-07-01 19:28
I can confirm that the issue does not occur using the manifold backend.

To enable the backend, OpenSCAD needs to be compiled with `-DEXPERIMENTAL=On`, which makes the "Features" tab appear under preferences. Manifold can be enabled there.

**Comment by kintel** [comment] 2024-07-01 20:58
Or you can use a precompiled development snapshot instead of building it yourself
