### ISSUE TITLE
Incorrect global library location on MacOS 

### ISSUE THREAD

**Issue by jottr** [openscad/openscad#3482] opened 2020-11-10 20:03 UTC
According to the [documentation](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Libraries#Library_Locations) openSCAD libraries that should be globally available must be placed in the `Documents`-folder, i.e.`$HOME/Documents/OpenSCAD/libraries`.

1. This pollutes the users `Documents` folder 
2. Does not follow the commonly used MacOS configuration path, see Apple's official [documentation](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFileSystem/Articles/WhereToPutFiles.html)

I would like to suggest that openSCAD loads global libraries in the following order on MacOS:

```
$HOME/Library/Preferences/openSCAD/libraries
$HOME/.local/share/OpenSCAD/libraries # match Linux XDG path for portability
$HOME/Documents/OpenSCAD/libraries # for backwards compatibility
$HOME/.openSCAD/libraries # follow common dotfiles convention
```

**Comment by t-paul** [comment] 2020-11-10 20:06
Duplicate of #1524.

**Comment by jottr** [comment] 2020-11-10 20:07
Sorry for the duplicate.

**Closed by t-paul** 2020-11-10 20:06 UTC
