### ISSUE TITLE
Incorrect display at difference

### ISSUE THREAD

**Issue by kberkut** [openscad/openscad#5027] opened 2024-03-03 19:13 UTC
**Describe the bug**
Surfaces subject to subtraction are not displayed.

**To Reproduce**
Repeat the simple code
`$fn = $preview ? 100 : 100;
Dh = 50;
Hh = 50;
Dotv = 8;
TH = 5;
module work()
{
	difference()
	{
		cylinder(d = Dh, h = Hh);
    cylinder(d = Dotv, h = Hh + TH);
    translate([0,0,-1]) cylinder(d = Dh - 2 * TH, h = Hh - TH);
	}
}
work();`

**Expected behavior**
Clear visibility of the surfaces of the shape that has undergone the difference operation

**Code reproducing the issue**
If applicable, add trimmed down, self-contained code demonstrating the issue.

**Screenshots**
![image](https://github.com/openscad/openscad/assets/57869227/0d2a641d-dfda-404e-80e0-1dc15242db06)
![image](https://github.com/openscad/openscad/assets/57869227/926035f0-31f4-4969-a4b3-58bce4bef38c)

**Environment and Version info (please complete the following information):**
 - OS: Arch Linux                                                                                                                                                                               
 Kernel: x86_64 Linux 6.7.6-arch1-2
 DE: GNOME 45.3
 WM: Mutter

 - System: 
 CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx @ 8x 2.1GHz
 GPU: AMD Radeon Vega 8 Graphics (radeonsi, raven, LLVM 16.0.6, DRM 3.57, 6.7.6-arch1-2)
 RAM: 5194MiB / 9884MiB
 - OpenSCAD Version   2024.03.02.ai18721 (git e3e5f8e0c), appimage

**Additional context**
It is displayed normally if applied: render()
But then the coloring of the colors of the cut surfaces is not displayed.
Function "manifold" may be enable or disable - does not affect. Other all function is off.
![image](https://github.com/openscad/openscad/assets/57869227/cd12095e-00be-476a-b443-f1d6cf7ffd87)

**Comment by kintel** [comment] 2024-03-03 21:34
This seems like a duplicate of the issue discussed at the bottom of #4861. Could you verify whether downgrading from Mesa 24 to Mesa 23 solves the issue?

**Comment by kberkut** [comment] 2024-03-04 04:45
> This seems like a duplicate of the issue discussed at the bottom of #4861. Could you verify whether downgrading from Mesa 24 to Mesa 23 solves the issue?

Downgraded the version. Yes, I confirm. Something has changed in the new versions of openscad, apparently there is a bug somewhere.

![image](https://github.com/openscad/openscad/assets/57869227/3542d458-adbd-497f-a42b-44b03d47b5e9)

**Comment by kintel** [comment] 2024-03-04 13:29
Thanks, closing as duplicate of #4861

**Closed by kintel** 2024-03-04 13:29 UTC
Labels: Type: Bug

**Comment by kintel** [comment] 2024-04-01 21:50
This was a bug in Mesa. Fixed in Mesa-24.0.4: https://docs.mesa3d.org/relnotes/24.0.4.html
