### ISSUE TITLE
Suggestion: Navigation with arrow keys

### ISSUE THREAD

**Issue by andyM92** [openscad/openscad#4448] opened 2022-12-13 11:29 UTC
It would be nice to navigate on the view window using the arrow keys on the keyboard. Shift + arrow key could be fast navigation.

**Comment by andyM92** [comment] 2022-12-14 19:43
> some 3D software using ASDW to move/strafe and arrows to rotate so you can walk a scene.

That's what I mean

**Comment by jordanbrown0** [comment] 2023-11-18 16:33
Duplicate of #3231.

**Closed by jordanbrown0** 2023-11-18 16:33 UTC
