### ISSUE TITLE
Crash when rendering (F6)

### ISSUE THREAD

**Issue by DisDis** [openscad/openscad#3356] opened 2020-06-13 15:20 UTC
OS: Ubuntu 19.10 64bit
Openscad 2019.05

Chash when rendering F6

reproduce file: https://github.com/DisDis/dslideshow/blob/4d6587bcdbe0f468278ad2e79303ef6b524e7d54/doc/photoframe_back_cover.scad

**Comment by t-paul** [comment] 2020-06-13 20:02
I can't reproduce the crash, but there's include files missing.

**Comment by thehans** [comment] 2020-06-13 21:17
I was able to reproduce, but the example requires downloading the rest of the repo, from which that link is just one of the files.

The issue appears to be with your included pcb models, which if rendered individually, give non-manifold warnings.  I think the reason they do is that the "blocks" on the boards are sharing the exact Z height as the face of the PCB, which can cause problems sometimes.  I would suggest offsetting those to slightly intersect with the board, which would hopefully workaround CGAL's strictness in this case.

And I'm not sure your goal, but typically in a model like this, the PCBs are only desired during F5 Preview as a mockup, and during render you would just want the case model.
You can achieve this by wrapping the last few lines of that file with `if($preview) { ... }`

Like this:
```
if ($preview) {
//RasPi4
translate([pcbRPi4X, pcbRPi4Y, pcbRPi4Z]) rotate(a=[0,0,-90]) raspberry4();


//Display Driver 
translate([(width-pcbDriverW)/2+pcbDriverW/2,(height-pcbDriverH)/2+pcbDriverH/2,back_thickness+10]) rotate(a=[180,0,-90]) translate([-pcbDriverW/2,-pcbDriverH/2,0])  pcbDisplayDriver();


//PoweDistib
translate([pcbPowerX, pcbPowerY, pcbPowerZ]) pcbPowerDistribution();
}
```

**Comment by DisDis** [comment] 2020-06-13 21:48
@thehans 
Thank you, I have a little experience with OpenScad.

> if ($preview) {

This fixes the crash.

How can I help with the problem? Or should I close issue because there is a workaround.
@ t-paul , you should clone the repository because photoframe_back_cover.scad needs other files.

**Comment by t-paul** [comment] 2020-06-13 21:52
It would still be interesting to find the reason for the crash. There's some chance it's caused by #2847.

**Comment by DisDis** [comment] 2020-06-13 21:57
@t-paul How can I get data(log and etc.) to verify this guess?

**Comment by kintel** [comment] 2024-03-31 01:49
Status as of 2024-03-24: Doesn't crash any longer, but doesn't produce an entirely correct geometry with neither CGAL or Manifold.

**Comment by pca006132** [comment] 2024-09-05 14:44
Is this correct? I am testing #5282

![image](https://github.com/user-attachments/assets/a2f4d262-436d-436d-a4df-3af7f1bfbbc2)

**Comment by kintel** [comment] 2024-09-19 23:54
Seems to work well with Manifold. Also no longer crashes with CGAL.
Closing this.

**Closed by kintel** 2024-09-19 23:54 UTC
Labels: Dep: CGAL, Tag: Manifold
