### ISSUE TITLE
Model/COM/NMR_DLLInterfaces.h missing in lib3mf 2.0.0

### ISSUE THREAD

**Issue by hroncok** [openscad/openscad#3300] opened 2020-05-05 18:45 UTC
Hello. After many years of stalled https://github.com/3MFConsortium/lib3mf/issues/8 I've finally packaged lib3mf for Fedora, only to realize Model/COM/NMR_DLLInterfaces.h (used by OpenSCAD) is no longer in the packaged version 2.0.0.

I'm opening this ticket in order to figure out if (and how) it is viable to migrate to lib3mf 2.0.0.

**Comment by t-paul** [comment] 2020-05-05 18:49
Duplicate of #3116.

**Closed by t-paul** 2020-05-05 18:49 UTC

**Comment by hroncok** [comment] 2020-05-05 18:52
Sorry for not searching properly.

**Comment by t-paul** [comment] 2020-05-05 18:54
No problem. Nice to see lib3mf moving into distros. Even though I don't have much time to update the Debian part.
