### ISSUE TITLE
Localization detection seems a little agressive on OSX

### ISSUE THREAD

**Issue by dmonego** [openscad/openscad#2545] opened 2018-11-01 23:58 UTC
I've installed Openscad on OSX and everything is configured to be in Russian. I have installed Russian compatibility and a Russian keyboard, but I am very much a novice speaker of Russian, and am unable to navigate the application to find the localization setting. 

I'm sure I'll figure that one out, but this is an unexpected result given that my machine is configured to use english.

This is using the following versions:
OpenSCAD 2015.03-3
OSX 10.12.6

**Comment by t-paul** [comment] 2018-11-02 00:10
Closing as duplicate of #1813.

You can disable localization in the preferences dialog.

**Closed by t-paul** 2018-11-02 00:10 UTC
