### ISSUE TITLE
2020.12-RC3 editor - copy/paste with Ctrl+Insert/Shift+Insert

### ISSUE THREAD

**Issue by ofmetal** [openscad/openscad#3560] opened 2020-12-29 15:51 UTC
Subj worked well in 2019.05 release, but now it is not. Still there is a way to copy/paste with Ctrl+C/Ctrl+V , but that is inconvenient.

**Comment by t-paul** [comment] 2020-12-29 15:54
Duplicate of #3558.

**Closed by t-paul** 2020-12-29 15:54 UTC
