### ISSUE TITLE
Export multiple volumes from a single script

### ISSUE THREAD

**Issue by kvtorp** [openscad/openscad#4809] opened 2023-11-04 21:51 UTC
With the proliferation of multi-color and multi-material 3D printers, I am starting to miss a feature to export multiple volumes from a single file, for later import into the slicer.
Specifically, the feature should:
* Trigger a separate export (either as a separate object in multi-object files suchs as 3MF, or as separate files for formats such as STL)
* Accept a label argument, used for naming the object in the export (3MF) or as suggested file name (STL)
* Prevent the indicated volumes from being automatically joined with any other parts of the model they touch (see example below)

So that a model like this:
```
volume("bottom") {
  difference() {
    Base();
    Modifier();
  }
}

volume("top") {
  intersection() {
    Base();
    Modifier();
  }
}

module Base() {
  cube(10);
}
module Modifier() {
  translate([-5, -5, 5])
    cube(20);
}
```
Would import into the slicer like this:
![image](https://github.com/openscad/openscad/assets/13795782/f4e8fd43-1906-49e2-9c74-f36d0a3d61c1)
![image](https://github.com/openscad/openscad/assets/13795782/db9db8c6-e468-4661-a965-05623caabaa4)

I am suggesting volume(), as it would directly affect the volume count at render.

**Comment by t-paul** [comment] 2023-11-04 22:27
Duplicate of #1608.

**Closed by t-paul** 2023-11-04 22:27 UTC
Labels: Type: Enhancement

**Comment by kvtorp** [comment] 2023-11-04 22:45
Argh, I didn't find it when I searched... Yes, it is a duplicate of the parts() operator
