### ISSUE TITLE
Unable to access files containing non-English letters in the path

### ISSUE THREAD

**Issue by coder2999** [openscad/openscad#5419] opened 2024-11-10 22:03 UTC
OpenSCAD is unable to access files containing non-English characters in the path from version 2024.10.28.

Any version of OpenSCAD is unable to use Ctrl+Click to open "include" or "use" files if the paths of these files contain non-English characters.

**Comment by hzeller** [comment] 2024-11-10 22:09
What operating system are you on ?

**Comment by thehans** [comment] 2024-11-11 04:27
Please paste your "Library Info" (from the Help toolbar, or using `openscad --info` option from command line).

Could you also provide an example file name and exactly how are you opening it (e.g. from File -> Open File dialog, or command line, etc)

**Comment by coder2999** [comment] 2024-11-11 20:06
I tested OPENSCAD on Windows 10 and 11 (English), version 2021.01 and version 2024.11.11.

For example, OPENSCAD cannot open "c:\пицца.scad", but it can open "c:\pizza.scad".

**Comment by thehans** [comment] 2024-11-11 20:14
Duplicate of #113

**Closed by thehans** 2024-11-11 20:14 UTC
Labels: Type: Bug
