### ISSUE TITLE
Can't open file directly from finder (macOS)

### ISSUE THREAD

**Issue by Fr3d-P** [openscad/openscad#3307] opened 2020-05-09 16:55 UTC
On macintosh, if I double-click a .scad file, the Finder launch openSCAD, but I end-up in the welcome... window when "show welcome screen" is checked in preferences.

The welcome window should appear only when opening openSCAD directly, not when opening a file (more that that, in this window, I don't see any way to continue opening this file, I have to select it again after clicking on  the button "open".

**Comment by t-paul** [comment] 2020-05-09 16:57
Which version is it? If possible please also check with the latest development snapshot.

**Comment by jarekmodra** [comment] 2020-05-15 05:12
I'm getting the same issue with 2019.05 and 2020.05.12

**Comment by vincentl** [comment] 2020-05-15 11:56
If openSCAD is already running (even if the welcome screen is open), double clicking a file in the Finder correctly opens the file in openSCAD.

Guessing that the QEvent::FileOpen event arrives before the SCADEventFilter is registered, but haven't been able to validate that yet.

**Comment by linuxdan** [comment] 2021-03-06 23:45
FWIW, I am using macOS 10.15.7 and OpenSCAD 2021.01 and double-clicking a .scad file works just fine.

**Comment by 3Dietrich** [comment] 2022-01-20 17:00
I am using macOS 12.0.1
in OpenScad version 2021.01 
AND OpenSCAD version 2022.01.20

I confirm this bug. @kintel

**Comment by kintel** [comment] 2022-01-20 23:38
Thx, I can reproduce this as well

**Comment by kintel** [comment] 2024-12-03 04:03
Closing as duplicate of #2682

**Closed by kintel** 2024-12-03 04:03 UTC
Labels: OS: macOS, Type: Bug, Test-with-Qt6
