### ISSUE TITLE
New type of CGAL ERROR: assertion violation!

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#1026] opened 2014-11-20 06:21 UTC
2014.03, and I suspect snapshots too - still looking.
I added import()s which caused this error.
Still checking the quality of the STLs and will try to get to a minimal example.

```
Compiling design (CSG Tree generation)...
ECHO: [2014, 3, 0]
ECHO: "hello"
Rendering Polygon Mesh using CGAL...
CGAL error in CGAL_Build_PolySet: CGAL ERROR: assertion violation!
Expr: check_protocoll == 0
File: /home/don/openscad_deps/mxe-w64/usr/x86_64-w64-mingw32/include/CGAL/Polyhedron_incremental_builder_3.h
Line: 199
PolySets in cache: 6
PolySet cache size in bytes: 758400
CGAL Polyhedrons in cache: 56
CGAL cache size in bytes: 7836384
   Top level object is a 3D object:
   Simple:        yes
   Vertices:      436
   Halfedges:    1308
   Edges:         654
   Halffacets:    440
   Facets:        220
   Volumes:         2
Total rendering time: 0 hours, 0 minutes, 2 seconds
Rendering finished.
```

**Comment by kintel** [comment] 2015-01-22 23:38
This is a duplicate of #945 - edge flip in MeshLab makes the STL work correctly

**Closed by kintel** 2015-01-22 23:38 UTC
Labels: CGAL, STL-related
