### ISSUE TITLE
CGAL error, performing boolean ops on imported meshes and primitives

### ISSUE THREAD

**Issue by Mazaw** [openscad/openscad#220] opened 2012-11-24 18:30 UTC
Not sure if this is a known issue and referenced in a more technical bug report, but I'll submit this anyway since I can't see anything like it.

Using the following simple code, I'm able to generate this error message:

CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation!
Expr: pe_prev->is_border() || !internal::Plane_constructor<Plane>::get_plane(pe_prev->facet(),pe_prev->facet()->plane()).is_degenerate()
File: /media/code/mingw-cross-env/usr/lib/gcc/i686-pc-mingw32/4.6.2/../../../../i686-pc-mingw32/include/CGAL/Nef_3/polyhedron_3_to_nef_3.h

```difference()
{
	import("X_Carriage_4_LM8UU_Richrap_Snapfit_Carriage_REV4_001_X_Fan_side_ready_to_print.stl");
	#translate([38,16,5]) cube([5,2,45]);	
}

```

The code references an STL file downloaded here: http://www.thingiverse.com/thing:19590

Also worth noting, the regular F5 renderer also doesn't display properly, showing a bunch of projected white holes. I've been doing a lot of CSG against imported STL files lately and while it never seems to look right pressing F5, I've been able to count on it working when pressing F6.

Tested in Latest release and Latest Snapshot for Windows

**Comment by kintel** [comment] 2015-01-22 17:09
Closing as duplicate of #945

**Closed by kintel** 2015-01-22 17:09 UTC
Labels: STL-related
