### ISSUE TITLE
Bad geometry - holes & degenerates

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2868] opened 2019-03-15 01:46 UTC
This is with RC3, it is worse than with 2015.
Starting from where I noticed a problem,  looks  very bad.
![Capture bf-bad](https://user-images.githubusercontent.com/1972961/54400934-6245b200-4719-11e9-9012-305a5be39e10.JPG)
In a nut shell that is a result of the following, the minkowski takes an hour, so I'll save you from the full code.
```
minkowski() scale([0.15,0.15,1]) linear_extrude(height=1.5, convexity=16) offset(-0.75) union() difference() union() text("𒄉", size=96, font="Akkadian:style=Regular",$fn=36);
```
Reducing it finds scale introduces degenerate faces: (note this is inverted compared to above)
![Capture bf-bad-offset](https://user-images.githubusercontent.com/1972961/54401349-67a3fc00-471b-11e9-9385-1bd3fe805de4.JPG)

The concentration of 'bad' in the top image correlates to the degenerations.
So I presume it is 'expected' that the further processing of the minkowski() will cause the nastiness??

I went back to 2015.03, it has 1/3rd of the degenerations than RC3, just those at the lips:
![Capture-bf-bad-scale-2015](https://user-images.githubusercontent.com/1972961/54401562-590a1480-471c-11e9-9aa3-6e349ece6301.JPG)

So, is it concerning that RC3 is worse than 2015? (note I haven't tried the full minkowski on 2015 yet)

If you want to replicate exactly, you'll need [the font](https://fontlibrary.org/en/font/akkadian), &
```
$fs=1.25; 
$fa=3;
//minkowski() 
  {
   scale([0.15,0.15,1])  
      linear_extrude(height=1.5, convexity=16) {
        offset(-0.75)
          union() {
            difference() {
              union() {
                text("𒄉", size=96, font="Akkadian:style=Regular",$fn=36);
                translate([105,83,0])
                  circle(d=12);
                translate([153,57,0])
                  circle(d=13);
              }
              translate([105,84,0])
                #circle(d=6);
              translate([153,57,0])
                #circle(d=5);
            }
            translate([190,36,0])
              circle(d=10);
            translate([190,44,0])
              circle(d=10);
            }
        }
    
  sphere(0.25,$fn=18);
  }
```

BTW if I change the order to scale([0.15,0.15,1]) minkowski() ... I get this (reused the cache as it ran in 0s)
![Capture-f-bad-s-m](https://user-images.githubusercontent.com/1972961/54402355-d2573680-471f-11e9-9056-7d5fac07d3cf.JPG)

So something funny in there somewhere...

**Comment by MichaelAtOz** [comment] 2019-03-15 02:44
Actually it looks like offset() may be the cause.
```
//minkowski() 
  {
   scale([0.15,0.15,1])  
      linear_extrude(height=1.5, convexity=16) 
    {
        //offset(-0.75)
          union() {
...
```
Is clean:
![Capture-bf-bad-not-offset](https://user-images.githubusercontent.com/1972961/54403637-de91c280-4724-11e9-8e06-f08ee00483fd.JPG)

If I tram the lip circles to change the angle of incidence (re adding the offset) it goes away:
![Capture-bf-bad-not--trammed-offset](https://user-images.githubusercontent.com/1972961/54404611-3a117f80-4728-11e9-9390-904b433a5edf.JPG)
and the other two locations are no longer degenerate.

**Comment by MichaelAtOz** [comment] 2019-03-15 02:57
AAArrrgh! The second above was without scale(), re-add that and those other two locations reappear:
![Capture-bf-bad-not--trammed-offset-scaled](https://user-images.githubusercontent.com/1972961/54405149-c6707200-4729-11e9-88f0-68aecbf97923.JPG)
Offset & scale are presumably having floating point differences of opinion.

**Comment by MichaelAtOz** [comment] 2019-03-15 05:02
The full minkowski in 2015, ie the same as the very first image, no holes, so RC3 is producing worse output than 2015.
![Capture bf-bad-2015](https://user-images.githubusercontent.com/1972961/54406006-865ebe80-472c-11e9-8490-44fd6bd13e6c.JPG)

**Comment by MichaelAtOz** [comment] 2019-03-15 05:09
With a positive offset() it produces different degenerations.
```
//minkowski() 
  {
   scale([0.15,0.15,1])  
      linear_extrude(height=1.5, convexity=16) {
        offset(0.5)
          union() {
```
![Capture-bf+offset scale](https://user-images.githubusercontent.com/1972961/54409725-561f1c00-473c-11e9-8d62-600a5677a183.JPG)

Again only with both scale() & offset(), either by themselves doesn't degenerate.

**Comment by kintel** [comment] 2019-03-15 11:19
If you have a good workflow for detecting this, would it be possible to find the smallest possible example using a more common font?
Alternatively, reproduce this by exporting to DXF/SVG or a 2D polygon and making it break again on import?

**Comment by MichaelAtOz** [comment] 2019-03-15 23:58
```
$fs=1.25; 
$fa=3;
   scale([0.15,0.15,1])  
      linear_extrude(height=2, convexity=16) 
        offset(-0.75)
          import("babel-fish.dxf");
```
[babel-fish.dxf.txt](https://github.com/openscad/openscad/files/2973101/babel-fish.dxf.txt)

As above:
![Capture-bf-dxf-offset](https://user-images.githubusercontent.com/1972961/54464722-e9ebf900-47cb-11e9-9ad7-b5132d8073c7.JPG)
Offset(+0.75):
![Capture-bf-dxf+offset](https://user-images.githubusercontent.com/1972961/54464747-0720c780-47cc-11e9-8dd0-2528c9ff981d.JPG)

**Comment by MichaelAtOz** [comment] 2019-03-16 00:13
With a built in font. I chose those glyphs semi-randomly with complex angles & some holes.
```
$fs=1.25; 
$fa=3;
   scale([0.15,0.15,1])  
      linear_extrude(height=2, convexity=16) {
        offset(-0.75)
          text("₡₢₥₦₩₯₱₳", font="Liberation Serif:style=Regular", size=96, spacing=0.75 ,$fn=36);
      }
```
![Capture-liberation](https://user-images.githubusercontent.com/1972961/54467832-caf56300-47db-11e9-8cf3-726fe8fcb9b6.JPG)

Simpler, just "₯₱"
![Capture-liberation-dp](https://user-images.githubusercontent.com/1972961/54467935-874f2900-47dc-11e9-9419-b203dcec6c01.JPG)

**Comment by nophead** [comment] 2019-03-30 18:53
Does it work if you do the scaling in 2D before the linear extrude?

**Comment by MichaelAtOz** [comment] 2019-03-30 21:44
No.

**Comment by MichaelAtOz** [comment] 2019-04-08 03:20
#2915 is producing degenerate faces too, and involving the 'small number' problem.
On reflection this, babel-fish/text, issue may be 'small number' problems too.
I'm wondering whether offset() brings in another floating point operation? Yes, Clipper.
With the intricate curvature of glyphs, points being minutely separated, floating point producing some equivalent to ['Brownian motion'](https://en.wikipedia.org/wiki/Brownian_motion). 
I notice CLIPPER_SCALE = 65536, as Clipper is Integer based, it converts both ways introducing more uncertainty. I'm wondering if that and the GRID is causing noise?
Perhaps that is the point to do some mesh repair?
Where are the Heisenberg compensators :/

**Comment by nophead** [comment] 2019-04-08 08:27
Clipper itself is supposed to be very robust with respect to self intersections, etc, and I don't think I have seen problems in 2D. I have used offset(0.01) to clean up a bad SVG before linear extruding it.

Yes any snap to grid or truncation to lower precision will break things. OpenSCAD does that all over the place with int64 to double, double to float, rational to double and some explicit grid snaps, which can be finer than the resolution of float as you move away from the origin.

**Comment by donbright** [comment] 2019-05-02 03:26
Clipper also does a large amount of converting from Integer to Double and back again, although it is very robust in general.  But Clipper converting to Int64 is essentially a form of "grid snap".

OpenSCADs floating point grid size could, in theory, be settable at runtime, so that these types of tests could be done by ordinary users to debug the engine better, without having to try to compile the program themselves with a modified gridsize. Also its called a grid but its actually not a "regular grid" so much as a "rectangular mesh" (since its based on floating point binary numbers, which do not form a regular grid  in space).

Different OpenSCAD-grid sizes, in and of themselves, will produce a performance change of maybe 10-20% depending - this is because the Rational Number math of CGAL, well, when you use a grid size that equates to an exact fraction of a binary number, the Double->Rational conversion produces a fewer number of digits in the resulting Rational denominator and numerator. This is expressed in the Bignum routines of MPFR/GMP taking less time to walk through the 'legs' of the Big Integers that  underly their Rational number math.

**Comment by MichaelAtOz** [comment] 2020-12-15 07:56
I'm revisiting some issues with 2020.12.RC2.

This one seems fixed.
It would be interesting to have conjecture on why?

The non-minkowski version above had zero self-intersections.
Zero with minkowski too:
![Capture-babelfish-rc2-minkowski](https://user-images.githubusercontent.com/1972961/102186575-f05e5600-3f06-11eb-940b-94d8dfff894c.JPG)

Tho apparently double render time, I will need to confirm this. So not closing the issue yet.

**Comment by thehans** [comment] 2020-12-31 21:37
> This one seems fixed.
> It would be interesting to have conjecture on why?

Possibly from changes to how large text is scaled (#3263)
Previous code had limited precision to glyph scaling, which may have led to some self-intersection/degenerate polygon edges etc.

**Comment by kintel** [comment] 2024-03-30 22:02
Closing as this seems to be fixed and probably not worth chasing why

**Closed by kintel** 2024-03-30 22:02 UTC
Labels: Type: Render Issue
