### ISSUE TITLE
Square bracket ( "[" ) issue on some keyboard layouts

### ISSUE THREAD

**Issue by tehcereal** [openscad/openscad#872] opened 2014-07-13 13:16 UTC
There is an issue when I try to type square brackets in the editor my shortcut for the character is altgr+F and openscad treats it like I pressed Ctrl+Alt+F (Find and replace) menu. The ] character works as its should. If I press the [ shortcut (altgr+f) when the menu is open it just highlights the text box. I'm using Windows 8.1 and OpenSCAD 2014.03 and my keyboard layout is Croatian but i think the problem occurs on every layout that has the [ character on altgr+f combination.

**Comment by AakaFosfor** [comment] 2015-08-26 07:59
I've solved this issue by using an external editor - actual stable version of OpenSCAD is hooked-up on the opened file and automatically re-displays when I save the file in my editor.

**Comment by kuzfix** [comment] 2015-11-18 10:28
Ctrl+Alt+F is standard shortcut for "[" on a lot of keyboard layouts (Slovene in my case). It would be nice if the developers either didn't use it for anything or make it possible to customize the shortcuts. Write now I still use an external editor the way AakaFosfor describes since this shortcut clash renders the built-in editor practically unusable.

**Comment by kintel** [comment] 2015-11-18 15:52
@kuzfix Which OS are you on?

**Comment by kuzfix** [comment] 2015-11-19 06:49
Hello @kintel. I am currently using Windows 10, but I had the same issue with some other programs as well on windows XP, 7 and 8.1. 
The Right alt (altgr) on Slovene keyboard acts as Ctrl+Alt and in combination with some characters gives square brackets and similar. Therefore any program that uses Ctrl+Alt+ any of those characters for a shortcut will not allow me to use any of those characters.

If it is any help, here is a short list of the most problematic shortcuts:
Ctrl+Alt+f   -   "["
Ctrl+Alt+g   -   "]"
Ctrl+Alt+v   -   "@"
Ctrl+Alt+b   -   "{"
Ctrl+Alt+n   -   "}"
Ctrl+Alt+q   -   "\"
Ctrl+Alt+w   -   "|"
Ctrl+Alt+e   -   "€"
Ctrl+Alt+1   -   "~"
Ctrl+Alt+2   -   "ˇ"
Ctrl+Alt+3   -   "^"
Ctrl+Alt+5   -   "°"

Here is a link to a picture of a Slovene keyboard: 
http://www.shrani.si/f/1G/lI/4uw1nCMk/g80-3000-lsmsl.jpg

Whatever symbol is in the lower right corner of a key will get typed if you press Ctrl+Alt+"that key".

I am not sure if it is the same in linux, but I can ask a friend of mine.

With kind regards,
Matic

**Comment by AakaFosfor** [comment] 2015-11-19 08:11
Hi, it's very similar with Czech keyboard layout (on whatever Windows version). And if I remember correctly, also some Linuxes (when Czech layout is set) use these shortcuts.
Cheers, Fosfor

**Comment by miharix** [comment] 2016-05-04 18:41
Is this bug totally ignored?
I normally use older version of OpenSCAD under Ubuntu and I love it!
But now I'm writing a paper article how to use it for beginners _(magazine targeted to older school kids)_ and see that under Win7 freshly installed OpenSCAD-2015.03-2-x86-64-Installer.exe still has for a beginner this ultra annoying bug.
It affects et least 6 different country’s (https://en.wikipedia.org/wiki/QWERTZ). 
**Please fix this as son as possible.**

**Comment by doug-moen** [comment] 2016-05-04 19:47
The primary purpose of the Alt key (Option key on the Macintosh) is for typing non-ASCII characters. It's used in different ways by different international input mechanisms, and we can't realistically keep track of them all.

My suggestion is to simply avoid using the Alt key in command shortcuts. As far as I know, the only command shortcut in OpenSCAD that uses Alt is Ctrl+Alt+F for Find and Replace. If we change this to Ctrl+Shift+F then the problem is solved. No need to find a developer with a Czech keyboard.

**Comment by miharix** [comment] 2016-05-04 20:06
@doug-moen Yes, that would be great solution for the problem. 
Probably no need for implementing custom shortcuts.

**Comment by MichaelAtOz** [comment] 2016-05-04 21:59
There are a few Alt shortcuts in [Qt](http://doc.qt.io/qt-5/qkeysequence.html )

**Comment by kintel** [comment] 2016-05-04 23:46
On Mac it's common to use Alt (aka. Option) to trigger variations of shortcuts. e.g. Cmd-Alt-F is used for Search&Replace on OS X' TextEdit.

**Comment by doug-moen** [comment] 2016-05-05 01:12
On Windows, the AltGr key (found on many non-English keyboards) is used to type non-English characters. But AltGr is missing from some keyboards, so Windows lets you simulate it with ctrl+alt.

reference: https://en.wikipedia.org/wiki/AltGr_key
quote: "To allow the specific functionality of AltGr when typing non-English text on such keyboards, Windows allows it to be emulated by pressing the Alt key together with the Control key:
   Ctrl+Alt ≈ AltGr
Therefore, it is recommended that this combination not be used as a modifier in Windows keyboard shortcuts as, depending on the keyboard layout and configuration, someone trying to type a special character with it may accidentally trigger the shortcut,[5] or the keypresses for the shortcut may be inadvertently interpreted as the user trying to input a special character."

While it's true that Qt has some standard Alt shortcuts, none of them use the Alt+Ctrl combination. Also, Qt never combines Alt with a printable character, only with other control keys like Backspace, Enter, Left and Right. The Qt shortcuts don't create this problem.

**Comment by doug-moen** [comment] 2016-05-05 01:32
@kintel said: "On Mac it's common to use Alt (aka. Option) to trigger variations of shortcuts. e.g. Cmd-Alt-F is used for Search&Replace on OS X' TextEdit."

I don't think that Cmd-Alt on the Mac creates the same problem as Ctrl-Alt does on Windows/Linux systems.

My other comment is that "Find and Replace" is commonly bound to Ctrl-H on non-Mac systems: eg, in Linux gedit, in Windows notepad, in Microsoft Word, etc. Using Alt+Ctrl+F instead of Ctrl+H on those systems is doubly bad: it's non standard, and it blocks the altgr functionality.

We can't use Cmd-H on the Mac for Find and Replace, since that means Hide Application. Can we use different shortcuts on Mac vs non-Mac?

**Comment by kintel** [comment] 2016-05-05 02:00
@doug-moen Makes sense. We should be able to just map it differently for non-Mac.

**Comment by doug-moen** [comment] 2016-05-05 10:34
The Find and Replace shortcut  is defined in src/MainWindow.ui, an XML file which contains:
```
  <action name="editActionFindAndReplace">
   <property name="text">
    <string>Fin&amp;d and Replace...</string>
   </property>
   <property name="shortcut">
    <string>Ctrl+Alt+F</string>
   </property>
  </action>
```
It's easy to change the shortcut to Ctrl+Shift+F for all platforms (my first suggestion).

But how do you put the equivalent of #ifdef MACOS into this XML file? It would be very ugly to maintain Mac and non-Mac versions of this file, just for a 1 line change.

**Comment by kintel** [comment] 2016-05-05 18:38
See https://github.com/openscad/openscad/blob/master/src/mainwin.cc#L341

We could add smth. like ```this->editActionFindAndReplace->setShortcut(SOME_SHORTCUT)```

**Comment by Sastas** [comment] 2016-05-10 07:48
There is any solution for non-prefessional users? I just want to start openSCAD, but ran into this error. It was an issue back to 2009, so its should be fixed now..

**Comment by miharix** [comment] 2016-05-11 19:25
Is in the code some part like "On first run do..." so it could run a query about OS name (https://wiki.qt.io/Get_OS_name) and str_replace the problematic line in XML?

**Comment by kintel** [comment] 2016-05-12 16:25
@miharix See my comment above - the best is to just set the shortcut in C++. No need to hack around in XML files, they're all compiled to C++ anyway.

**Comment by miharix** [comment] 2016-05-12 19:21
@kintel I don't like to sound impolite, especial that I really like OpenScad.
 But as I said, I wrote a paper article how to use it for beginners (magazine targeted to older school kids) and this magazine issue will be shipped 2.6.2016 and being the only magazine in its topic in our country it will be read by many kids. And I'm afraid that this [ has potential to demotivate many young readers to start to use OpenScad or worse, to demotivate them to try to learn any programming language in the future.

So please is there any chance, that this gets fixed and public available before 2.6.2016? 
If it helps a little I'm also wiling to donate all € that I get from publishing that article
_(unfortunately its symbolical number only enough for a pizza or two)_.
 Oh if you like more when people contribute their work than money... If you think its interesting I can translate my A4 cheat sheet _(http://miharix.eu/wp-content/uploads/2015/03/openSCAD_svinglc_Beta3.pdf)_ version to English _(but somebody would need to proof read it)_

**Comment by kintel** [comment] 2016-05-12 20:27
@miharix We most probably won't be able to make an official stable release in such short time, but we can fix this bug quickly and make a development snapshot release. You just have to instruct people to use the latest development snapshot until the next official version is released.

@t-paul Would you have the chance to kick off a Windows build if I fix this?

**Comment by t-paul** [comment] 2016-05-12 20:30
Sure, the build server is just waiting for something to do :).

**Comment by kintel** [comment] 2016-05-12 20:38
Fixed. Ping @t-paul.
@miharix You you five it a test once the binaries are uploaded?

**Comment by t-paul** [comment] 2016-05-12 22:15
@kintel Builds are [uploaded](http://files.openscad.org/snapshots/) but not linked yet.

**Comment by AakaFosfor** [comment] 2016-05-13 07:04
Jupi-je! I'm able to write [] in the in-build editor:) Thanks a lot:)

**Comment by miharix** [comment] 2016-05-13 14:10
@kintel & @t-paul I can also confirm OpenSCAD-2016.05.12 for keyboard Sl-si under Win7 64x, Win8.1 64x, Win10 32x the [ works great. Please link the files in download page.
Thanks for fixing this and compiling a working development snapshot.

**Comment by kintel** [comment] 2016-05-13 14:50
linked

**Closed by kintel** 2016-05-13 14:50 UTC
Labels: Low Hanging, Windows
