### ISSUE TITLE
OpenSCAD keeps asking for permission to access directories on Mac OS Ventura

### ISSUE THREAD

**Issue by jcwren** [openscad/openscad#4770] opened 2023-10-07 17:32 UTC
**Describe the bug**
I can have OpenSCAD 2023.09.04 (05b962168) on Mac OS Ventura open and working on a design. I hit Command-S to save it, and it asks for permission to access a directory that I've previously given it permission to access. This can also occur with exporting the STL. 

**To Reproduce**
Other than just using the program normally, there doesn't seem to be any specific steps that cause this to happen. It just periodically occurs. Closing and reopening OpenSCAD doesn't resolve the issue. I've not seen this happen with mid-2014 MacBook Pro running Big Sur 11.7.10 and a nightly build version that's several months old.

**Expected behavior**
I expect it it not to ask for permission to access directories I've previously given it access to.

**Environment and Version info (please complete the following information):**
Mac OS Ventura 13.5.2
MacBook Pro w/ Apple M2 Pro silicon
OpenSCAD 2023.09.04 (05b962168) nightly build

**Comment by t-paul** [comment] 2023-10-07 17:51
Duplicate of #4059.

**Closed by t-paul** 2023-10-07 17:51 UTC
Labels: Type: Bug
