### ISSUE TITLE
Prepending with `#` breaks syntax highlighting

### ISSUE THREAD

**Issue by Kreyren** [openscad/openscad#4016] opened 2021-12-19 00:36 UTC
![2021-12-19_01-35](https://user-images.githubusercontent.com/11302521/146659299-34ec94b9-49e4-460f-87df-423c8c3767e8.png)

### Expected
Highlight with `#` prepended

**Comment by t-paul** [comment] 2021-12-19 00:39
Now that is actually a duplicate of #1172.

**Closed by t-paul** 2021-12-19 00:39 UTC

**Comment by jordanbrown0** [comment] 2021-12-19 04:40
Workaround:

```
module hl() {
    #children();
}
hl() cube([x/2,y,x/2], center = true);
```

... but the trick of putting the `#` on the previous line is pretty clever.

Note that once you do this, you can do cleverer things like control the highlighting with a global variable:

```
module hl() {
    if ($highlight) {
        #children();
    } else {
        children();
    }
}
```
