### ISSUE TITLE
Errors and warnings would be more useful with a source line number attached

### ISSUE THREAD

**Issue by Ma-XX-oN** [openscad/openscad#1869] opened 2016-11-23 15:24 UTC
ERROR: Recursion detected calling function 'len' 
    WARNING: Ignoring unknown module 'fn'.

There are the types of reports given back to the user.  Not particularly helpful.  If something like this happens and a lot of code was generated/modified before these types of errors occur, then your just SOL and have to start hacking away at what is there, removing bits until the error/warning goes away.

Having a reference to a source file and line number (maybe the character number on the line?) to the parse tree nodes should allow for generating more useful messages to the user.

FYI:  The error above is usually caused by a recursion error but there is a `let()` variable injection in that function that calls `len()`.

**Comment by t-paul** [comment] 2016-11-23 15:35
Duplicate of #1843.

**Closed by t-paul** 2016-11-23 15:35 UTC
