### ISSUE TITLE
Closing app when there are unsaved files: After selection "Save All" app stays open

### ISSUE THREAD

**Issue by tarhytti** [openscad/openscad#3577] opened 2021-01-03 19:00 UTC
Hard to write proper title for the issue so here comes steps to reproduce situation:

1) open at least two files
2) edit both files (do not save them)
3) close openSCAD application from File menu or with close window -button
4) select "Save All":
![image](https://user-images.githubusercontent.com/16556018/103486397-420f4780-4e06-11eb-8366-1fb73edbbede.png)

Expected results:
5) all files are saved and openSCAD is closed

Actual results:
5) all files are saved and openSCAD is still open

**Comment by tombsar** [comment] 2021-01-03 20:17
Duplicate of https://github.com/openscad/openscad/issues/3556 ?

**Comment by t-paul** [comment] 2021-01-03 20:45
Yep, I think it's a duplicate, please re-check once RC5 is out (or with snapshot build >= 2021.01.03).

**Closed by t-paul** 2021-01-03 20:45 UTC
