### ISSUE TITLE
Export to path with spaces

### ISSUE THREAD

**Issue by darksnakezero** [openscad/openscad#2066] opened 2017-07-06 19:51 UTC
When using the export function under windows and you export to a path that contains spaces, nothing happens.

Export to a simple path without spaces does work.

"Save as" works as intended. If it is too complicated to fix, at least a warning\error would be nice.

**Comment by MichaelAtOz** [comment] 2017-07-06 20:34
Which version of OpenSCAD?
What type of export?
Can you give a specific example of the path & filename?
Did you use the dialogue box to select the directory, or did you type the directory/filename?

**Comment by MichaelAtOz** [comment] 2017-07-06 20:40
FIXME: [Export CSG](https://github.com/openscad/openscad/blob/a84da9a110b46543520f7e2e73e69b0f071c90db/src/mainwin.cc#L2228) needs to use [completeBaseName()](http://doc.qt.io/qt-4.8/qfileinfo.html#completeBaseName), not baseName().

**Comment by MichaelAtOz** [comment] 2017-07-06 21:03
I can't reproduce this with 2015.03. or a recent snapshot. Windows 7/64
@darksnakezero Also what version of Windows?

**Comment by darksnakezero** [comment] 2017-07-06 22:28
Windows: Windows 10 Pro 64 bit
Openscad: 2015.03

working path U:\output.svg
non-working: C:\Benutzer\L ö\Desktop\output.svg.

German version I use:
From the menu: Datei->"Speichern Unter" works
Datei->Exportieren->Select any option
Then "choose Filename and path" window opens, I select said path and it closes without doing the export.

English translations could be:
File ->"Save As" working
File -> Export-> Any option -> "choose filepath"   not working, filepath window closes without error, but doesnt save the file

**Comment by MichaelAtOz** [comment] 2017-07-07 00:19
a. Check the console for any error messages.
b. can you try it with a directory with a space, but no unicode chars.

**Comment by darksnakezero** [comment] 2017-07-07 02:50
a) No error in console
b)
Path "U:\a space\output.svg" working
Path "U:\örk\output.svg" NOT working
So the problem really is the 'ö'. It is not really needed to support those paths I guess, but I would expect some warning popup in that case :-)
Again, I am sorry that I didnt test enough before writing that bug report.

**Comment by MichaelAtOz** [comment] 2017-07-07 09:51
Reproduce unicode export issue.
Export as CSG works, others don't

https://github.com/openscad/openscad/blob/a84da9a110b46543520f7e2e73e69b0f071c90db/src/mainwin.cc#L2263 
Seems to be the way to go.

**Comment by kintel** [comment] 2017-08-04 17:42
This sounds very much like a duplicate of #113, which is addressed in #1296. I'm not too happy with the solution in #1296 though. Any ideas on how to improve this would be appreciated. Now that NoWide has been accepted into Boost it might be a more viable solution than before though..

**Comment by kintel** [comment] 2017-09-17 03:01
Closing as duplicate of #113

**Closed by kintel** 2017-09-17 03:01 UTC
