### ISSUE TITLE
GUI stuck during rendering

### ISSUE THREAD

**Issue by descampsa** [openscad/openscad#1970] opened 2017-03-19 21:18 UTC
When testing a minkowski() operation on a complex object, the preview rendering took a very long time (several minutes), and the gui was completely stuck during this time.
It would be nice to keep the preview rendering in a separate thread, and allow the user to cancel it if it takes too long.

**Comment by t-paul** [comment] 2017-03-19 21:19
Duplicate of #1195.

**Closed by t-paul** 2017-03-19 21:19 UTC
