### ISSUE TITLE
CGAL assertion violation

### ISSUE THREAD

**Issue by bgamari** [openscad/openscad#822] opened 2014-06-03 22:54 UTC
CGAL seems to barf while churning through [this](https://gist.github.com/bgamari/f8645049ff3b80900983) model with,

```
...
Geometry Cache insert: multmatrix([[1,0,0,0],[0,1,0,0],[0,0,1,- (960 bytes)
CGAL Cache insert: multmatrix([[1,0,0,0],[0,1,0,0],[0,0,1,2 (254112 bytes)
CGAL Cache insert: group(){multmatrix([[0.92388,-0.382683,0 (595096 bytes)
CGAL Cache insert: group(){multmatrix([[1,0,0,0],[0,1,0,0], (595096 bytes)
CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation!
Expr: e->incident_sface() != SFace_const_handle()
File: /usr/local/include/CGAL/Nef_S2/SM_const_decorator.h
Line: 326
```

This is with CGAL 4.4 and openscad 78803bfe1051a29aa5c257615c472b0f43563fdf.
##

**Comment by thehans** [comment] 2021-06-10 22:12
Unable to reproduce with 2021.06.07.nightly (git 5e1a7cd)
closing

**Closed by thehans** 2021-06-10 22:12 UTC
Labels: Dep: CGAL
