### ISSUE TITLE
Cannot save file in 2020.12rc2

### ISSUE THREAD

**Issue by amiga1985** [openscad/openscad#3545] opened 2020-12-20 00:10 UTC
Hi!
I am running the Linux appimage version of OpenSCAD on Ubuntu 20.04, and whenever I try to save a document, the program exits. What is causing this? Has it been patched yet?

**Comment by t-paul** [comment] 2020-12-20 00:14
Duplicate of #3523.

**Closed by t-paul** 2020-12-20 00:14 UTC
