### ISSUE TITLE
"$linenumber", "$currentmethod" for debugging echo statements

### ISSUE THREAD

**Issue by Jimw338** [openscad/openscad#4879] opened 2023-12-05 14:11 UTC
Special variables "$linenumber" and "$currentmethod" would be useful for debugging.  I'm tracking down a bug where an "undef" is passed as a parameter (explicitly) that is used in almost all the modules.  I'm left writing:

echo("$linenumber: [...]");

and then taking it into a text editor and replacing "$linenumber" in BBEdit with the help of LibreOffice or Excel, as detailed here:

https://stackoverflow.com/questions/26641522/textwrangler-line-number-in-a-replace-string

(Yeah, I know, a grep script could do this in 5 seconds, but I don't know grep)

**Comment by jordanbrown0** [comment] 2023-12-05 18:15
Duplicate of #380.

**Closed** 2023-12-05 18:16 UTC
Labels: Type: Enhancement
