### ISSUE TITLE
Crash with nested loops and complex math (normalization)

### ISSUE THREAD

**Issue by epicepee** [openscad/openscad#449] opened 2013-08-01 16:38 UTC
I am making a gyroid by calculating whether each location should be included in the shape -- Slow, but it works.  I am getting a crash when I set the resolution or range high enough, so that it is calculating >~10,000 cubes.  Interestingly, it doesn't happen when I duplicate the shape multiple times if the first doesn't crash, so it isn't just a limit on the number of shapes.  I am using 2013.06 x64 on Windows 8.  I will test older versions as soon as I can find where to download them.

```
range = 360; //Range. 360 is one "section".
res = 6; //Resolution.  Range/resolution=cubes on a side
reps = 0; //Repetitions.  0 is just one, 1 is two in every direction, etc.
num=0;

for(a=[0:reps], b=[0:reps], c=[0:reps]) translate([(range/res * a), (range/res * b), (range/res * c)]) {

    for(i=[0:res:range], j=[0:res:range], k=[0:res:range]){
        assign(num = ((cos(i) * sin(j)) + (cos(j) * sin(k)) + (cos(k) * sin(i)))) {
            if ((num < 0.2) && (num > -0.2)) {
                translate([(i/res),(j/res),(k/res)]) 
                    cube([1.05,1.05,1.05]); 
            }
        }
    }
}
```
##

**Comment by Witzany** [comment] 2018-08-02 15:07
Although this thread is a bit old, I hope this message finds you well. I think I have found a better way to create a gyroid 3D model with openscad. I calculate the points of the body and the indices of the triangles. With this data I create a polyhedron. The resolution and wall thickness can be chosen individually. This 3D model can then be rendered and converted to an stl file for further prosecution. Larger 3D models can be realised by placing mutiples of them with the periode 360. This should be done with the imported stl file. The openscad file is commented to see my programming ideas. There are no routines implemented, checking sense of input parameters. Therefore, if the wall thickness is too big or the pp value negative, you will obtain strange results. Please find my code enclosed.

[Gyroid.zip](https://github.com/openscad/openscad/files/2254009/Gyroid.zip)

**Comment by MichaelAtOz** [comment] 2018-08-04 00:55
@Witzany I haven't looked at you code, but something is wrong.
I just rendered the file, as is, it looks OK, but the console reports `Volumes: 9', so some bits are not joined.

**Comment by Witzany** [comment] 2018-08-04 21:04
Thank you for your response Michael!
I have previously checked the file with combined display (f12) and did not find any inverted faces. I have now checked the stl file with meshmixer and found some errors at the boundaries between the segments. Therefore I think it is not enough overlap between the segments. I will check it and post the new code after repair. With which display option s have you got the posted image?

**Comment by Witzany** [comment] 2018-08-04 21:41
As just posted, the scad file had a boundary problem. I had used tiny boundar, to avoid edge artefacts. This was not a good idea. Now the segments are a bit larger and therefore have anough overlap. Therer are some edge arterfacts, which can be ignored, as they are in the gyroid surface and disappear when translating the model. The outer edges should be cut by intersection or diffreence to the correct value after transforming to stl. Openscad still reports 2 volumes, but meshmixer does not report any error. The model should be printable.

[Gyroid.zip](https://github.com/openscad/openscad/files/2259829/Gyroid.zip)

**Comment by MichaelAtOz** [comment] 2018-08-04 23:27
> With which display option s have you got the posted image?

F5 & F12...
Interesting, I'm running via remote desktop (Windows RDP), when I do it on my actual PC I don't get the purple. Probably an OpenGL issue.

I also got them with you new code: (F5, F12 RDP)
![git 449-2](https://user-images.githubusercontent.com/1972961/43680940-c745a4be-9835-11e8-846c-b3dbc26263bc.JPG)
But don't get it without RDP.

But I am always wary when I see things like these: (F6)
![git 449-3](https://user-images.githubusercontent.com/1972961/43680954-13cb0068-9836-11e8-9a75-8ef27f10dd16.JPG)

I don't mean to be picky, but Meshlab shows two self intersections:
![git 449-5 ml](https://user-images.githubusercontent.com/1972961/43681237-9926666a-983d-11e8-9c5f-dbc397c9d7ab.JPG)

Personally I think your fix was not right, the surface is ugly.

> Openscad still reports 2 volumes

That's normal, one is the object, the other is the universe, ie NOT the object. 
[there's probably a better name for that...]

**Comment by Witzany** [comment] 2018-08-05 10:41
Thank you Michael for your help!
It's good news that 2 volumes are OK and the purple faces could be an OpenGL RDP issue. The artefacts you mentioned can be explained as following: 
If you delete the last three lines if the code by commenting and add the following line
polyhedron(points=points[0], faces=fi, convexity=3);
you will see, what I am really calculating. It is a very small part of the fundamental cell of the gyroid. I have used all possible mathematical symmetries to reduce this part as far as possible. These symmetries are:
f(x, y, z)=f(y, z, x)=f(z, x, y)
f(x, y, z)=f(180°-x,180°-y, 180°-z)

f(x, y, z)=f(360°-x, y, 180°+z)
f(x, y, z)=f(180°+x, 360°-y, z)
f(x, y, z)=f(x, 180°+y, 360°-z)
f(x, y, z)=f(x, 180°+y, 360°-z)
f(x, y, z)=f(360°-x, 180°y, z)
f(x, y, z)=f(180°-x, y, 360°-z)
f(x, y, z)=f(x, 360°-y, 180°-z)
f(x, y, z)=f(360°-x, 360°-y, 360°-z)
There are two main reasons to take advantage of all these identities. 
1. The gyroid equation solving is done numerically applying a nested intervalls an algorithm. The cacluation is done one one time, deriving all other points ba applying the identities.
2. The gyroid surface bends into all thre dimensions. In order to obtain a point of the gyroid surface one has to provide two coordinates and calculate the third one. 

If a surface is about horizontally flat, it is a good idea to provide x and y coordinates in form of a grid and calculate the z coordinate. On the other hand, if part of the surface is about vertically alligned, one will obtain huge troubles by this technique. As the gyriod surface bends in all directions, the only way to handle it, is to devide it into subsurfaces, which are not too steep in one specified direction. 

I have taken advantage from the identities mentioned above to create a small subsurface of the gyroid, which can be calculated by providig x and y coordiantes in form of a grid. This leads to a uniform point distribution. The first two lines of identities mentioned above are coordinate tranformations. Therefore the grids of subfaces will not match. This causes the artefacts you mentioned. As the calcualtion of the gyroid surface is done to an accuracy of about 10^-15, it is shure that the calcualted points are much preciser than the triangle resolution. Consequently the artefacts are smaller than the error caused by triangulation. If you increase the mesh desnsity by increasing the value pp to let's say 25 you will see that the artefact will be reduced accordingly. The numeric calculation is done one time only. Therefore not using the identities would havily increase calculation time without getting any increse of accuracy.

My first idea to create the gyroid was to combine all meshes according to identities of the frist two lines to one polyherdon. This approch would avoid artefacts at the boundaries, but the calculation of the faces matrix is extremely complex. It would be necessary to check for overlapping points in the mesh and delete these points. This leads to extreme consequences in the faces matrix. On the other hand, if I would let a gap between adjacent meshes, accuracy would be significantly reduced. In both cases it would be difficult to debug the code, as the behaviour of the code will be mesh density dependant. In my opinion code stability is an essential feature. May be I will find a better x, y calulation insead of a grid, avoiding this problem. I will think about this.

**Comment by MichaelAtOz** [comment] 2018-08-08 00:07
Almost there.
Self intersection, with your parameters:
![git 449v3-2 ml](https://user-images.githubusercontent.com/1972961/43808593-4928a83c-9a9d-11e8-85ed-9c4f14849098.JPG)
Just that one place.

Bad triangulation:
![git 449v3-3 ml](https://user-images.githubusercontent.com/1972961/43808640-73757c32-9a9d-11e8-9114-25d29677958d.JPG)
At more than one of those locations, ie artifact in the middle of the flat edge.
I don't know whether OpenSCAD did that (ie in union) or you told it to do that.

I suspect, without having grocked your algorithms, if you can fix those artifacts and the terminal condition causing them the irregularities may be fixed.

This one is much more visually pleasing.

> "When I'm working on a problem, I never think about beauty... but when I have finished, if the solution is not beautiful, I know it is wrong."
>R. Buckminster Fuller

**Comment by Witzany** [comment] 2018-08-08 09:07
Thank you Michael for your investigation!
I am wondering about the self intersection only one time. The model is produced by 48 polyhedrons which differ according to coordiante transformations. If there is one self intersecting face, I would expect 48 of them. 8 of the polyhedrons are just copies of the one with the intersectinf face. I am wondering that neither openscad nor meshmixer report an error. As the error is near the wedge, it can be a problem in my algrithm. In this region I had to implement some special cases in the faces matrix.

According to the bad triangulation I can promise that I am not responsible for it. My algorithm is symmetric. I think this is a consequence of numerics. I tried to avoid any overlaps in the visible region. Due to finite numerical resolution it is possible that openscad incorporates additional points when performing the union operator. Of course this has no effect on the model.

I have just cecked with smaller wall thickness (w=3 and w=1).  I didn't have the time for a test print, but the models slice well even with w=1. Both are correctly compiled without an error. But meshmixer reported a lot of errors not only in boundery regions of the model. Any repair leads to loss of faces. I think meshmixer has a problem with this geometry. Can it be that meshlab has problems with the complex geometry too?

**Comment by MichaelAtOz** [comment] 2018-08-08 23:07
a. I'm still looking

b.
> but the models slice well even with w=1. Both are correctly compiled without an error. 

Slicers are generally very flexibly and can cope with some common irregularities, so they are not reliable to debug geometry.

> I think meshmixer has a problem with this geometry. Can it be that meshlab has problems with the complex geometry too?

I'll have a look at MM, I haven't had issues with ML yet. And in this case I used Netfabb first, which showed anomalies which lead me to look with ML.

c. I'm looking into your code. I did the following, using animation (set steps to 6 in the GUI), it helps visualising;

```
step=floor($t*6+0.1);
gyroid_cell()	// apply coordinate transformations
for(i=[0:step]) 	// for every vector in matrix
	polyhedron(points=points[i], faces=(i%2==0) ? fi : f, convexity=100);	// create polyhedron of gyroid body
```

**Comment by MichaelAtOz** [comment] 2018-08-08 23:09
p.s. re c. to visualise, start with pp=3, then increase.

**Comment by MichaelAtOz** [comment] 2018-08-08 23:36
>  this is a consequence of numerics. I tried to avoid any overlaps in the visible region. Due to finite numerical resolution 

Now that I see how you are assembling the model, I agree. What I called anomalies are the pointy ends protruding. as they fan out around the common point, each will have that 'point' (but actually an edge intersection) based on floating point calculations, very close to each other, or possibly some actually equal.
OpenSCAD, and others, have problems with coincident faces or edges, this explains the self intersections and other geometry problems. I'm not sure what it does internally, but it has to somehow determine whether that point is inside or outside the others, when coincident it can't know for sure.

I'm still looking at the bad triangulation.

**Comment by thehans** [comment] 2020-06-04 10:57
I cannot recreate a crash from the original example using latest snapshot build.

There have been a few fixes to normalization stack usage since this bug was opened.  Closing as fixed

**Closed by thehans** 2020-06-04 10:57 UTC
Labels: Bug: Crash

**Comment by thehans** [comment] 2020-06-04 18:03
reference: #2886 and #3122
