### ISSUE TITLE
Warnings are not displayed when result is cached

### ISSUE THREAD

**Issue by knrafto** [openscad/openscad#2080] opened 2017-08-03 05:47 UTC
Pressing F6 like
```
difference() {
    cube(1);
    square(1);
}
```
results in 
```
WARNING: Mixing 2D and 3D objects is not supported. 
WARNING: Ignoring 2D child object for 3D operation 
```
as expected. Pressing F6 again results in the same output but no warning. Changing, say, `square(1)` to `square(2)` results in a warning again, but no warning is shown after changing back it back to `square(1)`. This could mislead users into thinking their input is correct.

One solution is to bundle warnings in the `Geometry`s themselves; this might also help with #225.

**Comment by t-paul** [comment] 2017-08-03 05:52
Duplicate of #454.

**Closed by t-paul** 2017-08-03 05:52 UTC
