### ISSUE TITLE
Incorrect line number in error messages

### ISSUE THREAD

**Issue by alanbernstein** [openscad/openscad#1658] opened 2016-06-03 23:48 UTC
Example:
`ERROR: Parser error in line 149: syntax error
ERROR: Compilation failed!`

But the scad file is 27 lines long. The single include is 125 lines long, and the reported line number is correct, when counting the lines from the include. This is not expected, it makes finding errors tedious.

**Comment by kintel** [comment] 2016-06-04 03:21
Closing as duplicate of #214

**Closed by kintel** 2016-06-04 03:21 UTC
