### ISSUE TITLE
New set of features: Caculations with graphical objects

### ISSUE THREAD

**Issue by zabrodas** [openscad/openscad#2072] opened 2017-07-24 15:28 UTC
1. Assign names to graphical objects:
For example:
`plate=cube([100,100,1]);`

2. Functions on objects:
Example:
`ball_on_plate=translate([plate.centerX(), plate.centerY(), plate.top()+5]) sphere(10,10,10);`

desired functions:
center - vector to center of object
centerX, centerY, centerZ - projections of center
right, left, top, bottom, front, back - min/max for each axis
num_vertices, num_faces, num_edges, volume - for debug and statistics
vertices - list of vertices

3. Hidden objects (helpers)
```
helper=union() {
    cube([1,1,1]);
    rotate([45,20,0]) cube([1,1,1]);
}
for (v=helper.vertices()) {
    translate(v) sphere(r=0.2);
}
helper.hide();
```

**Comment by t-paul** [comment] 2017-07-24 17:25
Duplicate of #301.

**Closed by t-paul** 2017-07-24 17:25 UTC
