### ISSUE TITLE
Wireframe doesn't render on simple geometry

### ISSUE THREAD

**Issue by gabrielrobinson000** [openscad/openscad#3796] opened 2021-06-01 06:17 UTC
This is a simple object that doesn't render on wireframe, adding anymore geometry causes it to render.
```
//cube(.1); //<==anymore geometry
polyhedron([[0,0,0],[1,0,0],[0,0,1],
            [0,1,0],[1,1,0],[0,1,1]],
           [[2,1,0],[3,4,5],[0,1,4,3],
            [0,3,5,2],[1,2,5,4]]);
```
It was test on the current master version 1a9430fba435c3b3758988dbf80f94cb2f0423c6 .

**Comment by t-paul** [comment] 2021-07-26 23:52
Duplicate of #2031.

**Closed by t-paul** 2021-07-26 23:52 UTC
