### ISSUE TITLE
Preview stopped working properly since Ubuntu 17.10 update

### ISSUE THREAD

**Issue by theopensourcerer** [openscad/openscad#2157] opened 2017-10-30 13:01 UTC
(Mentioned originally in #1409)

Since upgrading Ubuntu from 16.10 to 17.10 a few days ago the preview quite often simply disappears from the viewport. Pressing F6 to render it works fine. If I quit OpenSCAD and open it again with the same design file, the preview is visible again but once I change something and save it then (mostly) disappears and I have to do a F6 to get back a drawing.

I am not sure if this is something to do with the new Weyland graphics or Gnome desktop, an update to OpenSCAD (am using the Ubuntu packaged version of OpenSCAD) or something else?

**Comment by t-paul** [comment] 2017-10-30 13:04
Can you please add the output of `Help`->`Library Info`.

**Comment by theopensourcerer** [comment] 2017-10-30 13:10
No problem. Will do it tonight when I get home. Thanks.

**Comment by theopensourcerer** [comment] 2017-10-30 17:33
Here you go:

OpenSCAD Version: 2015.03-2
System information: Linux 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 Ubuntu 17.10 4 CPUs 15.55 GB RAM
Compiler: GCC "6.2.1 20161124" 64bit
Boost version: 1_62
Eigen version: 3.3.0
CGAL version, kernels: 4.9, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.4.0
Qt version: 5.9.1
QScintilla version: 2.9.3
MingW build: No
GLib version: 2.51.0
Application Path: /usr/bin
Documents Path: /home/alanlord/.local/share
Resource Path: /usr/share/openscad
User Library Path: /home/alanlord/.local/share/OpenSCAD/libraries
User Config Path: /home/alanlord/.config/OpenSCAD
Backup Path: /home/alanlord/.local/share/OpenSCAD/backups
OPENSCADPATH: /home/alanlord/Personal/OpenSCAD_Libraries
OpenSCAD library path:
/home/alanlord/Personal/OpenSCAD_Libraries
/home/alanlord/.local/share/OpenSCAD/libraries
/usr/share/openscad/libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 2.0.0
OpenGL Version: 3.0 Mesa 17.2.2
GL Renderer: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
GL Vendor: Intel Open Source Technology Center
RGBA(8880), depth(0), stencil(0)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Using QOpenGLWidget

GL Extensions:
GL_3DFX_texture_compression_FXT1
GL_AMD_conservative_depth
GL_AMD_draw_buffers_blend
GL_AMD_seamless_cubemap_per_texture
GL_AMD_shader_stencil_export
GL_AMD_shader_trinary_minmax
GL_ANGLE_texture_compression_dxt3
GL_ANGLE_texture_compression_dxt5
GL_APPLE_object_purgeable
GL_APPLE_packed_pixels
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_instanced
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_ballot
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_stencil_export
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_window_pos
GL_ATI_blend_equation_separate
GL_ATI_draw_buffers
GL_ATI_separate_stencil
GL_ATI_texture_env_combine3
GL_ATI_texture_float
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_copy_texture
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_gpu_program_parameters
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset
GL_EXT_polygon_offset_clamp
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_specular_color
GL_EXT_shader_integer_mix
GL_EXT_shader_samples_identical
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_subtexture
GL_EXT_texture
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_object
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_IBM_multimode_draw_arrays
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_INGR_blend_func_separate
GL_INTEL_performance_query
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_KHR_texture_compression_astc_ldr
GL_KHR_texture_compression_astc_sliced_3d
GL_MESA_pack_invert
GL_MESA_shader_integer_functions
GL_MESA_texture_signed_rgba
GL_MESA_window_pos
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_depth_clamp
GL_NV_light_max_exponent
GL_NV_packed_depth_stencil
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_env_combine4
GL_NV_texture_rectangle
GL_OES_EGL_image
GL_OES_read_format
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_border_clamp
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays

**Comment by thehans** [comment] 2017-10-31 01:06
@theopensourcerer If you launch openscad from the terminal and reproduce the issue, do you see any error messages etc output there?

And no errors in the OpenSCAD GUI console?

**Comment by theopensourcerer** [comment] 2017-10-31 07:37
Correct. 

It prints just the normal Compile and preview finished, and Rendering statements at the end and no errors (unless I have something wrong in the design code of course).

**Comment by theopensourcerer** [comment] 2017-10-31 07:37
Ahh - sorry I missed the first part of your question re. the cli. I will try that tonight - good idea.

**Comment by theopensourcerer** [comment] 2017-11-01 17:31
@thehans Just tried it and nothing logged to the terminal after starting it from the command line. The problem happens very frequently.

**Comment by theopensourcerer** [comment] 2017-11-01 17:45
Here's a bit more info. I created a really simple new drawing.

`cube([20,30,40],true);`

Just as a single cube. the preview always works. It doesn't disappear.

If I then do something like this:

```
difference() {
    cube([20,30,40],true);
    cube([10,10,10]);
}
```

The the preview disappears all the time. I can only view the drawing using F6. F5 produces an empty viewport.

If I comment out either of the two cubes in the difference() function, the preview drawing reappears again on save and F5/F6 work as expected..

No errors are reported anywhere.

**Comment by theopensourcerer** [comment] 2017-11-01 17:51
Something else... I closed (exited) OpenSCAD and re-opened it and loaded this "test" file above.. F5 and F6 worked as expected. I couldn't get F5 to not work until I resized OpenSCAD. It was full screen. When I shrank the window a bit, the preview disappeared again. Putting it back to full-screen didn't help to resolve the issue.

**Comment by freedriven** [comment] 2017-11-02 02:07
I'm have a very similar/same problem on Ubuntu 17.10, but I'm a new user of OpenSCAD and haven't used it on previous versions of Ubuntu.

Basically, several/many previous shapes will disappear until I close OpenSCAD and reopen the file.

**Comment by donbright** [comment] 2017-12-13 04:57
can you try a newer version of OpenSCAD?

**Comment by theopensourcerer** [comment] 2017-12-13 11:08
@donbright There don't appear to have been any more recent releases than the one the Ubuntu package maintainers are providing [1]... Is there a beta release or something?

[1] https://packages.ubuntu.com/artful/openscad

**Comment by freedriven** [comment] 2017-12-13 12:10
I downloaded the latest appimage (2017.12.13), and it appears to have fixed several of the problems I was having with the version in the standard Ubuntu repositories (2015.03). I'll update if I still find issues.
THANKS!

**Comment by freedriven** [comment] 2017-12-13 12:14
It appears there are development snapshots, both appimages and repositories) available here (this is where I found the 2017.12.13 appimage):
http://www.openscad.org/downloads.html

**Comment by theopensourcerer** [comment] 2017-12-13 12:52
@freedriven Thanks for the cluebat - I never looked "below the fold" ;-)

I'll test when I get home and report back (it'll be a day or two)

**Comment by theopensourcerer** [comment] 2017-12-14 10:45
I downloaded the x64 appimage and it doesn't exhibit the same symptoms as the Ubuntu packaged version. It is easy to replicate the problem. Open any reasonably complex design in the Ubuntu packaged version and change the from full screen to a smaller window - the F5 quick render disappears or only some parts of the image are shown. In the appimage code - this does not happen. 

Thanks.

**Comment by simon1tan** [comment] 2018-01-23 08:30
I am having a similar issue where some of my components do not show in preview but renders fine. Also installed from Ubuntu 17.10 repository. Just installed nightly and the preview looks working properly.

**Comment by kintel** [comment] 2018-01-23 13:26
Closing as fixed since newer versions works as expected.

**Closed by kintel** 2018-01-23 13:26 UTC

**Comment by markfinn** [comment] 2018-09-03 17:42
Newer versions don't work as expected.  I'm trying 2018.09.03.nightly right now.  From the previous comments I wonder if it is the appimage that worked, not the new versions (see https://github.com/openscad/openscad/issues/2157#issuecomment-351675118)

please re-open.

**Comment by donbright** [comment] 2018-09-03 17:59
@markfinn do you have

output of help/library info

an example .scad file that shows the problem reliably?

**Comment by t-paul** [comment] 2018-09-03 18:03
If the LibraryInfo shows anything lower than OpenCSG 1.4.2, we can't do much about it. Maybe there's a backport available somewhere. Ubuntu 18.04 is the first to ship with OpenCSG 1.4.2.

**Comment by donbright** [comment] 2018-09-03 18:05
back in the old days we had to ask people to build OpenCSG and CGAL on just about every distro since most distros did not have them. i think it would be possible to go back to that, and just ban building with older OpenCSG.

**Comment by markfinn** [comment] 2018-09-03 22:51
I'm trying both the PPA and nightly, both exibit the problems.  And I just went from 17.10 to 18.04. none of these fixes it.

Yes it's OpenCSG 1.4.2:

OpenSCAD Version: 2018.09.03.nightly (git ce08fcd)
System information: Linux 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 Ubuntu 18.04.1 LTS 12 CPUs 23.53 GB RAM
Compiler: GCC "7.3.0" 64bit
Boost version: 1_65_1
Eigen version: 3.3.4
CGAL version, kernels: 4.11, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.9.5
QScintilla version: 2.10.2
MingW build: No
GLib version: 2.56.1
libzip version: 
Application Path: /usr/bin
Documents Path: /home/mark/.local/share
Resource Path: /usr/share/openscad-nightly
User Library Path: /home/mark/.local/share/OpenSCAD/libraries
User Config Path: /home/mark/.config/OpenSCAD
Backup Path: /home/mark/.local/share/OpenSCAD/backups
OPENSCADPATH: 
OpenSCAD library path:
/home/mark/.local/share/OpenSCAD/libraries
/home/mark

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 2.0.0
OpenGL Version: 4.6.0 NVIDIA 390.48
GL Renderer: GeForce GTX 1050 Ti/PCIe/SSE2
GL Vendor: NVIDIA Corporation
RGBA(8880), depth(24), stencil(0)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(8880), depth(24), stencil(0)

GL Extensions:
GL_AMD_multi_draw_indirect
GL_AMD_seamless_cubemap_per_texture
GL_AMD_vertex_shader_layer
GL_AMD_vertex_shader_viewport_index
GL_ARB_ES2_compatibility
GL_ARB_ES3_1_compatibility
GL_ARB_ES3_2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_bindless_texture
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_compute_variable_group_size
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_direct_state_access
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_fragment_shader_interlock
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gl_spirv
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_gpu_shader_int64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_imaging
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_parallel_shader_compile
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_polygon_offset_clamp
GL_ARB_post_depth_coverage
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_locations
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_ballot
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shader_viewport_layer_array
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_sparse_buffer
GL_ARB_sparse_texture
GL_ARB_sparse_texture2
GL_ARB_sparse_texture_clamp
GL_ARB_spirv_extensions
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_filter_anisotropic
GL_ARB_texture_filter_minmax
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_draw_buffers
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_EXTX_framebuffer_mixed_formats
GL_EXT_Cg_shader
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_bindable_uniform
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_import_sync_object
GL_EXT_memory_object
GL_EXT_memory_object_fd
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset_clamp
GL_EXT_post_depth_coverage
GL_EXT_provoking_vertex
GL_EXT_raster_multisample
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_semaphore
GL_EXT_semaphore_fd
GL_EXT_separate_shader_objects
GL_EXT_separate_specular_color
GL_EXT_shader_image_load_formatted
GL_EXT_shader_image_load_store
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_sparse_texture2
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_filter_minmax
GL_EXT_texture_integer
GL_EXT_texture_lod
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_object
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback2
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_EXT_vertex_attrib_64bit
GL_EXT_window_rectangles
GL_EXT_x11_sync_object
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_parallel_shader_compile
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_KTX_buffer_region
GL_NVX_blend_equation_advanced_multi_draw_buffers
GL_NVX_conditional_render
GL_NVX_gpu_memory_info
GL_NVX_nvenc_interop
GL_NV_ES1_1_compatibility
GL_NV_ES3_1_compatibility
GL_NV_alpha_to_coverage_dither_control
GL_NV_bindless_multi_draw_indirect
GL_NV_bindless_multi_draw_indirect_count
GL_NV_bindless_texture
GL_NV_blend_equation_advanced
GL_NV_blend_equation_advanced_coherent
GL_NV_blend_minmax_factor
GL_NV_blend_square
GL_NV_clip_space_w_scaling
GL_NV_command_list
GL_NV_compute_program5
GL_NV_conditional_render
GL_NV_conservative_raster
GL_NV_conservative_raster_dilate
GL_NV_conservative_raster_pre_snap_triangles
GL_NV_copy_depth_to_color
GL_NV_copy_image
GL_NV_depth_buffer_float
GL_NV_depth_clamp
GL_NV_draw_texture
GL_NV_draw_vulkan_image
GL_NV_explicit_multisample
GL_NV_fence
GL_NV_fill_rectangle
GL_NV_float_buffer
GL_NV_fog_distance
GL_NV_fragment_coverage_to_color
GL_NV_fragment_program
GL_NV_fragment_program2
GL_NV_fragment_program_option
GL_NV_fragment_shader_interlock
GL_NV_framebuffer_mixed_samples
GL_NV_framebuffer_multisample_coverage
GL_NV_geometry_shader4
GL_NV_geometry_shader_passthrough
GL_NV_gpu_program4
GL_NV_gpu_program4_1
GL_NV_gpu_program5
GL_NV_gpu_program5_mem_extended
GL_NV_gpu_program_fp64
GL_NV_gpu_shader5
GL_NV_half_float
GL_NV_internalformat_sample_query
GL_NV_light_max_exponent
GL_NV_multisample_coverage
GL_NV_multisample_filter_hint
GL_NV_occlusion_query
GL_NV_packed_depth_stencil
GL_NV_parameter_buffer_object
GL_NV_parameter_buffer_object2
GL_NV_path_rendering
GL_NV_path_rendering_shared_edge
GL_NV_pixel_data_range
GL_NV_point_sprite
GL_NV_primitive_restart
GL_NV_query_resource
GL_NV_query_resource_tag
GL_NV_register_combiners
GL_NV_register_combiners2
GL_NV_robustness_video_memory_purge
GL_NV_sample_locations
GL_NV_sample_mask_override_coverage
GL_NV_shader_atomic_counters
GL_NV_shader_atomic_float
GL_NV_shader_atomic_float64
GL_NV_shader_atomic_fp16_vector
GL_NV_shader_atomic_int64
GL_NV_shader_buffer_load
GL_NV_shader_storage_buffer_object
GL_NV_shader_thread_group
GL_NV_shader_thread_shuffle
GL_NV_stereo_view_rendering
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_compression_vtc
GL_NV_texture_env_combine4
GL_NV_texture_multisample
GL_NV_texture_rectangle
GL_NV_texture_rectangle_compressed
GL_NV_texture_shader
GL_NV_texture_shader2
GL_NV_texture_shader3
GL_NV_transform_feedback
GL_NV_transform_feedback2
GL_NV_uniform_buffer_unified_memory
GL_NV_vdpau_interop
GL_NV_vertex_array_range
GL_NV_vertex_array_range2
GL_NV_vertex_attrib_integer_64bit
GL_NV_vertex_buffer_unified_memory
GL_NV_vertex_program
GL_NV_vertex_program1_1
GL_NV_vertex_program2
GL_NV_vertex_program2_option
GL_NV_vertex_program3
GL_NV_viewport_array2
GL_NV_viewport_swizzle
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_lod
GL_SGIX_depth_texture
GL_SGIX_shadow
GL_SUN_slice_accum

**Comment by markfinn** [comment] 2018-09-03 23:02
oooh.  setting "turn off rendering at" to an absurdly high value fixes it.  

With that set at the default of 2000 I get and a "simplified" object which works I get:

`Compiling design (CSG Products normalization)...
WARNING: Normalized tree is growing past 4000 elements. Aborting normalization. 
Normalized CSG tree has 1424 elements
Compile and preview finished.
Total rendering time: 0 hours, 0 minutes, 0 seconds`

but for a "complex" object (that fails) I get:

`Compiling design (CSG Products normalization)...
WARNING: Normalized tree is growing past 4000 elements. Aborting normalization. 
Normalized CSG tree has 1044 elements
Compile and preview finished.
Total rendering time: 0 hours, 0 minutes, 0 seconds`

I find it odd that the normalized tree has fewer objects when the scene is more complex.

For reference, when I set the "rendering off" threshold really high I get no warnings followed by 2638 elements for the complex and 1508 for the simple one. both render correctly.

code follows.  my "simple" and "complex" quoted above comes from changing on and off the element at:
`//ring
if (0) `

Code:
`use <threads.scad>

$fn=120;

module cap(knurled=0)
{
    union(){
        difference(){
            union(){
                cylinder(r=29, h=20);
                if (knurled) {
                    for(r=[0:45:360])
                        rotate([0,0,r])
                        translate([0,27,0])
                        cylinder(r=6, h=20);
                    for(r=[0:5:360])
                        rotate([0,0,r])
                        translate([0,29,0])
                        cylinder(r=.6, h=20);
                }
            }
            translate([0,0,-1])
            metric_thread (50.8, 4, 17, thread_size=4.5, rectangle=.5, internal=true);
            translate([0,0,-1])
            cylinder(r2=24, r1=24+4, h=4);

        }

    cylinder(r2=18+7/32*20, r1=18, h=20);

    }
}

//cap
if(0) 
translate([60,0,20])
rotate([180,0,0])
cap(knurled=1);


translate([-60,0,20])
rotate([180,0,0])
difference(){
    cap(knurled=1);
    cylinder(r=14, h=100, center=true);
    translate([0,0,16-100])
    cylinder(r=23, h=100);
}



//plug
if (1) 
    translate([0,0,10])
    difference(){
    union(){
        intersection(){
            translate([0,0,4-20])
            cylinder(r2=18+7/32*20, r1=18, h=20);
            translate([0,0,-10])
            cylinder(r=50, h=10);
            translate([0,0,-15])
            cylinder(r2=32, r1=13.5, h=20);
        }
        translate([0,0,-1])
        english_thread (17/16, 11.5, .75, leadin=1);
    }

    cylinder(r=10, h=100, center=true);
       translate([0,0,-11])
         cylinder(r2=9, r1=12, h=5);
}`

**Comment by t-paul** [comment] 2018-09-03 23:59
The current default is actually 100000 and even higher values should be ok on most machines nowadays.

Anyway, this has nothing to do with the originally reported issue then.
