### ISSUE TITLE
Declare a parameter with an integer value but allowing decimal places.

### ISSUE THREAD

**Issue by Nartlof** [openscad/openscad#3774] opened 2021-05-15 15:59 UTC
When a parameter is created with an integer value, it is not possible add decimal places on the customizer, For example:

`//Parameter`
`A=20;`
`cube(A);`

On the customizer the parameter A appears as 20 and only integer values will be accepted. If one wants a cube with size 20.5, the code must be changed as so:

`//Parameter`
`A=20.5;`
`cube(A);`

Now the value of A appears on the customizer as 20.5 and the user can enter any value, as long it has just one decimal place. A value as 20.25 will not be allowed.
My suggestion is that a parameter could be declared as:

`//Parameter`
`A=20.00;`
`cube(A);`

If declared in this form, the system should allow the customizer to accept as many decimal places for parameter as the number of zeros put after the dot.

**Comment by thehans** [comment] 2021-05-15 16:14
Duplicate of #3098

**Closed by thehans** 2021-05-15 16:14 UTC
