### ISSUE TITLE
Misaligned characters and cursor in editor area - multiple display resolution issue

### ISSUE THREAD

**Issue by vguenther** [openscad/openscad#2362] opened 2018-03-31 12:56 UTC
When entering text in the Editor the cursor does not proceed the full character width.

<img width="78" alt="2018-03-31-openscad-1" src="https://user-images.githubusercontent.com/13488061/38163292-1757986a-34f2-11e8-8495-f5f7c9e2198d.PNG">

When entering brackets, these are placed in the displayed cursor position rather than behind the last character.

<img width="76" alt="2018-03-31-openscad-2" src="https://user-images.githubusercontent.com/13488061/38163304-32d72d26-34f2-11e8-95a2-521e62fef8b1.PNG">

When opening an scad-file, similar behaviour occurs.

<img width="250" alt="2018-03-31-openscad-3" src="https://user-images.githubusercontent.com/13488061/38163306-38de8caa-34f2-11e8-9bc3-c561666d89e0.PNG">

I tried it with the Windows snapshots OpenSCAD-2018.03.10-x86-64-Installer.exe and OpenSCAD-2018.03.10-x86-64-Installer.exe for windows in Windows10. I am quite sure it was initially ok after the first installation of OpenSCAD-2018.03.10-x86-64-Installer. I observe the issue on one single Windws10 Notebook with Intel HD620 

<img width="185" alt="2018-03-31-openscad-4" src="https://user-images.githubusercontent.com/13488061/38163373-7b31e3d0-34f3-11e8-88a6-86cb4351bbd6.PNG">

On this notebook the problem is reproducible even after new installation of openSCAD. On another Windows10 Notebook everything is working fine.  (both on same -current- Windows version)

Behaviour occurs no matter if simple editor or qscintilla is selected.
It does not seem to depend on neither font nor size.
Nothing worth mentioning in the registry entries.

Any hints how to get around this?

Best regards, 
Volker

**Comment by t-paul** [comment] 2018-03-31 13:11
I'm not sure how that's possible except with a font that's either broken or not understood by the editor component we are using. Can you try changing the editor font in preferences and see if that issue goes away with a different font?
The default selection for the editor font sometimes seems to be a bit random.

**Comment by vguenther** [comment] 2018-03-31 15:50
Actually I tried many editor fonts in the preferences dialog. Every single one I tried showed the described behaviour. Changing the size did not help either.

**Comment by vguenther** [comment] 2018-04-01 10:29
I found out more about it. The issue occurs in a setup with an external monitor with a higher resolution.

The pattern is: 
Step 1) I open an scad-file on the internal display -> text in editor looks fine.
Step 2) I drag the window with the opened file to the external display -> text in editor still looks fine. But: it immediately messes up when I enter a single character.
Step 3) I close OpenScad and reopen it with doubleclick on filename, forcing it to reopen on external display -> text in editor looks messed up as shown in the original post.
Step 4) I drag the window to the internal display -> text in editor still messed. But after entering a character it looks fine again.
Step 5) I close and reopen on internal display - text in editor looks fine.

**Comment by t-paul** [comment] 2018-04-01 11:22
Ok, I guess we can't do muich about this then. We have no control over the internal rendering of the GUI framework. That sounds a bit like https://bugreports.qt.io/browse/QTBUG-48242 which is supposedly fixed in Qt 5.9 but OpenSCAD-2018.03.10 should already have that.

**Comment by MichaelAtOz** [comment] 2018-04-01 12:31
I'll try to remember to test this on my other PC, on W7, where - from memory, I set the screen DPI to a non-STD higher resolution, and I seem to recall similar issues. 
Also this DPI change, I suspect, makes things like the splash window, be non optimal size.
Unless you think the problem is elsewhere?

**Comment by t-paul** [comment] 2018-04-01 12:47
I see similar things like tiny window sizes on the new notebook which has 3840x2160 at 13". So running (on Linux) with 2 times scaling gives a nice sharp picture. So while the font is scaled ok for the welcome screen, the window itself is too tiny to look sensible, same with the preferences window.

Those things we can probably do something about. But the actual font rendering and especially that strange positioning issue comes very likely from either somewhere in Qt (supposedly fixed) or QScintilla (the text editor component, maybe ignoring that fix). I can't find a bug tracker for QScintilla, maybe the mailing list is the only option for reporting issues.

With (as far as I'm aware) no developer working on Windows there's not a good chance to dig that deep into third party code to actually fix that soon.

**Comment by kintel** [comment] 2018-04-01 15:47
This sounds like a duplicate of #1624 

There was one report of this symptom going away after switching to the simple editor (note that it requires a restart of OpenSCAD to take effect).

**Comment by vguenther** [comment] 2018-04-01 18:08
I just double-checked: Changing preferences from "QScintilla" to "simple editor" and restarting OpenSCAD does not make the symptom go away.

![image](https://user-images.githubusercontent.com/13488061/38176072-283a8ed4-35e8-11e8-8d69-81153834494c.png)

**Comment by kintel** [comment] 2018-04-01 18:18
@vguenther Thx, that definitely take QScintilla out of the loop. That also means that this should likely be reproducible with a plain Qt application.

**Comment by t-paul** [comment] 2018-04-01 18:27
I'm pretty sure that is not yet showing the simple editor. That has no folding, has it? That setting will need OpenSCAD to restart to be effective I think.

**Comment by kintel** [comment] 2018-04-01 18:45
Good point. @vguenther Could you try again?

**Comment by vguenther** [comment] 2018-04-01 22:58
I again checked the registry settings and restarted OpenSCAD again. Both registry and preferences say "simple editor", but symptom is still there. I agree there seems to be no visual difference at all. As a newbie I'm not aware of the differences between the editors, but to me it looks like OpenSCAD just ignores the editortype setting - which seems to an issue not directly related to the original one. 
I will try to find out which editor is actually used and I will have a closer look at #1624 asap and update accordingly.

**Comment by t-paul** [comment] 2018-04-01 23:04
Hmm, strange, I checked with both Linux version and Windows version via wine. In both cases switching does work. No idea why it's not working natively.

**Comment by vguenther** [comment] 2018-04-01 23:15
ok - I just learned folding is a discriminator and I definitely still have folding. I compared it to Linux version in virtualbox. I confirm switching works in Linux but not in Windows. Should I open another issue for that?

**Comment by kintel** [comment] 2018-04-01 23:53
Could the editor switching issue be related to language setting? I see we compare some strings against the English combobox contents, while the screenshot above show a German locale.

**Comment by MichaelAtOz** [comment] 2018-04-02 00:01
Switching works on my W7/64, with OpenSCAD 2018.01.06 (latest I have ATM).

**Comment by t-paul** [comment] 2018-04-02 01:52
Yep, it's picking up the translated value so that never matches. See #2365.

**Comment by t-paul** [comment] 2018-04-07 12:50
Updated Windows snapshots are online. Please try again with those. Switching the editor type should now work regardless of the language settings.

**Comment by vguenther** [comment] 2018-04-08 09:08
I confirm now editor switching works fine with German language setting. Thx. I will try in my dual screen setup asap to finally confirm this issue is a duplicate of #1624.

**Comment by vguenther** [comment] 2018-04-08 09:25
As expected the issue is specific to qscintilla editor. It goes away after switching to simple editor. So we obviously have a duplicate.

**Comment by kintel** [comment] 2018-04-09 00:55
@vguenther Thanks for following up! Closing this as a duplicate of #1624

**Closed by kintel** 2018-04-09 00:55 UTC
